using '../modules/geneva-health-function/functionapp.bicep'

param deploy = {{ .genevaHealthFunction.deploy }}
param location = '{{ .region }}'
param functionAppName = '{{ .genevaHealthFunction.functionAppName }}'
param appServicePlanName = '{{ .genevaHealthFunction.appServicePlanName }}'
param storageAccountName = '{{ .genevaHealthFunction.storageAccountName }}'
param managedIdentityName = '{{ .genevaHealthFunction.managedIdentityName }}'
param svcKeyVaultUrl = '__svcKeyVaultUrl__'
param keyVaultCertificateName = '{{ .genevaHealthFunction.certificateName }}'
param genevaMonitoringAccount = '{{ .genevaHealthFunction.monitoringAccount }}'
param genevaHealthEnvironment = '{{ .genevaHealthFunction.healthEnvironment }}'
param hcpMonitorPrometheusQueryEndpoint = '__hcpMonitorPrometheusQueryEndpoint__'
param svcKeyVaultName = '{{ .serviceKeyVault.name }}'
param serviceKeyVaultSubscription = '__serviceKeyVaultSubscription__'
param svcKeyVaultResourceGroup = '{{ .serviceKeyVault.rg }}'
param genevaDefaultRegion = '{{ .region }}'
param containerImage = '{{ .genevaHealthFunction.image.registry }}/{{ .genevaHealthFunction.image.repository }}@{{ .genevaHealthFunction.image.digest }}'
param svcAcrName = '{{ .acr.svc.name }}'
param svcAcrResourceGroup = '{{ .global.rg }}'
