// Code generated by MockGen. DO NOT EDIT.
// Source: ../../backend/pkg/azure/client/client_builder.go
//
// Generated by this command:
//
//	mockgen-v0.5.0 -typed -source=../../backend/pkg/azure/client/client_builder.go -destination=azure_client_builder.go -package mocks github.com/Azure/ARO-HCP/backend/pkg/azure/client ClientBuilder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	arm "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	gomock "go.uber.org/mock/gomock"

	client "github.com/Azure/ARO-HCP/backend/pkg/azure/client"
)

// MockClientBuilder is a mock of ClientBuilder interface.
type MockClientBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockClientBuilderMockRecorder
	isgomock struct{}
}

// MockClientBuilderMockRecorder is the mock recorder for MockClientBuilder.
type MockClientBuilderMockRecorder struct {
	mock *MockClientBuilder
}

// NewMockClientBuilder creates a new mock instance.
func NewMockClientBuilder(ctrl *gomock.Controller) *MockClientBuilder {
	mock := &MockClientBuilder{ctrl: ctrl}
	mock.recorder = &MockClientBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientBuilder) EXPECT() *MockClientBuilderMockRecorder {
	return m.recorder
}

// ResourceProvidersClient mocks base method.
func (m *MockClientBuilder) ResourceProvidersClient(tenantID, subscriptionID string, options *arm.ClientOptions) client.ResourceProvidersClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceProvidersClient", tenantID, subscriptionID, options)
	ret0, _ := ret[0].(client.ResourceProvidersClient)
	return ret0
}

// ResourceProvidersClient indicates an expected call of ResourceProvidersClient.
func (mr *MockClientBuilderMockRecorder) ResourceProvidersClient(tenantID, subscriptionID, options any) *MockClientBuilderResourceProvidersClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceProvidersClient", reflect.TypeOf((*MockClientBuilder)(nil).ResourceProvidersClient), tenantID, subscriptionID, options)
	return &MockClientBuilderResourceProvidersClientCall{Call: call}
}

// MockClientBuilderResourceProvidersClientCall wrap *gomock.Call
type MockClientBuilderResourceProvidersClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientBuilderResourceProvidersClientCall) Return(arg0 client.ResourceProvidersClient) *MockClientBuilderResourceProvidersClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientBuilderResourceProvidersClientCall) Do(f func(string, string, *arm.ClientOptions) client.ResourceProvidersClient) *MockClientBuilderResourceProvidersClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientBuilderResourceProvidersClientCall) DoAndReturn(f func(string, string, *arm.ClientOptions) client.ResourceProvidersClient) *MockClientBuilderResourceProvidersClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
