apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mgmt-agent-backup-cleanup
  namespace: velero
rules:
- apiGroups:
  - velero.io
  resources:
  - backups
  - backuprepositories
  - backupstoragelocations
  - schedules
  - datauploads
  - datadownloads
  - podvolumebackups
  - podvolumerestores
  - restores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  verbs:
  - get
  - list
  - create
  - patch
  - delete
- apiGroups:
  - velero.io
  resources:
  - backuprepositories
  verbs:
  - patch
  - delete
- apiGroups:
  - mgmtagent.aro-hcp.azure.com
  resources:
  - backuprepositorycleanups
  verbs:
  - get
  - list
  - watch
  - create
  - patch
- apiGroups:
  - mgmtagent.aro-hcp.azure.com
  resources:
  - backuprepositorycleanups/status
  verbs:
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mgmt-agent-backup-cleanup
  namespace: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mgmt-agent-backup-cleanup
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
