apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeMitigation.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mgmt-agent
data:
  {{ .Values.nodeMitigation.configKey }}: |
{{ .Values.nodeMitigation.configuration | indent 4 }}
