FROM --platform=linux/amd64 mcr.microsoft.com/oss/go/microsoft/golang:1.24-fips-cbl-mariner2.0@sha256:374281fe968134a44bcc7bd4b9e2d55dda61dcaa942fee5dda28cd38d54619cd as builder

WORKDIR /app
COPY --from=ARO-HCP test ./test
COPY --from=ARO-HCP internal ./internal
RUN cd test/e2e && make e2etest

FROM --platform=linux/amd64 mcr.microsoft.com/cbl-mariner/distroless/base:2.0-nonroot@sha256:a5d5928601847a40c81fa397df33136c285866c974bf91ed94d688390fcc33f3

WORKDIR /
ENV SETUP_FILEPATH=/data/e2e-setup.json
COPY --from=builder /app/test/e2e/e2e.test /e2e.test
ENTRYPOINT ["/e2e.test", "--ginkgo.timeout", "1h", "--ginkgo.junit-report", "/data/junit-report.xml", "--ginkgo.trace"]
