FROM registry.ci.openshift.org/aro-hcp/aro-hcp-ci-images:aro-hcp-e2e-base-ci
USER root
WORKDIR /opt/app-root/src/github.com/Azure/ARO-HCP
COPY . .
ENV GOFLAGS='-mod=readonly'
ENV GOPROXY='https://proxy.golang.org|direct'
RUN make build-hcpctl && \
    make -C tooling/templatize templatize && \
    make -C test/ build && \
    go clean -cache -modcache && rm -f go.work.sum
RUN chmod 777 /opt/app-root/src/github.com/Azure/ARO-HCP
