#!/bin/bash

# E2E Environment Variables Setup for Local Run

export LOCATION="westus3"
export AROHCP_ENV="development"

if [ "${DEPLOY_ENV}" = "prow" ]; then
    export USER="j${BUILD_ID: -3}"
fi

if [ -z "${CUSTOMER_SUBSCRIPTION:-}" ]; then
    export CUSTOMER_SUBSCRIPTION="$(az account show --output tsv --query 'name')"
fi