apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: aro-hcp-prometheus
spec:
  replicas: 2
  version: 2.35.0
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  # remoteWrite:
  #   - url: "https://your-remote-write-endpoint"
  #     basicAuth:
  #       username: your-username
  #       password:
  #         secretKeyRef:
  #           name: remote-write-secret
  #           key: password
  #     writeRelabelConfigs:
  #       - sourceLabels: [__name__]
  #         targetLabel: job
  #     proxyURL: "http://proxy.example.com:1234"
  #     queueConfig:
  #       maxSamplesPerSend: 1000
