apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: konnectivity-server
  name: konnectivity-server
  namespace: prometheus
spec:
  podMetricsEndpoints:
  - targetPort: 8093
    path: /metrics
  namespaceSelector:
    matchLabels:
      hypershift.openshift.io/hosted-control-plane: "true"
  selector:
    matchLabels:
      app: kube-apiserver
