apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fleet-controller
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-controller
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fleet-controller
        image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}'
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
        env:
        - name: AZURE_TOKEN_CREDENTIALS
          value: "WorkloadIdentityCredential"
        args:
        - controller
        - --cloud-environment
        - '{{ .Values.cloudEnvironmentName }}'
        - --region
        - '{{ .Values.region }}'
        - --cosmos-url
        - '{{ .Values.cosmos.url }}'
        - --cosmos-name
        - '{{ .Values.cosmos.name }}'
        - --clusters-service-url
        - 'http://clusters-service.{{ .Values.clustersService.namespace }}.svc.cluster.local:8000'
        - --kube-namespace
        - '{{ .Values.controller.namespace }}'
        ports:
        - name: healthz
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8081
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 5
          periodSeconds: 5
