// Code generated by MockGen. DO NOT EDIT.
// Source: crud_management_cluster_content.go
//
// Generated by this command:
//
//	mockgen-v0.6.0 -typed -source=crud_management_cluster_content.go -destination=mock_crud_management_cluster_content.go -package database ManagementClusterContentCRUD
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	azcosmos "github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos"
	gomock "go.uber.org/mock/gomock"

	api "github.com/Azure/ARO-HCP/internal/api"
)

// MockManagementClusterContentCRUD is a mock of ManagementClusterContentCRUD interface.
type MockManagementClusterContentCRUD struct {
	ctrl     *gomock.Controller
	recorder *MockManagementClusterContentCRUDMockRecorder
	isgomock struct{}
}

// MockManagementClusterContentCRUDMockRecorder is the mock recorder for MockManagementClusterContentCRUD.
type MockManagementClusterContentCRUDMockRecorder struct {
	mock *MockManagementClusterContentCRUD
}

// NewMockManagementClusterContentCRUD creates a new mock instance.
func NewMockManagementClusterContentCRUD(ctrl *gomock.Controller) *MockManagementClusterContentCRUD {
	mock := &MockManagementClusterContentCRUD{ctrl: ctrl}
	mock.recorder = &MockManagementClusterContentCRUDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagementClusterContentCRUD) EXPECT() *MockManagementClusterContentCRUDMockRecorder {
	return m.recorder
}

// AddCreateToTransaction mocks base method.
func (m *MockManagementClusterContentCRUD) AddCreateToTransaction(ctx context.Context, transaction DBTransaction, newObj *api.ManagementClusterContent, opts *azcosmos.TransactionalBatchItemOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCreateToTransaction", ctx, transaction, newObj, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCreateToTransaction indicates an expected call of AddCreateToTransaction.
func (mr *MockManagementClusterContentCRUDMockRecorder) AddCreateToTransaction(ctx, transaction, newObj, opts any) *MockManagementClusterContentCRUDAddCreateToTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCreateToTransaction", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).AddCreateToTransaction), ctx, transaction, newObj, opts)
	return &MockManagementClusterContentCRUDAddCreateToTransactionCall{Call: call}
}

// MockManagementClusterContentCRUDAddCreateToTransactionCall wrap *gomock.Call
type MockManagementClusterContentCRUDAddCreateToTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDAddCreateToTransactionCall) Return(arg0 string, arg1 error) *MockManagementClusterContentCRUDAddCreateToTransactionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDAddCreateToTransactionCall) Do(f func(context.Context, DBTransaction, *api.ManagementClusterContent, *azcosmos.TransactionalBatchItemOptions) (string, error)) *MockManagementClusterContentCRUDAddCreateToTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDAddCreateToTransactionCall) DoAndReturn(f func(context.Context, DBTransaction, *api.ManagementClusterContent, *azcosmos.TransactionalBatchItemOptions) (string, error)) *MockManagementClusterContentCRUDAddCreateToTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddReplaceToTransaction mocks base method.
func (m *MockManagementClusterContentCRUD) AddReplaceToTransaction(ctx context.Context, transaction DBTransaction, newObj *api.ManagementClusterContent, opts *azcosmos.TransactionalBatchItemOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReplaceToTransaction", ctx, transaction, newObj, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddReplaceToTransaction indicates an expected call of AddReplaceToTransaction.
func (mr *MockManagementClusterContentCRUDMockRecorder) AddReplaceToTransaction(ctx, transaction, newObj, opts any) *MockManagementClusterContentCRUDAddReplaceToTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReplaceToTransaction", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).AddReplaceToTransaction), ctx, transaction, newObj, opts)
	return &MockManagementClusterContentCRUDAddReplaceToTransactionCall{Call: call}
}

// MockManagementClusterContentCRUDAddReplaceToTransactionCall wrap *gomock.Call
type MockManagementClusterContentCRUDAddReplaceToTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDAddReplaceToTransactionCall) Return(arg0 string, arg1 error) *MockManagementClusterContentCRUDAddReplaceToTransactionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDAddReplaceToTransactionCall) Do(f func(context.Context, DBTransaction, *api.ManagementClusterContent, *azcosmos.TransactionalBatchItemOptions) (string, error)) *MockManagementClusterContentCRUDAddReplaceToTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDAddReplaceToTransactionCall) DoAndReturn(f func(context.Context, DBTransaction, *api.ManagementClusterContent, *azcosmos.TransactionalBatchItemOptions) (string, error)) *MockManagementClusterContentCRUDAddReplaceToTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockManagementClusterContentCRUD) Create(ctx context.Context, newObj *api.ManagementClusterContent, options *azcosmos.ItemOptions) (*api.ManagementClusterContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, newObj, options)
	ret0, _ := ret[0].(*api.ManagementClusterContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockManagementClusterContentCRUDMockRecorder) Create(ctx, newObj, options any) *MockManagementClusterContentCRUDCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).Create), ctx, newObj, options)
	return &MockManagementClusterContentCRUDCreateCall{Call: call}
}

// MockManagementClusterContentCRUDCreateCall wrap *gomock.Call
type MockManagementClusterContentCRUDCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDCreateCall) Return(arg0 *api.ManagementClusterContent, arg1 error) *MockManagementClusterContentCRUDCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDCreateCall) Do(f func(context.Context, *api.ManagementClusterContent, *azcosmos.ItemOptions) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDCreateCall) DoAndReturn(f func(context.Context, *api.ManagementClusterContent, *azcosmos.ItemOptions) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockManagementClusterContentCRUD) Delete(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagementClusterContentCRUDMockRecorder) Delete(ctx, resourceID any) *MockManagementClusterContentCRUDDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).Delete), ctx, resourceID)
	return &MockManagementClusterContentCRUDDeleteCall{Call: call}
}

// MockManagementClusterContentCRUDDeleteCall wrap *gomock.Call
type MockManagementClusterContentCRUDDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDDeleteCall) Return(arg0 error) *MockManagementClusterContentCRUDDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDDeleteCall) Do(f func(context.Context, string) error) *MockManagementClusterContentCRUDDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockManagementClusterContentCRUDDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockManagementClusterContentCRUD) Get(ctx context.Context, resourceID string) (*api.ManagementClusterContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceID)
	ret0, _ := ret[0].(*api.ManagementClusterContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManagementClusterContentCRUDMockRecorder) Get(ctx, resourceID any) *MockManagementClusterContentCRUDGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).Get), ctx, resourceID)
	return &MockManagementClusterContentCRUDGetCall{Call: call}
}

// MockManagementClusterContentCRUDGetCall wrap *gomock.Call
type MockManagementClusterContentCRUDGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDGetCall) Return(arg0 *api.ManagementClusterContent, arg1 error) *MockManagementClusterContentCRUDGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDGetCall) Do(f func(context.Context, string) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDGetCall) DoAndReturn(f func(context.Context, string) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockManagementClusterContentCRUD) GetByID(ctx context.Context, cosmosID string) (*api.ManagementClusterContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, cosmosID)
	ret0, _ := ret[0].(*api.ManagementClusterContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockManagementClusterContentCRUDMockRecorder) GetByID(ctx, cosmosID any) *MockManagementClusterContentCRUDGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).GetByID), ctx, cosmosID)
	return &MockManagementClusterContentCRUDGetByIDCall{Call: call}
}

// MockManagementClusterContentCRUDGetByIDCall wrap *gomock.Call
type MockManagementClusterContentCRUDGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDGetByIDCall) Return(arg0 *api.ManagementClusterContent, arg1 error) *MockManagementClusterContentCRUDGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDGetByIDCall) Do(f func(context.Context, string) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDGetByIDCall) DoAndReturn(f func(context.Context, string) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockManagementClusterContentCRUD) List(ctx context.Context, opts *DBClientListResourceDocsOptions) (DBClientIterator[api.ManagementClusterContent], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(DBClientIterator[api.ManagementClusterContent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockManagementClusterContentCRUDMockRecorder) List(ctx, opts any) *MockManagementClusterContentCRUDListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).List), ctx, opts)
	return &MockManagementClusterContentCRUDListCall{Call: call}
}

// MockManagementClusterContentCRUDListCall wrap *gomock.Call
type MockManagementClusterContentCRUDListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDListCall) Return(arg0 DBClientIterator[api.ManagementClusterContent], arg1 error) *MockManagementClusterContentCRUDListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDListCall) Do(f func(context.Context, *DBClientListResourceDocsOptions) (DBClientIterator[api.ManagementClusterContent], error)) *MockManagementClusterContentCRUDListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDListCall) DoAndReturn(f func(context.Context, *DBClientListResourceDocsOptions) (DBClientIterator[api.ManagementClusterContent], error)) *MockManagementClusterContentCRUDListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Replace mocks base method.
func (m *MockManagementClusterContentCRUD) Replace(ctx context.Context, newObj *api.ManagementClusterContent, options *azcosmos.ItemOptions) (*api.ManagementClusterContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, newObj, options)
	ret0, _ := ret[0].(*api.ManagementClusterContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockManagementClusterContentCRUDMockRecorder) Replace(ctx, newObj, options any) *MockManagementClusterContentCRUDReplaceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockManagementClusterContentCRUD)(nil).Replace), ctx, newObj, options)
	return &MockManagementClusterContentCRUDReplaceCall{Call: call}
}

// MockManagementClusterContentCRUDReplaceCall wrap *gomock.Call
type MockManagementClusterContentCRUDReplaceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagementClusterContentCRUDReplaceCall) Return(arg0 *api.ManagementClusterContent, arg1 error) *MockManagementClusterContentCRUDReplaceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagementClusterContentCRUDReplaceCall) Do(f func(context.Context, *api.ManagementClusterContent, *azcosmos.ItemOptions) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDReplaceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagementClusterContentCRUDReplaceCall) DoAndReturn(f func(context.Context, *api.ManagementClusterContent, *azcosmos.ItemOptions) (*api.ManagementClusterContent, error)) *MockManagementClusterContentCRUDReplaceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
