// Code generated by MockGen. DO NOT EDIT.
// Source: crud_untyped_resource.go
//
// Generated by this command:
//
//	mockgen-v0.6.0 -typed -source=crud_untyped_resource.go -destination=mock_crud_untyped_resource.go -package database UntypedResourceCRUD
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	arm "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	gomock "go.uber.org/mock/gomock"
)

// MockUntypedResourceCRUD is a mock of UntypedResourceCRUD interface.
type MockUntypedResourceCRUD struct {
	ctrl     *gomock.Controller
	recorder *MockUntypedResourceCRUDMockRecorder
	isgomock struct{}
}

// MockUntypedResourceCRUDMockRecorder is the mock recorder for MockUntypedResourceCRUD.
type MockUntypedResourceCRUDMockRecorder struct {
	mock *MockUntypedResourceCRUD
}

// NewMockUntypedResourceCRUD creates a new mock instance.
func NewMockUntypedResourceCRUD(ctrl *gomock.Controller) *MockUntypedResourceCRUD {
	mock := &MockUntypedResourceCRUD{ctrl: ctrl}
	mock.recorder = &MockUntypedResourceCRUDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUntypedResourceCRUD) EXPECT() *MockUntypedResourceCRUDMockRecorder {
	return m.recorder
}

// Child mocks base method.
func (m *MockUntypedResourceCRUD) Child(resourceType arm.ResourceType, resourceName string) (UntypedResourceCRUD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Child", resourceType, resourceName)
	ret0, _ := ret[0].(UntypedResourceCRUD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Child indicates an expected call of Child.
func (mr *MockUntypedResourceCRUDMockRecorder) Child(resourceType, resourceName any) *MockUntypedResourceCRUDChildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Child", reflect.TypeOf((*MockUntypedResourceCRUD)(nil).Child), resourceType, resourceName)
	return &MockUntypedResourceCRUDChildCall{Call: call}
}

// MockUntypedResourceCRUDChildCall wrap *gomock.Call
type MockUntypedResourceCRUDChildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUntypedResourceCRUDChildCall) Return(arg0 UntypedResourceCRUD, arg1 error) *MockUntypedResourceCRUDChildCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUntypedResourceCRUDChildCall) Do(f func(arm.ResourceType, string) (UntypedResourceCRUD, error)) *MockUntypedResourceCRUDChildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUntypedResourceCRUDChildCall) DoAndReturn(f func(arm.ResourceType, string) (UntypedResourceCRUD, error)) *MockUntypedResourceCRUDChildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockUntypedResourceCRUD) Delete(ctx context.Context, resourceID *arm.ResourceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUntypedResourceCRUDMockRecorder) Delete(ctx, resourceID any) *MockUntypedResourceCRUDDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUntypedResourceCRUD)(nil).Delete), ctx, resourceID)
	return &MockUntypedResourceCRUDDeleteCall{Call: call}
}

// MockUntypedResourceCRUDDeleteCall wrap *gomock.Call
type MockUntypedResourceCRUDDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUntypedResourceCRUDDeleteCall) Return(arg0 error) *MockUntypedResourceCRUDDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUntypedResourceCRUDDeleteCall) Do(f func(context.Context, *arm.ResourceID) error) *MockUntypedResourceCRUDDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUntypedResourceCRUDDeleteCall) DoAndReturn(f func(context.Context, *arm.ResourceID) error) *MockUntypedResourceCRUDDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByCosmosID mocks base method.
func (m *MockUntypedResourceCRUD) DeleteByCosmosID(ctx context.Context, partitionKey, cosmosID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCosmosID", ctx, partitionKey, cosmosID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCosmosID indicates an expected call of DeleteByCosmosID.
func (mr *MockUntypedResourceCRUDMockRecorder) DeleteByCosmosID(ctx, partitionKey, cosmosID any) *MockUntypedResourceCRUDDeleteByCosmosIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCosmosID", reflect.TypeOf((*MockUntypedResourceCRUD)(nil).DeleteByCosmosID), ctx, partitionKey, cosmosID)
	return &MockUntypedResourceCRUDDeleteByCosmosIDCall{Call: call}
}

// MockUntypedResourceCRUDDeleteByCosmosIDCall wrap *gomock.Call
type MockUntypedResourceCRUDDeleteByCosmosIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUntypedResourceCRUDDeleteByCosmosIDCall) Return(arg0 error) *MockUntypedResourceCRUDDeleteByCosmosIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUntypedResourceCRUDDeleteByCosmosIDCall) Do(f func(context.Context, string, string) error) *MockUntypedResourceCRUDDeleteByCosmosIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUntypedResourceCRUDDeleteByCosmosIDCall) DoAndReturn(f func(context.Context, string, string) error) *MockUntypedResourceCRUDDeleteByCosmosIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockUntypedResourceCRUD) Get(ctx context.Context, resourceID *arm.ResourceID) (*TypedDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceID)
	ret0, _ := ret[0].(*TypedDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUntypedResourceCRUDMockRecorder) Get(ctx, resourceID any) *MockUntypedResourceCRUDGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUntypedResourceCRUD)(nil).Get), ctx, resourceID)
	return &MockUntypedResourceCRUDGetCall{Call: call}
}

// MockUntypedResourceCRUDGetCall wrap *gomock.Call
type MockUntypedResourceCRUDGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUntypedResourceCRUDGetCall) Return(arg0 *TypedDocument, arg1 error) *MockUntypedResourceCRUDGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUntypedResourceCRUDGetCall) Do(f func(context.Context, *arm.ResourceID) (*TypedDocument, error)) *MockUntypedResourceCRUDGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUntypedResourceCRUDGetCall) DoAndReturn(f func(context.Context, *arm.ResourceID) (*TypedDocument, error)) *MockUntypedResourceCRUDGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockUntypedResourceCRUD) List(ctx context.Context, opts *DBClientListResourceDocsOptions) (DBClientIterator[TypedDocument], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(DBClientIterator[TypedDocument])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUntypedResourceCRUDMockRecorder) List(ctx, opts any) *MockUntypedResourceCRUDListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUntypedResourceCRUD)(nil).List), ctx, opts)
	return &MockUntypedResourceCRUDListCall{Call: call}
}

// MockUntypedResourceCRUDListCall wrap *gomock.Call
type MockUntypedResourceCRUDListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUntypedResourceCRUDListCall) Return(arg0 DBClientIterator[TypedDocument], arg1 error) *MockUntypedResourceCRUDListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUntypedResourceCRUDListCall) Do(f func(context.Context, *DBClientListResourceDocsOptions) (DBClientIterator[TypedDocument], error)) *MockUntypedResourceCRUDListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUntypedResourceCRUDListCall) DoAndReturn(f func(context.Context, *DBClientListResourceDocsOptions) (DBClientIterator[TypedDocument], error)) *MockUntypedResourceCRUDListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRecursive mocks base method.
func (m *MockUntypedResourceCRUD) ListRecursive(ctx context.Context, opts *DBClientListResourceDocsOptions) (DBClientIterator[TypedDocument], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecursive", ctx, opts)
	ret0, _ := ret[0].(DBClientIterator[TypedDocument])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecursive indicates an expected call of ListRecursive.
func (mr *MockUntypedResourceCRUDMockRecorder) ListRecursive(ctx, opts any) *MockUntypedResourceCRUDListRecursiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecursive", reflect.TypeOf((*MockUntypedResourceCRUD)(nil).ListRecursive), ctx, opts)
	return &MockUntypedResourceCRUDListRecursiveCall{Call: call}
}

// MockUntypedResourceCRUDListRecursiveCall wrap *gomock.Call
type MockUntypedResourceCRUDListRecursiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUntypedResourceCRUDListRecursiveCall) Return(arg0 DBClientIterator[TypedDocument], arg1 error) *MockUntypedResourceCRUDListRecursiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUntypedResourceCRUDListRecursiveCall) Do(f func(context.Context, *DBClientListResourceDocsOptions) (DBClientIterator[TypedDocument], error)) *MockUntypedResourceCRUDListRecursiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUntypedResourceCRUDListRecursiveCall) DoAndReturn(f func(context.Context, *DBClientListResourceDocsOptions) (DBClientIterator[TypedDocument], error)) *MockUntypedResourceCRUDListRecursiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
