// Copyright 2025 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package database

import (
	"encoding/json"
	"strings"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	azcorearm "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/google/uuid"

	"github.com/Azure/ARO-HCP/internal/api"
	"github.com/Azure/ARO-HCP/internal/api/arm"
)

type BaseDocument struct {
	ID string `json:"id,omitempty"`

	// https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/time-to-live
	TimeToLive int `json:"ttl,omitempty"`

	// System-defined properties generated by Cosmos DB
	CosmosResourceID  string      `json:"_rid,omitempty"`
	CosmosSelf        string      `json:"_self,omitempty"`
	CosmosETag        azcore.ETag `json:"_etag,omitempty"`
	CosmosAttachments string      `json:"_attachments,omitempty"`
	CosmosTimestamp   int         `json:"_ts,omitempty"`
}

// newBaseDocument returns a baseDocument with a unique ID.
func NewBaseDocument() BaseDocument {
	return BaseDocument{ID: uuid.New().String()}
}

type TypedDocument struct {
	BaseDocument
	PartitionKey string          `json:"partitionKey"`
	ResourceType string          `json:"resourceType"`
	Properties   json.RawMessage `json:"properties"`
}

// newTypedDocument returns a TypedDocument from a ResourceType.
func NewTypedDocument(partitionKey string, resourceType azcorearm.ResourceType) *TypedDocument {
	return &TypedDocument{
		BaseDocument: NewBaseDocument(),
		PartitionKey: strings.ToLower(partitionKey),
		ResourceType: strings.ToLower(resourceType.String()),
	}
}

// HCPClusterDocument represents a customer desired HCP Cluster.
// To transition from our current state using cluster-service as half the source of truth to a state where
// cosmos contains all the desired state and all the observed state, we are basing the schema on ResourceDocument.
type HCPClusterDocument struct {
	// do NOT marshal this field.  These are system properties that we will set on read so we can look at them, but the values
	// in this type are never serialized because the typed document is the wrapper, not the content.
	TypedDocument    `json:"-"`
	ResourceDocument `json:",inline"`

	// CustomerDesiredState represents information from the user.  Some minimal validation may happen prior to persisting
	// this information, but it is entirely possible that this state does not reflect an achievable reality.
	// This information is necessary to determine the HostedCluster and supporting resources that are desired.
	CustomerDesiredState CustomerDesiredState `json:"customerDesiredState"`

	ServiceProviderState ServiceProviderState `json:"serviceProviderState"`
}

func NewHCPClusterDocument(resourceID *azcorearm.ResourceID) *HCPClusterDocument {
	return &HCPClusterDocument{
		ResourceDocument: ResourceDocument{
			ResourceID: resourceID,
		},
	}
}

// GetValidTypes returns the valid resource types for a ResourceDocument.
func (doc HCPClusterDocument) GetValidTypes() []string {
	return []string{
		api.ClusterResourceType.String(),
	}
}

func (doc HCPClusterDocument) GetResourceType() azcorearm.ResourceType {
	return api.ClusterResourceType

}

type CustomerDesiredState struct {
	// HCPOpenShiftCluster contains the desired state from a customer.  It is filtered to only those fields that customers
	// are able to set.
	// We will whitelist specific fields as we go through to prevent conflicts.
	HCPOpenShiftCluster api.HCPOpenShiftCluster `json:"hcpOpenShiftCluster"`
}

type ServiceProviderState struct {
	// HCPOpenShiftCluster contains the service provider owned state.  It is filtered to only those fields that the service provider owns.
	// We will whitelist specific fields as we go through to prevent conflicts.
	HCPOpenShiftCluster api.HCPOpenShiftCluster `json:"hcpOpenShiftCluster"`
}

// ClearUnownedFields force resets fields in the document down to only the allowed fields.  We do this because our
// internal API types are not generated and so it's significant work to create types for customer versus service provider.
func ClearUnownedFields(in *HCPClusterDocument) {
	in.CustomerDesiredState.HCPOpenShiftCluster = KeepCustomerOwnedFieldsFromHCPOpenShiftCluster(in.CustomerDesiredState.HCPOpenShiftCluster)
	in.ServiceProviderState.HCPOpenShiftCluster = KeepServiceProviderOwnedFieldsFromHCPOpenShiftCluster(in.ServiceProviderState.HCPOpenShiftCluster)
}

// KeepCustomerOwnedFieldsFromHCPOpenShiftCluster creates a new instance and copies the data that a customer is allowed to set.
// This approach makes the whitelist extremely clear.
// Once the vast majority of fields are customer owned, we can choose to invert the model.
// TODO filter using the create/update (but not read) tagging on api.HCPOpenShiftCluster struct
func KeepCustomerOwnedFieldsFromHCPOpenShiftCluster(in api.HCPOpenShiftCluster) api.HCPOpenShiftCluster {
	out := api.HCPOpenShiftCluster{
		TrackedResource: arm.TrackedResource{
			Location: in.Location,
		},
		Properties: api.HCPOpenShiftClusterProperties{
			DNS: api.DNSProfile{
				BaseDomainPrefix: in.Properties.DNS.BaseDomain,
			},
		},
	}

	return out
}

// KeepServiceProviderOwnedFieldsFromHCPOpenShiftCluster creates a new instance and copies the data that a service provider is allowed to set.
// This approach makes the whitelist extremely clear.
// Once the vast majority of fields are customer owned, we can choose to invert the model.
// TODO filter using the read (but not create/update) tagging on api.HCPOpenShiftCluster struct
func KeepServiceProviderOwnedFieldsFromHCPOpenShiftCluster(in api.HCPOpenShiftCluster) api.HCPOpenShiftCluster {
	out := api.HCPOpenShiftCluster{
		Properties: api.HCPOpenShiftClusterProperties{
			DNS: api.DNSProfile{
				BaseDomain: in.Properties.DNS.BaseDomain,
			},
		},
	}

	return out
}
