// Copyright 2025 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generate

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-logr/logr"
	"github.com/spf13/cobra"

	"github.com/Azure/ARO-HCP/tooling/kustoctl/pkg/config"
)

type ingestionMappingEntry struct {
	Column     string                       `json:"column"`
	Properties ingestionMappingPathProperty `json:"Properties"`
}

type ingestionMappingPathProperty struct {
	Path string `json:"path"`
}

func newTableCommand() *cobra.Command {
	var inputYAML, outputDir string

	cmd := &cobra.Command{
		Use:   "table",
		Short: "Generate KQL table definitions from a YAML schema",
		Long: `Generate .kql files containing Kusto table definitions and ingestion
mappings from a YAML configuration file.

Each table defined in the input YAML produces a .kql file with:
  1. A ".create-merge table" command declaring the column schema
  2. A ".create-or-alter table ingestion json mapping" command`,
		RunE: func(cmd *cobra.Command, args []string) error {
			logger := logr.FromContextOrDiscard(cmd.Context())
			return runGenerateTable(logger, inputYAML, outputDir)
		},
	}

	cmd.Flags().StringVar(&inputYAML, "input", "", "Path to the tables YAML configuration file")
	cmd.Flags().StringVar(&outputDir, "output-dir", "", "Directory to write generated .kql files")

	_ = cmd.MarkFlagRequired("input")
	_ = cmd.MarkFlagRequired("output-dir")

	return cmd
}

func runGenerateTable(logger logr.Logger, inputYAML, outputDir string) error {
	cfg, err := config.NewConfigFromFile(inputYAML)
	if err != nil {
		return fmt.Errorf("reading %s: %w", inputYAML, err)
	}

	for _, table := range cfg.Tables {
		kql := generateKQL(table.Name, cfg.ResolveTableColumns(table))

		outPath := filepath.Join(outputDir, table.Name+".kql")
		if err := os.WriteFile(outPath, []byte(kql), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", outPath, err)
		}
		logger.Info("Generated", "file", outPath)
	}

	return nil
}

func generateKQL(tableName string, columns []config.Column) string {
	var sb strings.Builder

	sb.WriteString("// This file is generated by tooling/kustoctl. Do not edit manually.\n")
	sb.WriteString("// Source: tooling/kustoctl/tables.yaml\n\n")

	sb.WriteString(fmt.Sprintf(".create-merge table %s (\n", tableName))
	for i, col := range columns {
		sep := ","
		if i == len(columns)-1 {
			sep = ""
		}
		sb.WriteString(fmt.Sprintf("  %s: %s%s\n", col.Name, col.Type, sep))
	}
	sb.WriteString(")\n\n")

	sb.WriteString(fmt.Sprintf(".create-or-alter table %s ingestion json mapping 'ingestionMapping'\n", tableName))
	sb.WriteString("```\n")

	entries := make([]ingestionMappingEntry, len(columns))
	for i, col := range columns {
		entries[i] = ingestionMappingEntry{
			Column:     col.Name,
			Properties: ingestionMappingPathProperty{Path: col.Mapping},
		}
	}

	jsonBytes, _ := json.MarshalIndent(entries, "", "  ")
	sb.Write(jsonBytes)
	sb.WriteString("\n```\n")

	return sb.String()
}
