# Uses a multi-stage container build to build the frontend.
#
ARG REGISTRY
FROM ${REGISTRY}/ubi8/go-toolset:1.20.10 AS builder

USER root
ENV GOPATH=/root/go
RUN mkdir -p /app
WORKDIR /app

COPY . /app
RUN make frontend

FROM ${REGISTRY}/ubi8/ubi-minimal
RUN microdnf update && microdnf clean all
COPY --from=builder /app/aro /usr/local/bin/
ENTRYPOINT ["aro"]
EXPOSE 2222/tcp 8080/tcp 8443/tcp 8444/tcp 8445/tcp
USER 1000