apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mgmt-agent
  name: ama-metrics-configmap-reader
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: mgmt-agent
  name: ama-metrics-configmap-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ama-metrics-configmap-reader
subjects:
- kind: ServiceAccount
  name: ama-metrics-serviceaccount
  namespace: kube-system
