apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
data:
  prometheus-config: |-
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: "custom-app-metrics"
        kubernetes_sd_configs:
          - role: pod
        metric_relabel_configs:
          - source_labels: [microsoft_metrics_include_label]
            regex: "^$"
            target_label: microsoft_metrics_include_label
            replacement: "service"
            action: replace
