#!/bin/bash

source ../../demo/env_vars

error_msg() {
    echo "Error: $1"
    exit 1
}

is_dev_subscription() {
    return $(test "$(az account show --query name --output tsv)" = "ARO Hosted Control Planes (EA Subscription 1)")
}

is_redhat_user(){
    user=$(az account show --query user.name --output tsv)
    regex=".*@redhat.com"
    return $([[ "$user" =~ $regex ]])
}

is_service_principal(){
    return $(test "$(az account show --query user.type --output tsv)" = "servicePrincipal")
}

export resource_group=$CUSTOMER_RG_NAME
export vnet_name=$CUSTOMER_VNET_NAME
export subnet_name=$CUSTOMER_VNET_PODNETWORK1
export subscription=1d3378d3-5a3f-4712-85a1-2485495dfc4b
export resource=RedHatOpenShift
export linked_resource_type=Microsoft.RedHatOpenShift/hcpOpenShiftClusters
export location="uksouth"
