#!/bin/bash

error_msg() {
    echo "Error: $1"
    exit 1
}

is_dev_subscription() {
    return $(test "$(az account show --query name --output tsv)" = "ARO Hosted Control Planes (EA Subscription 1)")
}

is_redhat_user(){
    user=$(az account show --query user.name --output tsv)
    regex=".*@redhat.com"
    return $([[ "$user" =~ $regex ]])
}

is_service_principal(){
    return $(test "$(az account show --query user.type --output tsv)" = "servicePrincipal")
}

export resource_group=$USER-swiftv2-test
export vnet_name=$USER-swiftv2-test-vnet
export subnet_name=$USER-swiftv2-test-subnet
export subscription=1d3378d3-5a3f-4712-85a1-2485495dfc4b
export resource=RedHatOpenShift
export linked_resource_type=Microsoft.RedHatOpenShift/hcpOpenShiftClusters
export linked_resource_name=
export location="westus3"
export address_prefix="10.32.0.0/16"
export subnet_prefix="10.32.0.0/24"