continue_on_error: true
match_type: doublestar
exclude:
- '**/zz_fixture_*.yaml'
- 'frontend/deploy/templates/frontend.deployment.yaml'
- 'frontend/deploy/templates/frontend-v2.deployment.yaml'
formatter:
  type: basic
  indentless_arrays: true
