#!/bin/bash

PROJECT_ROOT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

DEPLOY_ENV=$1
INPUT=$2
OUTPUT=$3

if [ "$DEPLOY_ENV" == "personal-dev" ]; then
    REGION_STAMP=$USER
else
    REGION_STAMP=$DEPLOY_ENV
fi

if [ -z "$CLOUD" ]; then
    CLOUD="public"
fi

if [ -z "$REGION" ]; then
    REGION="westus3"
fi

if [ -z "$CXSTAMP" ]; then
    CXSTAMP="1"
fi

CONFIG_FILE=${PROJECT_ROOT_DIR}/config/config.yaml
if [ -n "$INPUT" ] && [ -n "$OUTPUT" ]; then
    go run ${PROJECT_ROOT_DIR}/tooling/templatize/main.go generate \
        --config-file=${CONFIG_FILE} \
        --cloud=$CLOUD \
        --deploy-env=$DEPLOY_ENV \
        --region=$REGION \
        --region-stamp=${REGION_STAMP} \
        --cx-stamp=$CXSTAMP \
        --input=$INPUT \
        --output=$OUTPUT
else
    go run ${PROJECT_ROOT_DIR}/tooling/templatize/main.go inspect \
        --config-file=${CONFIG_FILE} \
        --cloud=$CLOUD \
        --deploy-env=$DEPLOY_ENV \
        --region=$REGION \
        --region-stamp=${REGION_STAMP} \
        --cx-stamp=$CXSTAMP
fi
