cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('frontendLogs')
| where timestamp between ({{ kqlDatetime .FullStartTime }} .. {{ kqlDatetime .FullEndTime }})
| where log.client_request_id == '{{ .ClientRequestID }}'
| where log.msg == 'response complete'
| project asyncOperationId = replace_regex(tolower(tostring(parse_url(tostring(log["Header---Azure-AsyncOperation"])).Path)), @"/locations/[^/]+", "")
| where tostring(asyncOperationId) != ''
| distinct asyncOperationId
