{{ if .Values.enabled }}
# Alter kubelet config for better stability at higher scales
# Ref: https://issues.redhat.com/browse/ARO-13357
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: kubelet-parameters
  name: set-kubelet-parameters-for-scale
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  minReadySeconds: 30
  selector:
    matchLabels:
      component: kubelet-parameters
      tier: node
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: kubelet-parameters
        tier: node
    spec:
      nodeSelector:
        aro-hcp.azure.com/role: worker
      initContainers:
      - command:
        - nsenter
        - --target
        - "1"
        - --mount
        - --uts
        - --ipc
        - --net
        - --pid
        - --
        - sh
        - -c
        - |
{{ regexReplaceAll "(?m)^ +$" (.Files.Get "files/system-reserved.sh" | indent 10) "" }}
          if grep -q '\-\-collector.netclass.netlink' /usr/local/bin/node-exporter-startup.sh;then
             echo "collector.netclass.netlink parameter already updated in node-exporter configuration"
          else
             sed -i 's/--no-collector.arp.netlink/--no-collector.arp.netlink --collector.netclass.netlink/g' /usr/local/bin/node-exporter-startup.sh
             systemctl daemon-reload
             systemctl restart node-exporter
             echo "collector.netclass.netlink parameter has been updated in node-exporter configuration"
          fi
        image: alpine
        imagePullPolicy: IfNotPresent
        name: apply-kubelet-parameters
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      containers:
      - name: kubelet-parameters
        image: alpine
        imagePullPolicy: IfNotPresent
        command: ["sleep", "infinity"]
        readinessProbe:
          exec:
            command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - curl
            - --fail
            - --silent
            - --show-error
            - --noproxy
            - '*'
            - --connect-timeout
            - "2"
            - --max-time
            - "5"
            - http://127.0.0.1:10248/healthz
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 1
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
{{ end }}
