// Code generated by MockGen. DO NOT EDIT.
// Source: keyvault_client.go
//
// Generated by this command:
//
//	mockgen-v0.6.0 -typed -source=keyvault_client.go -destination=mock_keyvault_client.go -package client KeyVaultVaultsClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	armkeyvault "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyVaultVaultsClient is a mock of KeyVaultVaultsClient interface.
type MockKeyVaultVaultsClient struct {
	ctrl     *gomock.Controller
	recorder *MockKeyVaultVaultsClientMockRecorder
	isgomock struct{}
}

// MockKeyVaultVaultsClientMockRecorder is the mock recorder for MockKeyVaultVaultsClient.
type MockKeyVaultVaultsClientMockRecorder struct {
	mock *MockKeyVaultVaultsClient
}

// NewMockKeyVaultVaultsClient creates a new mock instance.
func NewMockKeyVaultVaultsClient(ctrl *gomock.Controller) *MockKeyVaultVaultsClient {
	mock := &MockKeyVaultVaultsClient{ctrl: ctrl}
	mock.recorder = &MockKeyVaultVaultsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyVaultVaultsClient) EXPECT() *MockKeyVaultVaultsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockKeyVaultVaultsClient) Get(ctx context.Context, resourceGroupName, vaultName string, options *armkeyvault.VaultsClientGetOptions) (armkeyvault.VaultsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, vaultName, options)
	ret0, _ := ret[0].(armkeyvault.VaultsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKeyVaultVaultsClientMockRecorder) Get(ctx, resourceGroupName, vaultName, options any) *MockKeyVaultVaultsClientGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKeyVaultVaultsClient)(nil).Get), ctx, resourceGroupName, vaultName, options)
	return &MockKeyVaultVaultsClientGetCall{Call: call}
}

// MockKeyVaultVaultsClientGetCall wrap *gomock.Call
type MockKeyVaultVaultsClientGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyVaultVaultsClientGetCall) Return(arg0 armkeyvault.VaultsClientGetResponse, arg1 error) *MockKeyVaultVaultsClientGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyVaultVaultsClientGetCall) Do(f func(context.Context, string, string, *armkeyvault.VaultsClientGetOptions) (armkeyvault.VaultsClientGetResponse, error)) *MockKeyVaultVaultsClientGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyVaultVaultsClientGetCall) DoAndReturn(f func(context.Context, string, string, *armkeyvault.VaultsClientGetOptions) (armkeyvault.VaultsClientGetResponse, error)) *MockKeyVaultVaultsClientGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
