// Code generated by MockGen. DO NOT EDIT.
// Source: network_security_groups_client.go
//
// Generated by this command:
//
//	mockgen-v0.6.0 -typed -source=network_security_groups_client.go -destination=mock_network_security_groups_client.go -package client NetworkSecurityGroupsClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v6"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkSecurityGroupsClient is a mock of NetworkSecurityGroupsClient interface.
type MockNetworkSecurityGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkSecurityGroupsClientMockRecorder
	isgomock struct{}
}

// MockNetworkSecurityGroupsClientMockRecorder is the mock recorder for MockNetworkSecurityGroupsClient.
type MockNetworkSecurityGroupsClientMockRecorder struct {
	mock *MockNetworkSecurityGroupsClient
}

// NewMockNetworkSecurityGroupsClient creates a new mock instance.
func NewMockNetworkSecurityGroupsClient(ctrl *gomock.Controller) *MockNetworkSecurityGroupsClient {
	mock := &MockNetworkSecurityGroupsClient{ctrl: ctrl}
	mock.recorder = &MockNetworkSecurityGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkSecurityGroupsClient) EXPECT() *MockNetworkSecurityGroupsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockNetworkSecurityGroupsClient) Get(ctx context.Context, resourceGroupName, networkSecurityGroupName string, options *armnetwork.SecurityGroupsClientGetOptions) (armnetwork.SecurityGroupsClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, networkSecurityGroupName, options)
	ret0, _ := ret[0].(armnetwork.SecurityGroupsClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNetworkSecurityGroupsClientMockRecorder) Get(ctx, resourceGroupName, networkSecurityGroupName, options any) *MockNetworkSecurityGroupsClientGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNetworkSecurityGroupsClient)(nil).Get), ctx, resourceGroupName, networkSecurityGroupName, options)
	return &MockNetworkSecurityGroupsClientGetCall{Call: call}
}

// MockNetworkSecurityGroupsClientGetCall wrap *gomock.Call
type MockNetworkSecurityGroupsClientGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkSecurityGroupsClientGetCall) Return(arg0 armnetwork.SecurityGroupsClientGetResponse, arg1 error) *MockNetworkSecurityGroupsClientGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkSecurityGroupsClientGetCall) Do(f func(context.Context, string, string, *armnetwork.SecurityGroupsClientGetOptions) (armnetwork.SecurityGroupsClientGetResponse, error)) *MockNetworkSecurityGroupsClientGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkSecurityGroupsClientGetCall) DoAndReturn(f func(context.Context, string, string, *armnetwork.SecurityGroupsClientGetOptions) (armnetwork.SecurityGroupsClientGetResponse, error)) *MockNetworkSecurityGroupsClientGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
