// Code generated by MockGen. DO NOT EDIT.
// Source: keyvault_client.go
//
// Generated by this command:
//
//	mockgen-v0.6.0 -typed -source=keyvault_client.go -destination=mock_keyvault_client.go -package client KeyVaultKeysClient
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	azkeys "github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyVaultKeysClient is a mock of KeyVaultKeysClient interface.
type MockKeyVaultKeysClient struct {
	ctrl     *gomock.Controller
	recorder *MockKeyVaultKeysClientMockRecorder
	isgomock struct{}
}

// MockKeyVaultKeysClientMockRecorder is the mock recorder for MockKeyVaultKeysClient.
type MockKeyVaultKeysClientMockRecorder struct {
	mock *MockKeyVaultKeysClient
}

// NewMockKeyVaultKeysClient creates a new mock instance.
func NewMockKeyVaultKeysClient(ctrl *gomock.Controller) *MockKeyVaultKeysClient {
	mock := &MockKeyVaultKeysClient{ctrl: ctrl}
	mock.recorder = &MockKeyVaultKeysClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyVaultKeysClient) EXPECT() *MockKeyVaultKeysClientMockRecorder {
	return m.recorder
}

// GetKey mocks base method.
func (m *MockKeyVaultKeysClient) GetKey(ctx context.Context, name, version string, options *azkeys.GetKeyOptions) (azkeys.GetKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", ctx, name, version, options)
	ret0, _ := ret[0].(azkeys.GetKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockKeyVaultKeysClientMockRecorder) GetKey(ctx, name, version, options any) *MockKeyVaultKeysClientGetKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockKeyVaultKeysClient)(nil).GetKey), ctx, name, version, options)
	return &MockKeyVaultKeysClientGetKeyCall{Call: call}
}

// MockKeyVaultKeysClientGetKeyCall wrap *gomock.Call
type MockKeyVaultKeysClientGetKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyVaultKeysClientGetKeyCall) Return(arg0 azkeys.GetKeyResponse, arg1 error) *MockKeyVaultKeysClientGetKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyVaultKeysClientGetKeyCall) Do(f func(context.Context, string, string, *azkeys.GetKeyOptions) (azkeys.GetKeyResponse, error)) *MockKeyVaultKeysClientGetKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyVaultKeysClientGetKeyCall) DoAndReturn(f func(context.Context, string, string, *azkeys.GetKeyOptions) (azkeys.GetKeyResponse, error)) *MockKeyVaultKeysClientGetKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
