module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.7

replace cloud.google.com/go => cloud.google.com/go v0.123.0

replace github.com/go-openapi/testify/v2 => github.com/go-openapi/testify/v2 v2.0.2

exclude github.com/linode/linodego v1.0.0

exclude github.com/grpc-ecosystem/grpc-gateway v1.14.7

exclude google.golang.org/api v0.30.0

require github.com/prometheus/prometheus v0.302.1 // cmd/promtool
