---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: arobit-forwarder
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: arobit-forwarder
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    ## Istio Labels: https://istio.io/docs/ops/deployment/requirements/
    app: arobit-forwarder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: arobit-forwarder
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arobit-forwarder
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app: arobit-forwarder
        azure.workload.identity/use: "true"
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/forwarder-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: '{{ .Values.forwarder.serviceAccountName }}'
      shareProcessNamespace: true
      containers:
        - name: fluentbit
          image: {{ .Values.forwarder.fluentbit.image.registry }}/{{ .Values.forwarder.fluentbit.image.repository }}@{{ .Values.forwarder.fluentbit.image.digest }}
          imagePullPolicy: '{{ .Values.forwarder.fluentbit.image.pullPolicy }}'
          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - -c
            - /forwarder/etc/fluent-bit.conf
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: forward
              containerPort: 24224
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          securityContext: 
            privileged: false
            allowPrivilegeEscalation: false
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              drop: ['ALL']
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: machine-id
              mountPath: /etc/machine-id
              readOnly: true
            - name: flb-storage
              mountPath: /var/fluent-bit/flb-storage
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: flb-config
              mountPath: /forwarder/etc
              readOnly: true
            - name: kusto
              mountPath: /var/fluent-bit/kusto
      volumes:
        - name: kusto
          emptyDir: {}
        - name: sp-host
          hostPath:
            type: Directory
            path: /etc/kubernetes/
        - name: flb-storage
          emptyDir: {}
        - name: machine-id
          hostPath:
            path: /etc/machine-id
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: cacrt-host
          hostPath:
            type: File
            path: /etc/ssl/certs/ca-certificates.crt
        - name: flb-config
          configMap:
            name: arobit-forwarder
            defaultMode: 0755
