# yamllint disable rule:line-length rule:syntax
{{- if eq .Values.forwarder.clusterType "mgmt" }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: namespace-resourceid-mapping
  namespace: '{{ .Release.Namespace }}'
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: namespace-resourceid-mapping
      spec:
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
        severity: low
        evaluationInterval:
          compliant: 2m
          noncompliant: 30s
        object-templates-raw: |
          - complianceType: mustonlyhave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: namespace-resourceid-mapping
                namespace: '{{ .Release.Namespace }}'
              data:
                {{ `{{- range (lookup "hypershift.openshift.io/v1beta1" "HostedCluster" "" "").items }}` }}
                {{ `{{- if index .metadata.annotations "azure.microsoft.com/hcp-cluster-azure-resource-id" }}` }}
                {{ `'{{ .metadata.namespace }}-{{ .metadata.name }}'` }}: {{ `'{{ index .metadata.annotations "azure.microsoft.com/hcp-cluster-azure-resource-id" }}'` }}
                {{ `{{- end }}` }}
                {{ `{{- end }}` }}
{{- end }}
