# yamllint disable rule:line-length rule:syntax
{{- if eq .Values.forwarder.clusterType "mgmt" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: namespace-resourceid-mapping
  namespace: '{{ .Release.Namespace }}'
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/clusterset: default
          name: local-cluster
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
{{- end }}
