// Copyright 2026 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/Azure/ARO-HCP/tooling/kusto-table-creation/config"
)

// ingestionMappingEntry represents a single entry in the JSON ingestion mapping.
type ingestionMappingEntry struct {
	Column     string                       `json:"column"`
	Properties ingestionMappingPathProperty `json:"Properties"`
}

type ingestionMappingPathProperty struct {
	Path string `json:"path"`
}

// generateKQL produces a .kql file containing two Kusto control commands:
//
//  1. A ".create-merge table" command that declares the column schema. Using
//     create-merge (rather than create-or-alter) lets new columns be added
//     without dropping existing data or requiring a full table rebuild.
//
//  2. A ".create-or-alter table ... ingestion json mapping" command that maps
//     each column to its JSON path in the ingestion payload. The mapping is
//     emitted as pretty-printed JSON inside a KQL markdown block (``` ... ```)
func generateKQL(tableName string, columns []config.Column) string {
	var sb strings.Builder

	sb.WriteString("// This file is generated by tooling/kusto-table-creation. Do not edit manually.\n")
	sb.WriteString("// Source: tooling/kusto-table-creation/tables.yaml\n\n")

	// .create-merge table
	sb.WriteString(fmt.Sprintf(".create-merge table %s (\n", tableName))
	for i, col := range columns {
		sep := ","
		if i == len(columns)-1 {
			sep = ""
		}
		sb.WriteString(fmt.Sprintf("  %s: %s%s\n", col.Name, col.Type, sep))
	}
	sb.WriteString(")\n\n")

	// .create-or-alter ingestion json mapping
	sb.WriteString(fmt.Sprintf(".create-or-alter table %s ingestion json mapping 'ingestionMapping'\n", tableName))
	sb.WriteString("```\n")

	entries := make([]ingestionMappingEntry, len(columns))
	for i, col := range columns {
		entries[i] = ingestionMappingEntry{
			Column:     col.Name,
			Properties: ingestionMappingPathProperty{Path: col.Mapping},
		}
	}

	jsonBytes, _ := json.MarshalIndent(entries, "", "  ")
	sb.Write(jsonBytes)
	sb.WriteString("\n```\n")

	return sb.String()
}
