---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.forwarder.serviceAccountName }}
  labels: {{- include "arobit.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "arobit.name" . }}-forwarder
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
      azure.workload.identity/client-id: '{{ .Values.forwarder.mdsd.geneva.managedIdentityId }}'