apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-state-metrics-crs-config
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: kube-state-metrics-crs
data:
  config.yaml: |
    {{- toYaml .Values.customResourceState.config | nindent 4 }}
