apiVersion: {{ .Values.monitoringApiGroup }}/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics-crs
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: kube-state-metrics-crs
spec:
  endpoints:
  - port: http-metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics-crs
  namespaceSelector:
    matchNames:
    - '{{ .Release.Namespace }}'
