apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: fleet-registration
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: fleet-registration
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: '{{ .Values.serviceAccountName }}'
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fleet-registration
        image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}'
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        env:
        - name: AZURE_TOKEN_CREDENTIALS
          value: "WorkloadIdentityCredential"
        args:
        - register
        - --cloud-environment
        - '{{ .Values.cloudEnvironmentName }}'
        - --cosmos-url
        - '{{ .Values.cosmos.url }}'
        - --cosmos-name
        - '{{ .Values.cosmos.name }}'
        - --stamp-identifier
        - '{{ .Values.registration.stampIdentifier }}'
        {{- if eq .Values.registration.autoApprove true }}
        - --auto-approve
        {{- end }}
        - --scheduling-policy
        {{- if eq .Values.registration.provisionShardStatus "active" }}
        - 'Schedulable'
        {{- else }}
        - 'Unschedulable'
        {{- end }}
        - --aks-resource-id
        - '{{ .Values.registration.aksResourceID }}'
        - --public-dns-zone-resource-id
        - '{{ .Values.registration.publicDNSZoneResourceID }}'
        - --hosted-clusters-secrets-keyvault-url
        - '{{ .Values.registration.hostedClustersSecretsKeyVaultURL }}'
        - --hosted-clusters-managed-identities-keyvault-url
        - '{{ .Values.registration.hostedClustersManagedIdentitiesKeyVaultURL }}'
        - --maestro-consumer-name
        - '{{ .Values.registration.maestroConsumerName }}'
        - --hosted-clusters-secrets-keyvault-mi-client-id
        - '{{ .Values.registration.hostedClustersSecretsKeyVaultManagedIdentityClientID }}'
        - --maestro-rest-api-url
        - '{{ .Values.registration.maestroRESTAPIURL }}'
        - --maestro-grpc-target
        - '{{ .Values.registration.maestroGRPCTarget }}'
        - --kube-applier-cosmos-container-name
        - '{{ .Values.registration.kubeApplierCosmosContainerName }}'
