# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "arohcp hcp-open-shift-cluster external-auth create",
)
class Create(AAZCommand):
    """Create a ExternalAuth

    :example: ExternalAuths_CreateOrUpdate_MaximumSet
        az arohcp hcp-open-shift-cluster external-auth create --resource-group rgopenapi --hcp-open-shift-cluster-name hcpCluster-name --external-auth-name my-cool-auth --issuer "{url:'https://microsoft.com/a',audiences:[audience1,audience2,audience3,audience4,audience5],ca:lrakpuqodeqscdauefb}" --clients "[{component:{name:my-cool-component,auth-client-namespace:my-cool-namespace},client-id:vobxtzobefgl,extra-scopes:[ejmvezdxvoozyiickteiqnvpxqciep],type:Confidential}]" --claim "{mappings:{username:{claim:utlmketyrdxmwijowjzbuqyawuoqrlriryuknigayeviriulgjvuwvxjrsrhpmvavyyxzapgkfeyedcklnoddeviibefgvubvecffqgdhntammtlwjsjemhsqhafmmorskpuwbtjgkoggxq,prefix:ojmwi,prefix-policy:mdbghfytgejdqobfllqmajtc},groups:{claim:icvcoadhpyprqygxyvqhewaycjdtzrwjzbjgmyralburdaolouyvkymfpetymlcwpqsoteryaatoapieizbsnttmkkxsrhyaacnucznujhgmxkmnmgtcjntjsmuabplpoyxberrjdikkkqqiqfnlvwngpbfajzhxzdgqicoconqtrrstzzumdurgfsheypcm,prefix:kjlxhbjdvwarcwdu}},validation-rules:[{type:RequiredClaim,required-claim:{claim:ciapdmvrnfitudpx,required-value:mqzzjiozgxfgflhdrnwawpke}}]}"
    """

    _aaz_info = {
        "version": "2025-12-23-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.redhatopenshift/hcpopenshiftclusters/{}/externalauths/{}", "2025-12-23-preview"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.external_auth_name = AAZStrArg(
            options=["-n", "--name", "--external-auth-name"],
            help="The name of the ExternalAuth",
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z][-a-zA-Z0-9]{1,15}$",
            ),
        )
        _args_schema.hcp_open_shift_cluster_name = AAZStrArg(
            options=["-c", "--cluster-name", "--hcp-open-shift-cluster-name"],
            help="The name of the HcpOpenShiftCluster",
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z][-a-zA-Z0-9]{1,52}[a-zA-Z0-9]$",
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.claim = AAZObjectArg(
            options=["--claim"],
            arg_group="Properties",
            help="External Auth claim This configures how claims are validated and applied.",
        )
        _args_schema.clients = AAZListArg(
            options=["--clients"],
            arg_group="Properties",
            help="External Auth OIDC clients There must not be more than 20 entries and entries must have unique namespace/name pairs.",
            fmt=AAZListArgFormat(
                max_length=20,
            ),
        )
        _args_schema.issuer = AAZObjectArg(
            options=["--issuer"],
            arg_group="Properties",
            help="Token Issuer profile",
        )

        claim = cls._args_schema.claim
        claim.mappings = AAZObjectArg(
            options=["mappings"],
            help="The claim mappings",
            required=True,
        )
        claim.validation_rules = AAZListArg(
            options=["validation-rules"],
            help="The claim validation rules",
        )

        mappings = cls._args_schema.claim.mappings
        mappings.groups = AAZObjectArg(
            options=["groups"],
            help="The claim mappings groups.",
        )
        mappings.username = AAZObjectArg(
            options=["username"],
            help="The claim mappings username.",
            required=True,
        )

        groups = cls._args_schema.claim.mappings.groups
        groups.claim = AAZStrArg(
            options=["claim"],
            help="Claim name of the external profile",
            required=True,
            fmt=AAZStrArgFormat(
                max_length=256,
                min_length=1,
            ),
        )
        groups.prefix = AAZStrArg(
            options=["prefix"],
            help="Prefix for the claim external profile If this is specified prefixPolicy will be set to \"Prefix\" by default",
        )

        username = cls._args_schema.claim.mappings.username
        username.claim = AAZStrArg(
            options=["claim"],
            help="Claim name of the external profile",
            required=True,
            fmt=AAZStrArgFormat(
                max_length=256,
                min_length=1,
            ),
        )
        username.prefix = AAZStrArg(
            options=["prefix"],
            help="Prefix for the claim external profile Must be set when the prefixPolicy field is set to 'Prefix' and must be unset otherwise.",
        )
        username.prefix_policy = AAZStrArg(
            options=["prefix-policy"],
            help="Prefix policy is an optional field that configures how a prefix should be applied to the value of the JWT claim specified in the 'claim' field.  Allowed values are 'Prefix', 'NoPrefix', and 'None'. If not specified, the default policy is 'None'.  When set to 'Prefix', the value specified in the prefix field will be prepended to the value of the JWT claim. The prefix field must be set when prefixPolicy is 'Prefix'.  When set to 'NoPrefix', no prefix will be prepended to the value of the JWT claim.  When set to 'None', this means no opinion and the platform is left to choose any prefixes that are applied which is subject to change over time. Currently, the platform prepends `{issuerURL}#` to the value of the JWT claim when the claim is not 'email'. As an example, consider the following scenario: `prefix` is unset, `issuerURL` is set to `https://myoidc.tld`, the JWT claims include \"username\":\"userA\" and \"email\":\"userA",
            enum={"NoPrefix": "NoPrefix", "None": "None", "Prefix": "Prefix"},
        )

        validation_rules = cls._args_schema.claim.validation_rules
        validation_rules.Element = AAZObjectArg()

        _element = cls._args_schema.claim.validation_rules.Element
        _element.required_claim = AAZObjectArg(
            options=["required-claim"],
            help="The required claim rule to be applied.",
        )
        _element.type = AAZStrArg(
            options=["type"],
            help="This configures the type of the validation rule. It defaults to \"RequiredClaim\"",
            default="RequiredClaim",
            enum={"RequiredClaim": "RequiredClaim"},
        )

        required_claim = cls._args_schema.claim.validation_rules.Element.required_claim
        required_claim.claim = AAZStrArg(
            options=["claim"],
            help="Claim name for the validation profile claim is a required field that configures the name of the required claim.",
            required=True,
            fmt=AAZStrArgFormat(
                min_length=1,
            ),
        )
        required_claim.required_value = AAZStrArg(
            options=["required-value"],
            help="Required value requiredValue is a required field that configures the value that 'claim' must have when taken from the incoming JWT claims. If the value in the JWT claims does not match, the token will be rejected for authentication.",
            required=True,
            fmt=AAZStrArgFormat(
                min_length=1,
            ),
        )

        clients = cls._args_schema.clients
        clients.Element = AAZObjectArg()

        _element = cls._args_schema.clients.Element
        _element.client_id = AAZStrArg(
            options=["client-id"],
            help="External Auth client id The clientId must appear in the audience field of the TokenIssuerProfile.",
            required=True,
            fmt=AAZStrArgFormat(
                min_length=1,
            ),
        )
        _element.component = AAZObjectArg(
            options=["component"],
            help="External Auth client component",
            required=True,
        )
        _element.extra_scopes = AAZListArg(
            options=["extra-scopes"],
            help="external auth client scopes  This is useful if you have configured claim mappings that requires specific scopes to be requested beyond the standard OIDC scopes. When omitted, no additional scopes are requested.",
        )
        _element.type = AAZStrArg(
            options=["type"],
            help="Determines the OIDC provider client type.",
            required=True,
            enum={"Confidential": "Confidential", "Public": "Public"},
        )

        component = cls._args_schema.clients.Element.component
        component.auth_client_namespace = AAZStrArg(
            options=["auth-client-namespace"],
            help="The namespace of the external Auth client This specifies the namespace in which the platform component being configured to use the identity provider as an authentication mode is running.  It is used in combination with name as a unique identifier.",
            required=True,
            fmt=AAZStrArgFormat(
                max_length=63,
                min_length=1,
            ),
        )
        component.name = AAZStrArg(
            options=["name"],
            help="The name of the external auth client  This specifies the name of the platform component being configured to use the identity provider as an authentication mode. It is used in combination with namespace as a unique identifier.",
            required=True,
            fmt=AAZStrArgFormat(
                max_length=256,
                min_length=1,
            ),
        )

        extra_scopes = cls._args_schema.clients.Element.extra_scopes
        extra_scopes.Element = AAZStrArg()

        issuer = cls._args_schema.issuer
        issuer.audiences = AAZListArg(
            options=["audiences"],
            help="This configures the acceptable audiences the JWT token, issued by the identity provider, must be issued to. At least one of the entries must match the 'aud' claim in the JWT token.  audiences must contain at least one entry and must not exceed ten entries.",
            required=True,
            fmt=AAZListArgFormat(
                max_length=10,
                min_length=1,
            ),
        )
        issuer.ca = AAZStrArg(
            options=["ca"],
            help="The issuer of the token  Certificate bundle to use to validate server certificates for the configured URL. It must be PEM encoded and when not specified, the system trust is used.",
        )
        issuer.url = AAZStrArg(
            options=["url"],
            help="This configures the URL used to issue tokens by the identity provider. The Kubernetes API server determines how authentication tokens should be handled by matching the 'iss' claim in the JWT to the issuerURL of configured identity providers.  issuerURL must use the 'https' scheme.",
            required=True,
        )

        audiences = cls._args_schema.issuer.audiences
        audiences.Element = AAZStrArg()
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.ExternalAuthsCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class ExternalAuthsCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RedHatOpenShift/hcpOpenShiftClusters/{hcpOpenShiftClusterName}/externalAuths/{externalAuthName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "externalAuthName", self.ctx.args.external_auth_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "hcpOpenShiftClusterName", self.ctx.args.hcp_open_shift_cluster_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-12-23-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("properties", AAZObjectType)

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("claim", AAZObjectType, ".claim", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("clients", AAZListType, ".clients")
                properties.set_prop("issuer", AAZObjectType, ".issuer", typ_kwargs={"flags": {"required": True}})

            claim = _builder.get(".properties.claim")
            if claim is not None:
                claim.set_prop("mappings", AAZObjectType, ".mappings", typ_kwargs={"flags": {"required": True}})
                claim.set_prop("validationRules", AAZListType, ".validation_rules")

            mappings = _builder.get(".properties.claim.mappings")
            if mappings is not None:
                mappings.set_prop("groups", AAZObjectType, ".groups")
                mappings.set_prop("username", AAZObjectType, ".username", typ_kwargs={"flags": {"required": True}})

            groups = _builder.get(".properties.claim.mappings.groups")
            if groups is not None:
                groups.set_prop("claim", AAZStrType, ".claim", typ_kwargs={"flags": {"required": True}})
                groups.set_prop("prefix", AAZStrType, ".prefix")

            username = _builder.get(".properties.claim.mappings.username")
            if username is not None:
                username.set_prop("claim", AAZStrType, ".claim", typ_kwargs={"flags": {"required": True}})
                username.set_prop("prefix", AAZStrType, ".prefix")
                username.set_prop("prefixPolicy", AAZStrType, ".prefix_policy")

            validation_rules = _builder.get(".properties.claim.validationRules")
            if validation_rules is not None:
                validation_rules.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.claim.validationRules[]")
            if _elements is not None:
                _elements.set_prop("requiredClaim", AAZObjectType, ".required_claim")
                _elements.set_prop("type", AAZStrType, ".type")

            required_claim = _builder.get(".properties.claim.validationRules[].requiredClaim")
            if required_claim is not None:
                required_claim.set_prop("claim", AAZStrType, ".claim", typ_kwargs={"flags": {"required": True}})
                required_claim.set_prop("requiredValue", AAZStrType, ".required_value", typ_kwargs={"flags": {"required": True}})

            clients = _builder.get(".properties.clients")
            if clients is not None:
                clients.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.clients[]")
            if _elements is not None:
                _elements.set_prop("clientId", AAZStrType, ".client_id", typ_kwargs={"flags": {"required": True}})
                _elements.set_prop("component", AAZObjectType, ".component", typ_kwargs={"flags": {"required": True}})
                _elements.set_prop("extraScopes", AAZListType, ".extra_scopes")
                _elements.set_prop("type", AAZStrType, ".type", typ_kwargs={"flags": {"required": True}})

            component = _builder.get(".properties.clients[].component")
            if component is not None:
                component.set_prop("authClientNamespace", AAZStrType, ".auth_client_namespace", typ_kwargs={"flags": {"required": True}})
                component.set_prop("name", AAZStrType, ".name", typ_kwargs={"flags": {"required": True}})

            extra_scopes = _builder.get(".properties.clients[].extraScopes")
            if extra_scopes is not None:
                extra_scopes.set_elements(AAZStrType, ".")

            issuer = _builder.get(".properties.issuer")
            if issuer is not None:
                issuer.set_prop("audiences", AAZListType, ".audiences", typ_kwargs={"flags": {"required": True}})
                issuer.set_prop("ca", AAZStrType, ".ca")
                issuer.set_prop("url", AAZStrType, ".url", typ_kwargs={"flags": {"required": True}})

            audiences = _builder.get(".properties.issuer.audiences")
            if audiences is not None:
                audiences.set_elements(AAZStrType, ".")

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()

            _schema_on_200_201 = cls._schema_on_200_201
            _schema_on_200_201.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.properties = AAZObjectType()
            _schema_on_200_201.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _schema_on_200_201.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200_201.properties
            properties.claim = AAZObjectType(
                flags={"required": True},
            )
            properties.clients = AAZListType()
            properties.condition = AAZObjectType(
                flags={"read_only": True},
            )
            properties.issuer = AAZObjectType(
                flags={"required": True},
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )

            claim = cls._schema_on_200_201.properties.claim
            claim.mappings = AAZObjectType(
                flags={"required": True},
            )
            claim.validation_rules = AAZListType(
                serialized_name="validationRules",
            )

            mappings = cls._schema_on_200_201.properties.claim.mappings
            mappings.groups = AAZObjectType()
            mappings.username = AAZObjectType(
                flags={"required": True},
            )

            groups = cls._schema_on_200_201.properties.claim.mappings.groups
            groups.claim = AAZStrType(
                flags={"required": True},
            )
            groups.prefix = AAZStrType()

            username = cls._schema_on_200_201.properties.claim.mappings.username
            username.claim = AAZStrType(
                flags={"required": True},
            )
            username.prefix = AAZStrType()
            username.prefix_policy = AAZStrType(
                serialized_name="prefixPolicy",
            )

            validation_rules = cls._schema_on_200_201.properties.claim.validation_rules
            validation_rules.Element = AAZObjectType()

            _element = cls._schema_on_200_201.properties.claim.validation_rules.Element
            _element.required_claim = AAZObjectType(
                serialized_name="requiredClaim",
            )
            _element.type = AAZStrType()

            required_claim = cls._schema_on_200_201.properties.claim.validation_rules.Element.required_claim
            required_claim.claim = AAZStrType(
                flags={"required": True},
            )
            required_claim.required_value = AAZStrType(
                serialized_name="requiredValue",
                flags={"required": True},
            )

            clients = cls._schema_on_200_201.properties.clients
            clients.Element = AAZObjectType()

            _element = cls._schema_on_200_201.properties.clients.Element
            _element.client_id = AAZStrType(
                serialized_name="clientId",
                flags={"required": True},
            )
            _element.component = AAZObjectType(
                flags={"required": True},
            )
            _element.extra_scopes = AAZListType(
                serialized_name="extraScopes",
            )
            _element.type = AAZStrType(
                flags={"required": True},
            )

            component = cls._schema_on_200_201.properties.clients.Element.component
            component.auth_client_namespace = AAZStrType(
                serialized_name="authClientNamespace",
                flags={"required": True},
            )
            component.name = AAZStrType(
                flags={"required": True},
            )

            extra_scopes = cls._schema_on_200_201.properties.clients.Element.extra_scopes
            extra_scopes.Element = AAZStrType()

            condition = cls._schema_on_200_201.properties.condition
            condition.last_transition_time = AAZStrType(
                serialized_name="lastTransitionTime",
                flags={"read_only": True},
            )
            condition.message = AAZStrType(
                flags={"read_only": True},
            )
            condition.reason = AAZStrType(
                flags={"read_only": True},
            )
            condition.status = AAZStrType(
                flags={"read_only": True},
            )
            condition.type = AAZStrType(
                flags={"read_only": True},
            )

            issuer = cls._schema_on_200_201.properties.issuer
            issuer.audiences = AAZListType(
                flags={"required": True},
            )
            issuer.ca = AAZStrType()
            issuer.url = AAZStrType(
                flags={"required": True},
            )

            audiences = cls._schema_on_200_201.properties.issuer.audiences
            audiences.Element = AAZStrType()

            system_data = cls._schema_on_200_201.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
            )

            return cls._schema_on_200_201


class _CreateHelper:
    """Helper class for Create"""


__all__ = ["Create"]
