apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-applier
  name: kube-applier
  namespace: '{{ .Release.Namespace }}'
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-applier
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-applier
        azure.workload.identity/use: "true"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: '{{ if eq (int .Values.deployment.zoneCount) 0 }}kubernetes.azure.com/agentpool{{ else }}topology.kubernetes.io/zone{{ end }}'
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: kube-applier
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: kube-applier
      serviceAccountName: '{{ .Values.serviceAccount.name }}'
      priorityClassName: service-lifecycle-critical
      containers:
      - name: kube-applier
        image: '{{ .Values.deployment.imageName }}'
        args:
        - --management-cluster={{ .Values.managementCluster }}
        - --cosmos-name={{ .Values.cosmosDB.databaseName }}
        - --cosmos-url={{ .Values.cosmosDB.endpoint }}
        - --cosmos-container={{ .Values.cosmosDB.containerName }}
        - --namespace={{ .Release.Namespace }}
        imagePullPolicy: Always
        env:
        - name: AZURE_TOKEN_CREDENTIALS
          value: "WorkloadIdentityCredential"
        ports:
        - name: healthz
          containerPort: 8083
          protocol: TCP
        - name: metrics
          containerPort: 8081
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
{{- if ne .Values.deployment.resources.limits.memory "unlimited" }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
{{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
