apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-applier
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: kube-applier
