apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-applier
    port: metrics
  name: kube-applier-metrics
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: metrics
  selector:
    app: kube-applier
