apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clusterlifecycle-state-metrics-v2
  namespace: '{{ .Release.Namespace }}'
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 60s
    metricRelabelings:
    - action: replace
      replacement: service
      targetLabel: microsoft_metrics_include_label
    port: https
    scheme: https
    scrapeTimeout: 10s
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: clc-app
  selector:
    matchLabels:
      clc-app: clusterlifecycle-state-metrics-v2
