apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    description: Foundational components for central management of multiple OpenShift Container Platform and Kubernetes clusters
    repository: https://github.com/open-cluster-management/backplane-operator
    support: Red Hat
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: backplane-operator
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: backplane-operator
        ocm-antiaffinity-selector: backplane-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_ADDON_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/addon-manager-rhel9@sha256:9f2a7985198a2349848f1646afa27ab703c5571734ddc239680139f62f7a08dc'
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/must-gather-rhel9@sha256:06883dace285f89603e114b3468eaf9155939942f532e67c711aafed1491d5c6'
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:c9be42ea32eae98bb0c2ebeddcec43dbc62b2ff24f2dac4cfb3245e27645f217'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-agent-rhel9@sha256:6685ae0c29d3c958f54c2d7b73c91462ab3de46309ed2a2b04d728a790f39486'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AWS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-aws-rhel9@sha256:242cc482b2b2e96a63c5d46ba51d22a5c2a2b26ca17aea0336edcf27f5d5c6f5'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_KUBEVIRT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-kubevirt-rhel9@sha256:242015bea700eaa3ec8840d3c04a09e98d8d28d3dc8c96801c0027a8aebdd38b'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_BOOTSTRAP
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-bootstrap-rhel9@sha256:dacca2c8f08a1d10d0c18e21e3736e62c84bc8cf8debfbce9e4515b9e26b8ded'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_CONTROL_PLANE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-control-plane-rhel9@sha256:4ae3a152de1067176a07cfb60298b233c2c047c50fd15cd02af5044eff7031a1'
        - name: OPERAND_IMAGE_MCE_CAPI_WEBHOOK_CONFIG_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/mce-capi-webhook-config-rhel9@sha256:f6c509cf40ac600c88307da348535ecbed17669bafb1275e9d0e8bd67a049872'
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterclaims-controller-rhel9@sha256:88011f27487b63c9269c4e42f5c89bd8ddf61536875fda196f75e01d5957c585'
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-curator-controller-rhel9@sha256:73bb742b9ad42814ef050805d64be05e591b1b4b901fcda38f87e605e06589ae'
        - name: OPERAND_IMAGE_CLUSTER_IMAGE_SET_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-image-set-controller-rhel9@sha256:ff66d0d4afb3da813ba1cfca227d6bcdb8a9641100e22fac3a6663d4c27b24ec'
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterlifecycle-state-metrics-rhel9@sha256:32b825c85a4da491f289b97226b93cea1b0e7e62b42bfee59c42e43f9fb2a5de'
        - name: OPERAND_IMAGE_CLUSTER_PROXY_ADDON
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-proxy-addon-rhel9@sha256:65e5f5e23d453d70b0ae91000c123e07a418a58c125f90c9102e82a2fccc8905'
        - name: OPERAND_IMAGE_CLUSTER_PROXY
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-proxy-rhel9@sha256:6c9a9b94d64d2f7459b70a8eb4ae0058705e2807301fc1d53760056c5f5dc039'
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/console-mce-rhel9@sha256:51cb24e66e7c6a33cd05cab535da6263d85880e8b960a6287ca5617ec7f0b7e9'
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/discovery-rhel9@sha256:02d434ff823485cb742b00506c31b3ada44af17183999c817670744c6327a8b0'
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hive-rhel9@sha256:977e181881550a3e6d364b98ec70b1f750a9c9f2cfaf47ffda042dee48d37f04'
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-addon-rhel9-operator@sha256:3ba1bc35cc179d78545efb6da2afa894e6ab8bd6f5001639ee1c98f73c4ccbcf'
        - name: OPERAND_IMAGE_HYPERSHIFT_CLI
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-cli-rhel9@sha256:12c5efc1269f370046df494097d54305ae9b25eeaf9bb7cba2782dc595802ada'
        - name: OPERAND_IMAGE_HYPERSHIFT_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-rhel9-operator@sha256:2046a404da45ec29a9b05f31765e2186e3381ab418afea771cdde4750f44aeec'
        - name: OPERAND_IMAGE_IMAGE_BASED_INSTALL_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/image-based-install-rhel9@sha256:2ee1032bad5c94e067cac39a2f2562d11e86a8f7e6e61401482358eda8235b74'
        - name: OPERAND_IMAGE_KUBE_RBAC_PROXY_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/kube-rbac-proxy-mce-rhel9@sha256:6a1724bacc9d5557a702d805b26c88c37ded0300dfd0e718c7886c0ef57e6491'
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managedcluster-import-controller-rhel9@sha256:e8b92a248899a0d8d55869b35d871070bc45c68d811ff0a98f0eb6e07ab2d8e3'
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managed-serviceaccount-rhel9@sha256:809f6f052c626d64b4498521e9dc8070fd02a011b3573ecee1eb4c3dc454bd6f'
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/multicloud-manager-rhel9@sha256:8d72fefd66e21686185032269b478983e1a95863b2dbbd7df5b4f89f7a3bede1'
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/provider-credential-controller-rhel9@sha256:46edc8d16e1fdb23726147a259f33c7831d3124cd577403990b25a66a5c2e823'
        - name: OPERAND_IMAGE_PLACEMENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/placement-rhel9@sha256:0768a096871824a8a344b6b9bd077318b75cd7921e1715513ac1098043a0698a'
        - name: OPERAND_IMAGE_REGISTRATION
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-rhel9@sha256:d7d6099babf38fbff8d2bad79c517e875167b6a72b9973dfa3a9dbe849b8179e'
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-operator-rhel9@sha256:09d1f15674cc0bea5d2d3a2998648b6920a14f260992e1ba7e7338349ac11bb5'
        - name: OPERAND_IMAGE_WORK
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/work-rhel9@sha256:90865fc9aef0a43370b11027ec23fbada016df7a4ceb192a620ac9e40cf8f8ea'
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-image-service-rhel9@sha256:2c307bb5a3caecf5e4f5e3eb4aff17ce327095e392462fb73915f3c0cec9ae6d'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-rhel9@sha256:911d56c49d4f990cbf56fba870f2fde79d9cee03babcccdb8bd638ae63afc10d'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-agent-rhel9@sha256:6582061fe79a416fe4454e45dcb5db5856cad5ddfe0cfd655cbcf822644c6d32'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-controller-rhel9@sha256:88d91e70277521b15538d787c5cc6fd7ebdad9191634107771a722a230658d0e'
        - name: OPERAND_IMAGE_ASSISTED_SERVICE_9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-service-9-rhel9@sha256:a24238537c7d94e78689aa664610f78e6de02fa02276163fb8ee579230519bb3'
        - name: OPERAND_IMAGE_OSE_CLUSTER_API_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-cluster-api-rhel9@sha256:b573d5ddf848eca57fae686f6ca2297b2424b8431bbcb08d3e2cdb19fe1a146a'
        - name: OPERAND_IMAGE_OSE_BAREMETAL_CLUSTER_API_CONTROLLERS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-baremetal-cluster-api-controllers-rhel9@sha256:5efadf9635250c589b4311512a3a61d5300bd2a33da4b4365aeeebe67b5d08d4'
        - name: OPERAND_IMAGE_POSTGRESQL_12
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/postgresql-12@sha256:1ac3f953c17e69468bee276267d3b5b7f40c849cdbac50d839790ea0c2bfc9f0'
        - name: OPERATOR_VERSION
          value: 2.10.2
        - name: OPERATOR_PACKAGE
          value: multicluster-engine
        image: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:c9be42ea32eae98bb0c2ebeddcec43dbc62b2ff24f2dac4cfb3245e27645f217'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: backplane-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
status: {}
