apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-engine-92lsw4ygrj90991gtruh0w98lza00paesv8kq64cv48
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-engine-92lsw4ygrj90991gtruh0w98lza00paesv8kq64cv48
subjects:
- kind: ServiceAccount
  name: multicluster-engine-operator
  namespace: '{{ .Release.Namespace }}'
