apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    description: Foundational components for central management of multiple OpenShift Container Platform and Kubernetes clusters
    repository: https://github.com/open-cluster-management/backplane-operator
    support: Red Hat
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: backplane-operator
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: backplane-operator
        ocm-antiaffinity-selector: backplane-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_ADDON_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/addon-manager-rhel9@sha256:e59bc039cd66cf80ffb7708c61e8ae80f07430dbb697e1751b4d64af844f4a69'
        - name: OPERAND_IMAGE_AZURE_SERVICE_OPERATOR_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/azure-service-operator-rhel9@sha256:e620272ef0b77ffc408382e66b9da03f146632ede4fde51ccb10b1820c165d98'
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/must-gather-rhel9@sha256:e1980700cf9e11318d40bf4e8b15918fda1c785da26511916ba36faa4e15d225'
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:f8ec92b2ecff7e48be04a758fadcb196135ae6cf1be0b45c9a0d9e55843bcaf2'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-agent-rhel9@sha256:14832ee2fa948f203c702db4f95a437e57059452c29d00e56dc6cf79a457e012'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AWS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-aws-rhel9@sha256:7771817f7e1981bd0c1314f603d17c933845683dc037c82875c3a5f7dab19fa8'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AZURE_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-azure-rhel9@sha256:9db1b63823e29af238229af680cf54ab886576ffc2e61db04a2f912e6fe0a504'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_KUBEVIRT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-kubevirt-rhel9@sha256:a6c92c6837b87de74e3265465e17878404b6bcf4f8f910f0ca188b2f7b1ebed1'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_BOOTSTRAP
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-bootstrap-rhel9@sha256:d2575bfd4913353ad77d564c329b2b6581d134ea7a4515936b33b4d1ab29ed37'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_CONTROL_PLANE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-control-plane-rhel9@sha256:1ea5d8c1644cc1ec1cdce1e65e31073ac5870f45397d96be85e00987ab23277b'
        - name: OPERAND_IMAGE_MCE_CAPI_WEBHOOK_CONFIG_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/mce-capi-webhook-config-rhel9@sha256:af2b97db0b35ccfdc530de16055de96989c1ad420112ff0d7fd557f114821537'
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterclaims-controller-rhel9@sha256:08559f0040711390f2792ffa4cd120122abfa4518b8c35879f374f8360a0eef7'
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-curator-controller-rhel9@sha256:e45d5a86ba5d88c78ab344804a8cbb62cd4ffd8e8e8c97b783db61f3bd41ff31'
        - name: OPERAND_IMAGE_CLUSTER_IMAGE_SET_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-image-set-controller-rhel9@sha256:8755bc5d99954c4b0cd30ac83d5b296e2fb21a189197e11d3c7e9a1e46a45727'
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterlifecycle-state-metrics-rhel9@sha256:5c85c5008d1eb5463efa3582a251b7322fd256b9991970759b8dbabc211d0cbd'
        - name: OPERAND_IMAGE_CLUSTER_PROXY
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-proxy-rhel9@sha256:e717c4f4494397ec7ebd34143ba42104bf5b9388a62c2ed26058bfa89f3be254'
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/console-mce-rhel9@sha256:e2b3fb80b7b5e1dc833318e52094317545d82aa2d09c22f5e5b50d408e3abb22'
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/discovery-rhel9@sha256:3106d788bc5e657f73dec98b46388136bfc1ec786023a7216ae92a0340292616'
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hive-rhel9@sha256:566ef824a077d3734bf731be409c851d7174ef79994617bc02c3b12a66c3fde7'
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-addon-rhel9-operator@sha256:9a825b2f4e73be48f06911ab3683b3be1b7cbfc10395c05ba4f396177ba5cb14'
        - name: OPERAND_IMAGE_HYPERSHIFT_CLI
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-cli-rhel9@sha256:037df1ba6444f829431ca78c94ef0adccc59907afe03f89dc80e140bac24dd43'
        - name: OPERAND_IMAGE_HYPERSHIFT_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-rhel9-operator@sha256:cb9b0e01e4f6faaa25ca0e2e6f32f37dc1b53d92e6ea5bb484db478cd12d0953'
        - name: OPERAND_IMAGE_IMAGE_BASED_INSTALL_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/image-based-install-rhel9@sha256:b22823526cd5b8c3a3b595512ceec8530a6019bc23ce69982b94293edca6a1a6'
        - name: OPERAND_IMAGE_KUBE_RBAC_PROXY_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/kube-rbac-proxy-mce-rhel9@sha256:e59e8254796f3ede6b8290f4273d8e54b02f2f4d382bce90b0eb208c67850fda'
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managedcluster-import-controller-rhel9@sha256:c6755e9d82b615fddc8f140839363918a91bb329b9d950c0d957e3c84c40c982'
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managed-serviceaccount-rhel9@sha256:1eb1f62bdf671c86999f178bf44874f30ad92f53e6122cf50d357363ad97a8ff'
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/multicloud-manager-rhel9@sha256:f4b3afdd1a8aeef673f2caa3ba885b2645ace9ec56fd82c5f0a5647cefb523d2'
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/provider-credential-controller-rhel9@sha256:a1b29070320a27a4e3314c102e80c86447a8af93234f9a782fa21f1c4aede7ec'
        - name: OPERAND_IMAGE_PLACEMENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/placement-rhel9@sha256:56ea0454eb35e297c7640556926143000360ac3e063bbdca8d2e2ae6fca29560'
        - name: OPERAND_IMAGE_REGISTRATION
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-rhel9@sha256:a2a7f3171a5801a750b86f5f797e951f5106941ae1ba14a33a69a531446b33a0'
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-operator-rhel9@sha256:6bbc44d153aeb2be0482b5145b1b0177840b86aa159432529949542858e5b121'
        - name: OPERAND_IMAGE_WORK
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/work-rhel9@sha256:0d00c5cb752883142fe6db759417b9f231c194a83f2e19ba8cbe74a190cbb20a'
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-image-service-rhel9@sha256:48305470fa7e55e78165734d094022a14ac9d083573974036c1f40021c362ba1'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-rhel9@sha256:4dd8f3992fcc23dc8f1e14dbfe4e3c3e447b592d88152fbf5d92ccd469653377'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-agent-rhel9@sha256:72427b669fe6feb4b46bcabf100bbd633ffd13bd0d3583b2e544f5709f680b73'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-controller-rhel9@sha256:b3d2b3c7c5bef17dfea7985eb854a6fe77720dfc185a968adc2db831081546ee'
        - name: OPERAND_IMAGE_ASSISTED_SERVICE_9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-service-9-rhel9@sha256:eb11d23849d00fc2ec07284054335921158f00f6dd7e4347c54fd606e80c8a2e'
        - name: OPERAND_IMAGE_OSE_CLUSTER_API_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-cluster-api-rhel9@sha256:adcade6e58fb77bebd285d6982f2fcda1792571548586c77364e6c791e7d883c'
        - name: OPERAND_IMAGE_OSE_BAREMETAL_CLUSTER_API_CONTROLLERS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-baremetal-cluster-api-controllers-rhel9@sha256:ef51b7c08e8f541c7c5a85e81f711c16ba356556763285a913d5ec0e5ba433bc'
        - name: OPERAND_IMAGE_POSTGRESQL_13
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/postgresql-13@sha256:97b64c18a32944b86fd1a118aa0d1aa04ff1fad8068c3c20f6e94af24712ff36'
        - name: OPERATOR_VERSION
          value: 2.11.4-534
        - name: OPERATOR_PACKAGE
          value: multicluster-engine
        image: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:f8ec92b2ecff7e48be04a758fadcb196135ae6cf1be0b45c9a0d9e55843bcaf2'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: backplane-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      nodeSelector:
        aro-hcp.azure.com/role: infra
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: infra
        operator: Equal
        value: "true"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
status: {}
