$schema: "pipeline.schema.v1"
serviceGroup: Microsoft.Azure.ARO.HCP.Fleet.Registration
rolloutName: Fleet Registration Rollout
resourceGroups:
- name: global
  resourceGroup: '{{ .global.rg }}'
  subscription: '{{ .global.subscription.key }}'
  steps:
  - name: output
    action: ARM
    template: templates/output-global.bicep
    parameters: ../../dev-infrastructure/configurations/output-global.tmpl.bicepparam
    deploymentLevel: ResourceGroup
    outputOnly: true
  - name: mirror-image
    action: ImageMirror
    targetACR:
      configRef: 'acr.svc.name'
    sourceRegistry:
      configRef: fleet.image.registry
    repository:
      configRef: fleet.image.repository
    digest:
      configRef: fleet.image.digest
    pullSecretKeyVault:
      configRef: global.keyVault.name
    pullSecretName:
      configRef: imageSync.ondemandSync.pullSecretName
    shellIdentity:
      input:
        resourceGroup: global
        step: output
        name: globalMSIId
    automatedRetry:
      errorContainsAny:
      - "unknown_storage_failure"
      - "unexpected EOF"
      - "unauthorized: authentication required"
      maximumRetryCount: 5
      durationBetweenRetries: 1m
- name: kusto
  resourceGroup: '{{ .kusto.rg }}'
  subscription: '{{ .global.subscription.key }}'
  steps:
  - name: kusto-lookup
    action: ARM
    template: ../../dev-infrastructure/templates/kusto-lookup.bicep
    parameters: ../../dev-infrastructure/configurations/kusto-lookup.tmpl.bicepparam
    deploymentLevel: ResourceGroup
    outputOnly: true
- name: management
  resourceGroup: '{{ .mgmt.rg }}'
  subscription: '{{ .mgmt.subscription.key }}'
  steps:
  - name: output
    action: ARM
    template: ../../dev-infrastructure/templates/output-mgmt.bicep
    parameters: ../../dev-infrastructure/configurations/output-mgmt.tmpl.bicepparam
    deploymentLevel: ResourceGroup
    outputOnly: true
  - name: infra-lookup
    action: ARM
    template: ../../dev-infrastructure/templates/mgmt-infra-lookup.bicep
    parameters: ../../dev-infrastructure/configurations/mgmt-infra-lookup.tmpl.bicepparam
    deploymentLevel: ResourceGroup
    outputOnly: true
- name: service
  resourceGroup: '{{ .svc.rg }}'
  subscription: '{{ .svc.subscription.key }}'
  steps:
  - name: fleet-lookup
    action: ARM
    template: ../../dev-infrastructure/modules/fleet/fleet-lookup.bicep
    parameters: ../../dev-infrastructure/configurations/fleet-lookup.tmpl.bicepparam
    deploymentLevel: ResourceGroup
    outputOnly: true
  - name: deploy
    aksCluster: '{{ .svc.aks.name }}'
    action: Helm
    releaseName: 'fleet-reg-{{ .mgmt.aks.name }}'
    releaseNamespace: '{{ .fleet.k8s.namespace }}'
    chartDir: ./deploy
    valuesFile: ./values.yaml
    kustoEndpoint:
      resourceGroup: kusto
      step: kusto-lookup
      name: kustoUri
    kustoDatabase: '{{ .kusto.serviceLogsDatabase }}'
    kustoTable: 'fleetLogs'
    inputVariables:
      cosmosUrl:
        resourceGroup: service
        step: fleet-lookup
        name: cosmosDBDocumentEndpoint
      aksResourceID:
        resourceGroup: management
        step: output
        name: azureAksManagementClusterResourceId
      cxKeyVaultUrl:
        resourceGroup: management
        step: infra-lookup
        name: cxKeyVaultUrl
      msiKeyVaultUrl:
        resourceGroup: management
        step: infra-lookup
        name: msiKeyVaultUrl
      cxDnsZoneResourceId:
        resourceGroup: service
        step: fleet-lookup
        name: cxDnsZoneResourceId
      hostedClustersSecretsKvMiClientId:
        resourceGroup: management
        step: output
        name: azureKeyvaultSecretsProviderIdentityClientId
    dependsOn:
    - resourceGroup: global
      step: mirror-image
    externalDependsOn:
    - serviceGroup: Microsoft.Azure.ARO.HCP.Fleet
      resourceGroup: service
      step: deploy
    identityFrom:
      resourceGroup: global
      step: output
      name: globalMSIId
    automatedRetry:
      errorContainsAny:
      - "500 Internal Server Error"
      - "Internal error occurred"
      maximumRetryCount: 3
      durationBetweenRetries: 1m
