image:
  registry: '{{ .acr.svc.name }}.azurecr.io'
  repository: '{{ .fleet.image.repository }}'
  digest: '{{ .fleet.image.digest }}'
serviceAccountName: '{{ .fleet.k8s.serviceAccountName }}'
cloudEnvironmentName: '{{ .cloudEnvironmentName }}'
cosmos:
  url: "__cosmosUrl__"
  name: '{{ .frontend.cosmosDB.name }}'
registration:
  stampIdentifier: '{{ .fleet.registration.stampIdentifier }}'
  autoApprove: {{ .fleet.registration.autoApproveStamps }}
  provisionShardStatus: '{{ .clustersService.provisionShardStatus }}'
  aksResourceID: "__aksResourceID__"
  publicDNSZoneResourceID: "__cxDnsZoneResourceId__"
  hostedClustersSecretsKeyVaultURL: "__cxKeyVaultUrl__"
  hostedClustersManagedIdentitiesKeyVaultURL: "__msiKeyVaultUrl__"
  maestroConsumerName: '{{ .maestro.agent.consumerName }}'
  hostedClustersSecretsKeyVaultManagedIdentityClientID: "__hostedClustersSecretsKvMiClientId__"
  maestroRESTAPIURL: "http://maestro.maestro.svc.cluster.local:8000"
  maestroGRPCTarget: "maestro-grpc.maestro.svc.cluster.local:8090"
  kubeApplierCosmosContainerName: '{{ .kubeApplier.cosmosContainerName }}'
