---
# Source: fleet-registration/templates/registration.job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: dev-westus3-svc-1-fleet-reg-dev-westus3-mgmt-1
  namespace: 'fleet'
  labels:
    app: fleet-registration
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: fleet-registration
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: 'fleet'
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fleet-registration
        image: 'arohcpsvcdev.azurecr.io/fleet@sha256:1234567890'
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        env:
        - name: AZURE_TOKEN_CREDENTIALS
          value: "WorkloadIdentityCredential"
        args:
        - register
        - --cloud-environment
        - 'AzurePublicCloud'
        - --cosmos-url
        - '__cosmosUrl__'
        - --cosmos-name
        - 'arohcpdev-rp-usw3'
        - --stamp-identifier
        - '1'
        - --auto-approve
        - --scheduling-policy
        - 'Schedulable'
        - --aks-resource-id
        - '__aksResourceID__'
        - --public-dns-zone-resource-id
        - '__cxDnsZoneResourceId__'
        - --hosted-clusters-secrets-keyvault-url
        - '__cxKeyVaultUrl__'
        - --hosted-clusters-managed-identities-keyvault-url
        - '__msiKeyVaultUrl__'
        - --maestro-consumer-name
        - 'hcp-underlay-usw3-mgmt-1'
        - --hosted-clusters-secrets-keyvault-mi-client-id
        - '__hostedClustersSecretsKvMiClientId__'
        - --maestro-rest-api-url
        - 'http://maestro.maestro.svc.cluster.local:8000'
        - --maestro-grpc-target
        - 'maestro-grpc.maestro.svc.cluster.local:8090'
        - --kube-applier-cosmos-container-name
        - 'Manifests-MC-1'

