namespace: acrpull
image: "{{ .acrPull.image.registry }}/{{ .acrPull.image.repository }}@{{ .acrPull.image.digest }}"
ttlRotationFraction: 0.5
replicas: 2
strategy:
  rollingUpdate:
    maxSurge: "{{ .acrPull.k8s.deploymentStrategy.rollingUpdate.maxSurge }}"
    maxUnavailable: "{{ .acrPull.k8s.deploymentStrategy.rollingUpdate.maxUnavailable }}"
resources:
  requests:
    memory: "{{ .acrPull.k8s.resources.requests.memory }}"
