cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('frontendLogs')
| where timestamp between ({{ kqlDatetime .FullStartTime }} .. {{ kqlDatetime .FullEndTime }})
{{- if and .ServiceClusterName .ManagementClusterName }}
| where cluster in ('{{ .ServiceClusterName }}', '{{ .ManagementClusterName }}')
{{- end }}
| where log.correlation_request_id == '{{ .CorrelationID }}'
| where log.msg == 'response complete'
| distinct client_request_id = tostring(log.client_request_id)
