# Keep this version in sync with .bingo/golangci-lint.mod
version: v2.5.0
name: custom-golangci-lint
destination: ./bin
plugins:
- module: 'github.com/Azure/ARO-HCP/tooling/customlinters'
  import: 'github.com/Azure/ARO-HCP/tooling/customlinters'
  path: .
