//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package api

import (
	azcorearm "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	runtime "k8s.io/apimachinery/pkg/runtime"

	arm "github.com/Azure/ARO-HCP/internal/api/arm"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAutoscalingProfile) DeepCopyInto(out *ClusterAutoscalingProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAutoscalingProfile.
func (in *ClusterAutoscalingProfile) DeepCopy() *ClusterAutoscalingProfile {
	if in == nil {
		return nil
	}
	out := new(ClusterAutoscalingProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterImageRegistryProfile) DeepCopyInto(out *ClusterImageRegistryProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterImageRegistryProfile.
func (in *ClusterImageRegistryProfile) DeepCopy() *ClusterImageRegistryProfile {
	if in == nil {
		return nil
	}
	out := new(ClusterImageRegistryProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	out.LastTransitionTime = in.LastTransitionTime
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Controller) DeepCopyInto(out *Controller) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Controller.
func (in *Controller) DeepCopy() *Controller {
	if in == nil {
		return nil
	}
	out := new(Controller)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerStatus) DeepCopyInto(out *ControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerStatus.
func (in *ControllerStatus) DeepCopy() *ControllerStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerAPIProfile) DeepCopyInto(out *CustomerAPIProfile) {
	*out = *in
	if in.AuthorizedCIDRs != nil {
		in, out := &in.AuthorizedCIDRs, &out.AuthorizedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerAPIProfile.
func (in *CustomerAPIProfile) DeepCopy() *CustomerAPIProfile {
	if in == nil {
		return nil
	}
	out := new(CustomerAPIProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerDNSProfile) DeepCopyInto(out *CustomerDNSProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerDNSProfile.
func (in *CustomerDNSProfile) DeepCopy() *CustomerDNSProfile {
	if in == nil {
		return nil
	}
	out := new(CustomerDNSProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerManagedEncryptionProfile) DeepCopyInto(out *CustomerManagedEncryptionProfile) {
	*out = *in
	if in.Kms != nil {
		in, out := &in.Kms, &out.Kms
		*out = new(KmsEncryptionProfile)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerManagedEncryptionProfile.
func (in *CustomerManagedEncryptionProfile) DeepCopy() *CustomerManagedEncryptionProfile {
	if in == nil {
		return nil
	}
	out := new(CustomerManagedEncryptionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerPlatformProfile) DeepCopyInto(out *CustomerPlatformProfile) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	if in.NetworkSecurityGroupID != nil {
		in, out := &in.NetworkSecurityGroupID, &out.NetworkSecurityGroupID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	in.OperatorsAuthentication.DeepCopyInto(&out.OperatorsAuthentication)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerPlatformProfile.
func (in *CustomerPlatformProfile) DeepCopy() *CustomerPlatformProfile {
	if in == nil {
		return nil
	}
	out := new(CustomerPlatformProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdDataEncryptionProfile) DeepCopyInto(out *EtcdDataEncryptionProfile) {
	*out = *in
	if in.CustomerManaged != nil {
		in, out := &in.CustomerManaged, &out.CustomerManaged
		*out = new(CustomerManagedEncryptionProfile)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdDataEncryptionProfile.
func (in *EtcdDataEncryptionProfile) DeepCopy() *EtcdDataEncryptionProfile {
	if in == nil {
		return nil
	}
	out := new(EtcdDataEncryptionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdProfile) DeepCopyInto(out *EtcdProfile) {
	*out = *in
	in.DataEncryption.DeepCopyInto(&out.DataEncryption)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdProfile.
func (in *EtcdProfile) DeepCopy() *EtcdProfile {
	if in == nil {
		return nil
	}
	out := new(EtcdProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthClaimProfile) DeepCopyInto(out *ExternalAuthClaimProfile) {
	*out = *in
	in.Mappings.DeepCopyInto(&out.Mappings)
	if in.ValidationRules != nil {
		in, out := &in.ValidationRules, &out.ValidationRules
		*out = make([]TokenClaimValidationRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthClaimProfile.
func (in *ExternalAuthClaimProfile) DeepCopy() *ExternalAuthClaimProfile {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthClaimProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthClientComponentProfile) DeepCopyInto(out *ExternalAuthClientComponentProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthClientComponentProfile.
func (in *ExternalAuthClientComponentProfile) DeepCopy() *ExternalAuthClientComponentProfile {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthClientComponentProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthClientProfile) DeepCopyInto(out *ExternalAuthClientProfile) {
	*out = *in
	out.Component = in.Component
	if in.ExtraScopes != nil {
		in, out := &in.ExtraScopes, &out.ExtraScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthClientProfile.
func (in *ExternalAuthClientProfile) DeepCopy() *ExternalAuthClientProfile {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthClientProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthCondition) DeepCopyInto(out *ExternalAuthCondition) {
	*out = *in
	out.LastTransitionTime = in.LastTransitionTime
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthCondition.
func (in *ExternalAuthCondition) DeepCopy() *ExternalAuthCondition {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupClaimProfile) DeepCopyInto(out *GroupClaimProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupClaimProfile.
func (in *GroupClaimProfile) DeepCopy() *GroupClaimProfile {
	if in == nil {
		return nil
	}
	out := new(GroupClaimProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftCluster) DeepCopyInto(out *HCPOpenShiftCluster) {
	*out = *in
	in.TrackedResource.DeepCopyInto(&out.TrackedResource)
	in.CustomerProperties.DeepCopyInto(&out.CustomerProperties)
	out.ServiceProviderProperties = in.ServiceProviderProperties
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(arm.ManagedServiceIdentity)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftCluster.
func (in *HCPOpenShiftCluster) DeepCopy() *HCPOpenShiftCluster {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCPOpenShiftCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterAdminCredential) DeepCopyInto(out *HCPOpenShiftClusterAdminCredential) {
	*out = *in
	out.ExpirationTimestamp = in.ExpirationTimestamp
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterAdminCredential.
func (in *HCPOpenShiftClusterAdminCredential) DeepCopy() *HCPOpenShiftClusterAdminCredential {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterAdminCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterCustomerProperties) DeepCopyInto(out *HCPOpenShiftClusterCustomerProperties) {
	*out = *in
	out.Version = in.Version
	out.DNS = in.DNS
	out.Network = in.Network
	in.API.DeepCopyInto(&out.API)
	in.Platform.DeepCopyInto(&out.Platform)
	out.Autoscaling = in.Autoscaling
	in.Etcd.DeepCopyInto(&out.Etcd)
	out.ClusterImageRegistry = in.ClusterImageRegistry
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterCustomerProperties.
func (in *HCPOpenShiftClusterCustomerProperties) DeepCopy() *HCPOpenShiftClusterCustomerProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterCustomerProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterExternalAuth) DeepCopyInto(out *HCPOpenShiftClusterExternalAuth) {
	*out = *in
	in.ProxyResource.DeepCopyInto(&out.ProxyResource)
	in.Properties.DeepCopyInto(&out.Properties)
	out.ServiceProviderProperties = in.ServiceProviderProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterExternalAuth.
func (in *HCPOpenShiftClusterExternalAuth) DeepCopy() *HCPOpenShiftClusterExternalAuth {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterExternalAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterExternalAuthProperties) DeepCopyInto(out *HCPOpenShiftClusterExternalAuthProperties) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	in.Issuer.DeepCopyInto(&out.Issuer)
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]ExternalAuthClientProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Claim.DeepCopyInto(&out.Claim)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterExternalAuthProperties.
func (in *HCPOpenShiftClusterExternalAuthProperties) DeepCopy() *HCPOpenShiftClusterExternalAuthProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterExternalAuthProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterExternalAuthServiceProviderProperties) DeepCopyInto(out *HCPOpenShiftClusterExternalAuthServiceProviderProperties) {
	*out = *in
	out.ClusterServiceID = in.ClusterServiceID
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterExternalAuthServiceProviderProperties.
func (in *HCPOpenShiftClusterExternalAuthServiceProviderProperties) DeepCopy() *HCPOpenShiftClusterExternalAuthServiceProviderProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterExternalAuthServiceProviderProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterNodePool) DeepCopyInto(out *HCPOpenShiftClusterNodePool) {
	*out = *in
	in.TrackedResource.DeepCopyInto(&out.TrackedResource)
	in.Properties.DeepCopyInto(&out.Properties)
	out.ServiceProviderProperties = in.ServiceProviderProperties
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(arm.ManagedServiceIdentity)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterNodePool.
func (in *HCPOpenShiftClusterNodePool) DeepCopy() *HCPOpenShiftClusterNodePool {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCPOpenShiftClusterNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterNodePoolProperties) DeepCopyInto(out *HCPOpenShiftClusterNodePoolProperties) {
	*out = *in
	out.Version = in.Version
	in.Platform.DeepCopyInto(&out.Platform)
	if in.AutoScaling != nil {
		in, out := &in.AutoScaling, &out.AutoScaling
		*out = new(NodePoolAutoScaling)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]Taint, len(*in))
		copy(*out, *in)
	}
	if in.NodeDrainTimeoutMinutes != nil {
		in, out := &in.NodeDrainTimeoutMinutes, &out.NodeDrainTimeoutMinutes
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterNodePoolProperties.
func (in *HCPOpenShiftClusterNodePoolProperties) DeepCopy() *HCPOpenShiftClusterNodePoolProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterNodePoolProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterNodePoolServiceProviderProperties) DeepCopyInto(out *HCPOpenShiftClusterNodePoolServiceProviderProperties) {
	*out = *in
	out.ClusterServiceID = in.ClusterServiceID
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterNodePoolServiceProviderProperties.
func (in *HCPOpenShiftClusterNodePoolServiceProviderProperties) DeepCopy() *HCPOpenShiftClusterNodePoolServiceProviderProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterNodePoolServiceProviderProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftClusterServiceProviderProperties) DeepCopyInto(out *HCPOpenShiftClusterServiceProviderProperties) {
	*out = *in
	out.ClusterServiceID = in.ClusterServiceID
	out.DNS = in.DNS
	out.Console = in.Console
	out.API = in.API
	out.Platform = in.Platform
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftClusterServiceProviderProperties.
func (in *HCPOpenShiftClusterServiceProviderProperties) DeepCopy() *HCPOpenShiftClusterServiceProviderProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftClusterServiceProviderProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftVersion) DeepCopyInto(out *HCPOpenShiftVersion) {
	*out = *in
	in.ProxyResource.DeepCopyInto(&out.ProxyResource)
	in.Properties.DeepCopyInto(&out.Properties)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftVersion.
func (in *HCPOpenShiftVersion) DeepCopy() *HCPOpenShiftVersion {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPOpenShiftVersionProperties) DeepCopyInto(out *HCPOpenShiftVersionProperties) {
	*out = *in
	out.EndOfLifeTimestamp = in.EndOfLifeTimestamp
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPOpenShiftVersionProperties.
func (in *HCPOpenShiftVersionProperties) DeepCopy() *HCPOpenShiftVersionProperties {
	if in == nil {
		return nil
	}
	out := new(HCPOpenShiftVersionProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalID) DeepCopyInto(out *InternalID) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalID.
func (in *InternalID) DeepCopy() *InternalID {
	if in == nil {
		return nil
	}
	out := new(InternalID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalTestResource) DeepCopyInto(out *InternalTestResource) {
	*out = *in
	in.TrackedResource.DeepCopyInto(&out.TrackedResource)
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(arm.ManagedServiceIdentity)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalTestResource.
func (in *InternalTestResource) DeepCopy() *InternalTestResource {
	if in == nil {
		return nil
	}
	out := new(InternalTestResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmsEncryptionProfile) DeepCopyInto(out *KmsEncryptionProfile) {
	*out = *in
	out.ActiveKey = in.ActiveKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmsEncryptionProfile.
func (in *KmsEncryptionProfile) DeepCopy() *KmsEncryptionProfile {
	if in == nil {
		return nil
	}
	out := new(KmsEncryptionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmsKey) DeepCopyInto(out *KmsKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmsKey.
func (in *KmsKey) DeepCopy() *KmsKey {
	if in == nil {
		return nil
	}
	out := new(KmsKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProfile) DeepCopyInto(out *NetworkProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProfile.
func (in *NetworkProfile) DeepCopy() *NetworkProfile {
	if in == nil {
		return nil
	}
	out := new(NetworkProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolAutoScaling) DeepCopyInto(out *NodePoolAutoScaling) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolAutoScaling.
func (in *NodePoolAutoScaling) DeepCopy() *NodePoolAutoScaling {
	if in == nil {
		return nil
	}
	out := new(NodePoolAutoScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolPlatformProfile) DeepCopyInto(out *NodePoolPlatformProfile) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	in.OSDisk.DeepCopyInto(&out.OSDisk)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolPlatformProfile.
func (in *NodePoolPlatformProfile) DeepCopy() *NodePoolPlatformProfile {
	if in == nil {
		return nil
	}
	out := new(NodePoolPlatformProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolVersionProfile) DeepCopyInto(out *NodePoolVersionProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolVersionProfile.
func (in *NodePoolVersionProfile) DeepCopy() *NodePoolVersionProfile {
	if in == nil {
		return nil
	}
	out := new(NodePoolVersionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSDiskProfile) DeepCopyInto(out *OSDiskProfile) {
	*out = *in
	if in.SizeGiB != nil {
		in, out := &in.SizeGiB, &out.SizeGiB
		*out = new(int32)
		**out = **in
	}
	if in.EncryptionSetID != nil {
		in, out := &in.EncryptionSetID, &out.EncryptionSetID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSDiskProfile.
func (in *OSDiskProfile) DeepCopy() *OSDiskProfile {
	if in == nil {
		return nil
	}
	out := new(OSDiskProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operation) DeepCopyInto(out *Operation) {
	*out = *in
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	out.InternalID = in.InternalID
	if in.OperationID != nil {
		in, out := &in.OperationID, &out.OperationID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	out.StartTime = in.StartTime
	out.LastTransitionTime = in.LastTransitionTime
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(arm.CloudErrorBody)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operation.
func (in *Operation) DeepCopy() *Operation {
	if in == nil {
		return nil
	}
	out := new(Operation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Operation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorsAuthenticationProfile) DeepCopyInto(out *OperatorsAuthenticationProfile) {
	*out = *in
	in.UserAssignedIdentities.DeepCopyInto(&out.UserAssignedIdentities)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorsAuthenticationProfile.
func (in *OperatorsAuthenticationProfile) DeepCopy() *OperatorsAuthenticationProfile {
	if in == nil {
		return nil
	}
	out := new(OperatorsAuthenticationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProviderAPIProfile) DeepCopyInto(out *ServiceProviderAPIProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProviderAPIProfile.
func (in *ServiceProviderAPIProfile) DeepCopy() *ServiceProviderAPIProfile {
	if in == nil {
		return nil
	}
	out := new(ServiceProviderAPIProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProviderCluster) DeepCopyInto(out *ServiceProviderCluster) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	out.ResourceID = in.ResourceID
	if in.LoadBalancerResourceID != nil {
		in, out := &in.LoadBalancerResourceID, &out.LoadBalancerResourceID
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	if in.Validations != nil {
		in, out := &in.Validations, &out.Validations
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProviderCluster.
func (in *ServiceProviderCluster) DeepCopy() *ServiceProviderCluster {
	if in == nil {
		return nil
	}
	out := new(ServiceProviderCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProviderConsoleProfile) DeepCopyInto(out *ServiceProviderConsoleProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProviderConsoleProfile.
func (in *ServiceProviderConsoleProfile) DeepCopy() *ServiceProviderConsoleProfile {
	if in == nil {
		return nil
	}
	out := new(ServiceProviderConsoleProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProviderDNSProfile) DeepCopyInto(out *ServiceProviderDNSProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProviderDNSProfile.
func (in *ServiceProviderDNSProfile) DeepCopy() *ServiceProviderDNSProfile {
	if in == nil {
		return nil
	}
	out := new(ServiceProviderDNSProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProviderPlatformProfile) DeepCopyInto(out *ServiceProviderPlatformProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProviderPlatformProfile.
func (in *ServiceProviderPlatformProfile) DeepCopy() *ServiceProviderPlatformProfile {
	if in == nil {
		return nil
	}
	out := new(ServiceProviderPlatformProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Taint) DeepCopyInto(out *Taint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Taint.
func (in *Taint) DeepCopy() *Taint {
	if in == nil {
		return nil
	}
	out := new(Taint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenClaimMappingsProfile) DeepCopyInto(out *TokenClaimMappingsProfile) {
	*out = *in
	out.Username = in.Username
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = new(GroupClaimProfile)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenClaimMappingsProfile.
func (in *TokenClaimMappingsProfile) DeepCopy() *TokenClaimMappingsProfile {
	if in == nil {
		return nil
	}
	out := new(TokenClaimMappingsProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenClaimValidationRule) DeepCopyInto(out *TokenClaimValidationRule) {
	*out = *in
	out.RequiredClaim = in.RequiredClaim
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenClaimValidationRule.
func (in *TokenClaimValidationRule) DeepCopy() *TokenClaimValidationRule {
	if in == nil {
		return nil
	}
	out := new(TokenClaimValidationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenIssuerProfile) DeepCopyInto(out *TokenIssuerProfile) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenIssuerProfile.
func (in *TokenIssuerProfile) DeepCopy() *TokenIssuerProfile {
	if in == nil {
		return nil
	}
	out := new(TokenIssuerProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenRequiredClaim) DeepCopyInto(out *TokenRequiredClaim) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenRequiredClaim.
func (in *TokenRequiredClaim) DeepCopy() *TokenRequiredClaim {
	if in == nil {
		return nil
	}
	out := new(TokenRequiredClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAssignedIdentitiesProfile) DeepCopyInto(out *UserAssignedIdentitiesProfile) {
	*out = *in
	if in.ControlPlaneOperators != nil {
		in, out := &in.ControlPlaneOperators, &out.ControlPlaneOperators
		*out = make(map[string]*azcorearm.ResourceID, len(*in))
		for key, val := range *in {
			var outVal *azcorearm.ResourceID
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(azcorearm.ResourceID)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DataPlaneOperators != nil {
		in, out := &in.DataPlaneOperators, &out.DataPlaneOperators
		*out = make(map[string]*azcorearm.ResourceID, len(*in))
		for key, val := range *in {
			var outVal *azcorearm.ResourceID
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(azcorearm.ResourceID)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ServiceManagedIdentity != nil {
		in, out := &in.ServiceManagedIdentity, &out.ServiceManagedIdentity
		*out = new(azcorearm.ResourceID)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAssignedIdentitiesProfile.
func (in *UserAssignedIdentitiesProfile) DeepCopy() *UserAssignedIdentitiesProfile {
	if in == nil {
		return nil
	}
	out := new(UserAssignedIdentitiesProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsernameClaimProfile) DeepCopyInto(out *UsernameClaimProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsernameClaimProfile.
func (in *UsernameClaimProfile) DeepCopy() *UsernameClaimProfile {
	if in == nil {
		return nil
	}
	out := new(UsernameClaimProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionProfile) DeepCopyInto(out *VersionProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionProfile.
func (in *VersionProfile) DeepCopy() *VersionProfile {
	if in == nil {
		return nil
	}
	out := new(VersionProfile)
	in.DeepCopyInto(out)
	return out
}
