# yamllint disable rule:line-length rule:syntax
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: namespace-resourceid-mapping
  namespace: '{{ .Release.Namespace }}'
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: namespace-resourceid-mapping
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: namespace-resourceid-mapping
