apiVersion: v1
kind: Service
metadata:
  name: aro-hcp-admin-api-metrics
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: admin-api-metrics
spec:
  selector:
    app: admin-api
  ports:
  - port: 8444
    protocol: TCP
    targetPort: 8444
    name: metrics
