apiVersion: {{ .Values.monitoringApiGroup }}/v1
kind: ServiceMonitor
metadata:
  name: aro-hcp-admin-api
  namespace: '{{ .Release.Namespace }}'
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
    metricRelabelings:
    - action: replace
      replacement: service
      targetLabel: microsoft_metrics_include_label
  namespaceSelector:
    matchNames:
    - '{{ .Release.Namespace }}'
  selector:
    matchLabels:
      app: admin-api-metrics
