apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admin-api
  namespace: '{{ .Release.Namespace }}'
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: admin-api
