apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: aro-hcp-admin-api-metrics
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    matchLabels:
      app: admin-api
  portLevelMtls:
    8444:
      mode: PERMISSIVE
