apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-admin-api-to-frontend
  namespace: '{{ .Values.sessiongate.namespace }}'
spec:
  action: "ALLOW"
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/{{ .Values.namespace }}/sa/{{ .Values.serviceAccount.name }}"
    to:
    - operation:
        ports:
        - "{{ .Values.sessiongate.servicePort }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: "sessiongate"
      component: "session-ingress"
