{{- if and .Values.holmes .Values.holmes.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: holmes-aoai
  namespace: '{{ .Release.Namespace }}'
spec:
  parameters:
    clientID: '{{ .Values.serviceAccount.workloadIdentityClientId }}'
    cloudName: '{{ .Values.azure.cloudEnvironmentName }}'
    keyvaultName: '{{ .Values.serviceKeyVault.name }}'
    objects: |-
      array:
        - |
          objectName: holmes-azure-api-base
          objectType: secret
          objectAlias: azure-api-base
    tenantId: '{{ .Values.azure.tenantId }}'
    usePodIdentity: "false"
  provider: azure
{{- end }}
