apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-api-sessiongate
  namespace: '{{ .Values.sessiongate.namespace }}'
rules:
- apiGroups:
  - sessiongate.aro-hcp.azure.com
  resources:
  - sessions
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - sessiongate.aro-hcp.azure.com
  resources:
  - sessions/status
  verbs:
  - get
  - list
  - watch
