.create-or-alter table backendContainerLogs ingestion json mapping 'ingestionMapping'
```
[
   {"column":"log", "DataType":"dynamic", "Properties":{"path":"$.log.log"}},
   {"column":"timestamp", "DataType":"datetime", "Properties":{"path":"$.timestamp"}},
   {"column":"tag", "DataType":"string", "Properties":{"path":"$.tag"}},
   {"column":"region", "DataType":"string", "Properties":{"path":"$.log.region"}},
   {"column":"cluster", "DataType":"string", "Properties":{"path":"$.log.cluster"}},
   {"column":"namespace", "DataType":"string", "Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"containerName", "Properties": {"path": "$log.kubernetes.container_name"}},
   {"column":"containerImage", "DataType":"string", "Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"host", "DataType":"string", "Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"labels", "DataType":"string", "Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName", "DataType":"string", "Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"environment", "DataType":"string", "Properties":{"path":"$.log.environment"}},
   {"column":"level", "DataType":"string", "Properties":{"path":"$.level"}},
   {"column":"operation", "DataType":"string", "Properties":{"path":"$.log.operation"}},
   {"column":"operationId", "DataType":"string", "Properties":{"path":"$.log.operation_id"}},
   {"column":"resourceId", "DataType":"string", "Properties":{"path":"$.log.resource_id"}},
   {"column":"internalId", "DataType":"string", "Properties":{"path":"$.log.internal_id"}},
   {"column":"clusterId", "DataType":"string", "Properties":{"path":"$.log.cluster_id"}},
   {"column":"clientRequestId", "DataType":"string", "Properties":{"path":"$.log.client_request_id"}},
   {"column":"correlationRequestId", "DataType":"string", "Properties":{"path":"$.log.correlation_request_id"}},
   {"column":"cloudErrorCode", "DataType":"string", "Properties":{"path":"$.log.cloud_error_code"}},
   {"column":"cloudErrorMessage", "DataType":"string", "Properties":{"path":"$.log.cloud_error_message"}},
   {"column":"subscriptionId", "DataType":"string", "Properties":{"path":"$.log.subscription_id"}},
   {"column":"unmatched", "DataType":"dynamic", "Properties":{"path":"$", "Transform":"DropMappedFields" }}
]
```
