.create-merge table containerLogs (
  timestamp: datetime,
  log: dynamic,
  environment: string,
  cluster: string,
  namespace_name: string,
  container_name: string,
  container_image: string,
  host: string,
  labels: string,
  pod_name: string,
  region: string,
  tag: string
)

.create-or-alter table containerLogs ingestion json mapping 'ingestionMapping'
```
[
  {"column":"timestamp","Properties":{"path":"$.timestamp"}},
  {"column":"log","Properties":{"path":"$.log.log"}},
  {"column":"environment","Properties":{"path":"$.log.environment"}},
  {"column":"region","Properties":{"path":"$.log.region"}},
  {"column":"cluster","Properties":{"path":"$.log.cluster"}},
  {"column":"host","Properties":{"path":"$.log.kubernetes.host"}},
  {"column":"container_name", "Properties": {"path": "$log.kubernetes.container_name"}},
  {"column":"container_image","Properties":{"path":"$.log.kubernetes.container_image"}},
  {"column":"namespace_name","Properties":{"path":"$.log.kubernetes.namespace_name"}},
  {"column":"labels","Properties":{"path":"$.log.kubernetes.labels"}},
  {"column":"pod_name","Properties":{"path":"$.log.kubernetes.pod_name"}},
  {"column":"tag","Properties":{"path":"$.tag"}}
]
```
