.create-or-alter table kubernetesEvents ingestion json mapping 'ingestionMapping'
```
[
   {"column":"log", "DataType":"dynamic", "Properties":{"path":"$.log.log"}},
   {"column":"timestamp","DataType":"datetime", "Properties":{"path":"$.timestamp"}},
   {"column":"tag","DataType":"string", "Properties":{"path":"$.tag"}},
   {"column":"region","DataType":"string", "Properties":{"path":"$.log.region"}},
   {"column":"cluster","DataType":"string", "Properties":{"path":"$.log.cluster"}},
   {"column":"namespace","DataType":"string", "Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"containerName", "DataType":"string", "Properties": {"path": "$log.kubernetes.container_name"}},
   {"column":"containerImage","DataType":"string", "Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"host","DataType":"string", "Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"labels","DataType":"string", "Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName","DataType":"string", "Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"environment","DataType":"string", "Properties":{"path":"$.log.environment"}},
   {"column":"count","DataType":"int", "Properties":{"path":"$.log.count"}},
   {"column":"kubeEventType","DataType":"string", "Properties":{"path":"$.log.kubeEventType"}},
   {"column":"firstSeen","DataType":"datetime", "Properties":{"path":"$.log.first_timestamp"}},
   {"column":"lastSeen","DataType":"datetime", "Properties":{"path":"$.log.last_timestamp"}},
   {"column":"message","DataType":"string", "Properties":{"path":"$.log.message"}},
   {"column":"eventNamespace", "DataType":"string", "Properties":{"path":"$.log.involved_object.namespace"}},
   {"column":"objectKind","DataType":"string", "Properties":{"path":"$.log.involved_object.kind"}},
   {"column":"objectName","DataType":"string", "Properties":{"path":"$.log.involved_object.name"}},
   {"column":"objectApiVersion","DataType":"string", "Properties":{"path":"$.log.involved_object.api_version"}},
   {"column":"objectUID","DataType":"string", "Properties":{"path":"$.log.involved_object.uid"}},
   {"column":"reason","DataType":"string", "Properties":{"path":"$.log.reason"}},
   {"column":"sourceComponent","DataType":"string", "Properties":{"path":"$.log.source.component"}},
   {"column":"unmatched","DataType":"dynamic", "Properties":{"path":"$", "Transform":"DropMappedFields" }}
]
```
