$schema: "pipeline.schema.v1"
serviceGroup: Microsoft.Azure.ARO.HCP.DevCI.CIHealth
rolloutName: CIHealth Rollout
resourceGroups:
- name: opstool
  resourceGroup: '{{ .svc.rg }}'
  subscription: '{{ .svc.subscription.key }}'
  steps:
  - name: output
    action: ARM
    template: ../../templates/output-opstool-cluster.bicep
    parameters: ../../configurations/output-opstool-cluster.tmpl.bicepparam
    deploymentLevel: ResourceGroup
    outputOnly: true
  - name: deploy
    aksCluster: '{{ .opstool.aks.name }}'
    action: Helm
    releaseName: 'cihealth'
    releaseNamespace: 'cihealth'
    namespaceFiles:
    - namespace.yaml
    chartDir: deploy
    valuesFile: ./values.yaml.tmpl
    kustoEndpoint:
      resourceGroup: opstool
      step: output
      name: kustoUri
    kustoDatabase: ''
    kustoTable: ''
    inputVariables:
      cihealthUAMIClientId:
        resourceGroup: opstool
        step: output
        name: cihealthUAMIClientId
      workloadKVName:
        resourceGroup: opstool
        step: output
        name: workloadKVName
      tenantId:
        resourceGroup: opstool
        step: output
        name: tenantId
    dependsOn:
    - resourceGroup: opstool
      step: output
    externalDependsOn:
    - serviceGroup: Microsoft.Azure.ARO.HCP.DevCI.Gateway
      resourceGroup: opstool
      step: deploy
    identityFrom:
      resourceGroup: opstool
      step: output
      name: cihealthUAMIId
