cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('cosmosResourceSnapshots')
| where timestamp between ({{ kqlDatetime .FullStartTime }} .. {{ kqlDatetime .FullEndTime }})
{{- if and .ServiceClusterName .ManagementClusterName }}
| where cluster in ('{{ .ServiceClusterName }}', '{{ .ManagementClusterName }}')
{{- end }}
| where subscriptionID == '{{ .SubscriptionID }}'
| where resourceGroup =~ '{{ .ResourceGroup }}'
| where resourceID =~ '{{ .ResourceID }}'
| extend internalId=tostring(content.properties.serviceProviderProperties.clusterServiceID)
| distinct internalId
