broker:
  host: "__brokerHost__"
  port: 8883
azure:
  cloudEnvironmentName: "{{ .cloudEnvironmentName }}"
  clientId: "__msiClientId__"
  tenantId: "__tenantId__"
serviceAccountName: "{{ .maestro.agent.k8s.serviceAccountName }}"
image:
  registry: "{{ .acr.svc.name }}.azurecr.io"
  repository: "{{ .maestro.image.repository }}"
  digest: "{{ .maestro.image.digest }}"
replicas: {{ .maestro.agent.k8s.replicas }}
resources:
  requests:
    cpu: "{{ .maestro.agent.k8s.resources.requests.cpu }}"
    memory: "{{ .maestro.agent.k8s.resources.requests.memory }}"
  limits:
    cpu: "{{ .maestro.agent.k8s.resources.limits.cpu }}"
    memory: "{{ .maestro.agent.k8s.resources.limits.memory }}"
metricsProxy:
  resources:
    requests:
      cpu: "{{ .maestro.agent.metricsProxy.resources.requests.cpu }}"
      memory: "{{ .maestro.agent.metricsProxy.resources.requests.memory }}"
    limits:
      cpu: "{{ .maestro.agent.metricsProxy.resources.limits.cpu }}"
      memory: "{{ .maestro.agent.metricsProxy.resources.limits.memory }}"
init:
  resources:
    requests:
      cpu: "{{ .maestro.agent.init.resources.requests.cpu }}"
      memory: "{{ .maestro.agent.init.resources.requests.memory }}"
    limits:
      cpu: "{{ .maestro.agent.init.resources.limits.cpu }}"
      memory: "{{ .maestro.agent.init.resources.limits.memory }}"
credsKeyVault:
  name: "{{ .mgmtKeyVault.name }}"
  secret: "{{ .maestro.agent.consumerName }}"
consumerName: "{{ .maestro.agent.consumerName }}"
glog_v: "{{ .maestro.agent.loglevel }}"
installAppliedManifestWorkCRD: false
sideCar:
  image:
    registry: "{{ .maestro.agent.sidecar.image.registry }}"
    repository: "{{ .maestro.agent.sidecar.image.repository }}"
    digest: "{{ .maestro.agent.sidecar.image.digest }}"
deployment:
  zoneCount: {{ .azureRegionAvailabilityZoneCount }}
