cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('frontendLogs')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where log.client_request_id == '{{ .ClientRequestID }}'
| where log.msg == 'response complete'
| project asyncOperationPath = tolower(tostring(parse_url(tostring(log["Header---Azure-AsyncOperation"])).Path))
| where tostring(asyncOperationPath) != ''
| distinct asyncOperationPath
