{
 "title": "Arobit Forwarder Dashboard",
 "description": "This is a simple dashboard for: https://github.com/banzaicloud/logging-operator utilising Fluent-bit and Fluentd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(up,cluster)" },
   {
    "name": "fluentbit",
    "query": "label_values(fluentbit_input_bytes_total,pod)"
   }
  ]
 },
 "panels": [
  { "title": "fluentbit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fluentbit Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_input_bytes_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}}/{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}}/{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_input_records_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}}/{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}}/{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Retries/Fails",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_output_retries_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "Retries {{cluster}}/{{pod}}/{{name}}"
    },
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "Failed {{cluster}}/{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod, name) (max without (prometheus_replica) (rate(fluentbit_output_errors_total{cluster=~\"$cluster\", pod=~\"$fluentbit\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}}/{{pod}}/{{name}}"
    }
   ]
  }
 ]
}