apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: addon-hosted-config
  namespace: multicluster-engine
spec:
  {{- $requirements := list -}}
  {{- range $key, $container := dict
      "configPolicyController" "deployments:config-policy-controller:config-policy-controller"
      "governancePolicyFramework" "deployments:governance-policy-framework:governance-policy-framework-addon"
      "workManager" "deployments:klusterlet-addon-workmgr:acm-agent" -}}
    {{- $resources := include "acm.resources" (index $.Values.resources $key) | fromYaml -}}
    {{- if $resources -}}
      {{- $requirements = append $requirements (dict "containerID" $container "resources" $resources) -}}
    {{- end -}}
  {{- end }}
  {{- with $requirements }}
  resourceRequirements:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  customizedVariables:
  - name: managedKubeConfigSecret
    value: external-managed-kubeconfig
  nodePlacement:
    tolerations:
    - effect: NoSchedule
      key: infra
      operator: "Equal"
      value: "true"
    nodeSelector:
      aro-hcp.azure.com/role: infra
