apiVersion: batch/v1
kind: Job
metadata:
  name: finalize-mce-config
  namespace: '{{ .Release.Namespace }}'
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  activeDeadlineSeconds: 1800
  backoffLimit: 3
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for AddonDeploymentConfig 'hypershift-addon-deploy-config' to exist..."
          until kubectl get AddonDeploymentConfig hypershift-addon-deploy-config -n multicluster-engine; do
            sleep 5
          done

          echo "AddonDeploymentConfig 'hypershift-addon-deploy-config' found. Patching..."
          {{- $spec := dict "customizedVariables" (list
              (dict "name" "disableMetrics" "value" "true")
              (dict "name" "disableHOManagement" "value" "true")
              (dict "name" "autoImportDisabled" "value" "true")
              (dict "name" "aroHcp" "value" "true")) -}}
          {{- $resources := include "acm.resources" .Values.resources.hypershiftAddonAgent | fromYaml -}}
          {{- if $resources -}}
            {{- $_ := set $spec "resourceRequirements" (list (dict "containerID" "deployments:hypershift-addon-agent:hypershift-addon-agent" "resources" $resources)) -}}
          {{- end }}
          kubectl patch addondeploymentconfig hypershift-addon-deploy-config -n multicluster-engine --type=merge -p '{{ dict "spec" $spec | toJson }}'
          echo "Patch applied successfully."

          echo "Wait for MulticlusterEngine to be available..."
          timeout=600
          interval=5
          elapsed=0
          while true; do
            phase=$(kubectl get mce multiclusterengine -o jsonpath='{.status.phase}')
            if [ "$phase" = "Available" ] || [ "$phase" = "Paused" ]; then
              break
            fi
            if [ $elapsed -ge $timeout ]; then
              break
            fi
            sleep $interval
            elapsed=$((elapsed + interval))
          done
          if [ $? -ne 0 ]; then
            echo "MulticlusterEngine did not become available within the timeout period."
            exit 1
          fi
          echo "MulticlusterEngine is available"
        image: "{{ .Values.finalizeMceJobImage }}"
        name: finalize
        resources:
          {{- include "acm.resources" .Values.resources.finalize | nindent 10 }}
      restartPolicy: Never
      serviceAccountName: multicluster-engine-operator
