#!/usr/bin/env bash

set -euo pipefail

base=${GITHUB_BASE_REF:-main}
repo=${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}
bot='aro-hcp-robot[bot]'
title='chore(gh-aw): [auto] upgrade agentic workflows (AROSLSRE-2267)'

repair_generated_agent() {
  local agent=.github/agents/agentic-workflows.agent.md
  local generated=.github/agents/agentic-workflows.md
  local version commit
  if [[ -f $generated ]]; then
    mv "$generated" "$agent"
  fi
  if [[ ! -f $agent ]]; then
    echo "gh-aw did not generate its dispatcher agent." >&2
    exit 1
  fi

  version=$(gh aw version | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
  [[ -n $version ]] || { echo "Cannot determine installed gh-aw version." >&2; exit 1; }
  commit=$(gh api "repos/github/gh-aw/commits/$version" --jq '.sha')
  [[ $commit =~ ^[0-9a-f]{40}$ ]] || { echo "Cannot pin gh-aw prompts to a commit." >&2; exit 1; }
  sed -E -i "s@raw\.githubusercontent\.com/github/gh-aw/(main|refs/heads/main|[0-9a-f]{40})/@raw.githubusercontent.com/github/gh-aw/$commit/@g" "$agent"
  if grep -Eo 'raw\.githubusercontent\.com/github/gh-aw/(refs/heads/)?[^/]+/' "$agent" |
    grep -Fvx "raw.githubusercontent.com/github/gh-aw/$commit/"; then
    echo "An unpinned gh-aw prompt reference remains in $agent." >&2
    exit 1
  fi
}

if [[ ${1:-} == --repair-only ]]; then
  repair_generated_agent
  exit 0
fi

prs=$(gh pr list --repo "$repo" --state open --author app/aro-hcp-robot \
  --limit 500 --json number,headRefName,author)
matches=$(jq -c '[.[] | select(
  (.author.login == "app/aro-hcp-robot" or .author.login == "aro-hcp-robot[bot]") and
  (.headRefName | test("^upgrade-agentic-workflows-[a-zA-Z0-9_-]+$"))
)]' <<<"$prs")
count=$(jq 'length' <<<"$matches")
if (( count > 1 )); then
  echo "More than one open upgrade PR matches; refusing to choose a branch." >&2
  exit 1
fi

if (( count == 1 )); then
  number=$(jq -r '.[0].number' <<<"$matches")
  branch=$(jq -r '.[0].headRefName' <<<"$matches")
  gh api "repos/$repo/pulls/$number" |
    jq -e --arg bot "$bot" --arg repo "$repo" --arg base "$base" --arg branch "$branch" \
      '.state == "open" and .user.login == $bot and .head.repo.full_name == $repo and .head.ref == $branch and .base.ref == $base' >/dev/null ||
    { echo "Upgrade PR identity, repository, or base does not match." >&2; exit 1; }
  if [[ ${1:-} == --select-only ]]; then
    printf '%s %s\n' "$number" "$branch"
    exit 0
  fi
  git fetch origin "refs/heads/$branch:refs/remotes/origin/$branch"
  git switch --detach "origin/$branch"
  git switch -c "$branch"
  git merge --no-edit "origin/$base"
else
  number=''
  branch="upgrade-agentic-workflows-${GITHUB_RUN_ID:?GITHUB_RUN_ID is required}"
  if [[ ${1:-} == --select-only ]]; then
    printf 'new %s\n' "$branch"
    exit 0
  fi
  git switch -c "$branch"
fi

gh aw upgrade --yes
repair_generated_agent

make yamlfmt
git add -A
if git diff --cached --name-only | grep -v '^\.github/' >/dev/null; then
  echo "Upgrade changed files outside .github; refusing to publish." >&2
  exit 1
fi
if git diff --cached --quiet && [[ -z $number ]]; then
  echo "No upgrade changes."
  exit 0
fi
if ! git diff --cached --quiet; then
  git commit -m "$title"
fi

make verify-yamlfmt
make -C config detect-change
if [[ -n $(git status --porcelain) ]]; then
  echo "Verification left uncommitted changes; refusing to publish." >&2
  exit 1
fi

cat > /tmp/gh-aw-upgrade-pr.md <<'EOF'
[AROSLSRE-2267](https://redhat.atlassian.net/browse/AROSLSRE-2267)

### What

Upgrade the agentic workflow compiler, refresh its generated workflows and action pins, and keep them pinned to the reviewed release. The recompiler reuses only a uniquely identified aro-hcp-robot upgrade PR, repairs the dispatcher agent and its prompt references, and rejects ambiguous or unrelated PRs.

### Why

The gh-aw runtime can reject workflows compiled by a blocked release, leaving scheduled automation unable to run.

### Testing

The recompiler runs `make verify-yamlfmt` and `make -C config detect-change` before publishing. Required CI checks and reviewer approval still gate merge.

### Special notes for your reviewer

This PR is generated by aro-hcp-robot and opens ready for review after local validation. Review workflow permissions and the generated safe-output protected-file list, including CHANGELOG.md. It does not bypass repository merge gates.

### PR Checklist

- [x] PR is scoped to a single task (no mixed concerns)
- [x] Title follows Conventional Commits format
- [x] Summary explains the why behind the change
- [x] Linked to relevant ticket/issue
- [ ] Self-reviewed the diff
- [x] Local generated-content checks gate publication
- [ ] CI/CD checks are passing (ignore Tide)
- [ ] All comment threads resolved before merge
EOF

git push origin "HEAD:refs/heads/$branch"
if [[ -n $number ]]; then
  gh pr edit "$number" --repo "$repo" --title "$title" --body-file /tmp/gh-aw-upgrade-pr.md
else
  gh pr create --repo "$repo" --base "$base" --head "$branch" \
    --title "$title" --body-file /tmp/gh-aw-upgrade-pr.md
fi
