KUBE_CODEGEN_TAG = v0.35.3

update-kube-codegen:
	curl --fail -o kube-codegen.sh https://raw.githubusercontent.com/kubernetes/code-generator/refs/tags/$(KUBE_CODEGEN_TAG)/kube_codegen.sh
.PHONY: update-kube-codegen
