image:
  registry: "{{ .acr.svc.name }}.azurecr.io"
  repository: "{{ .customExporter.image.repository }}"
  digest: "{{ .customExporter.image.digest }}"
serviceAccount:
  create: true
  name: "aro-hcp-exporter"
  msiClientId: "__msiClientId__"
service:
  name: "aro-hcp-exporter"
deployment:
  name: "aro-hcp-exporter"
resources:
  requests:
    cpu: "{{ .customExporter.k8s.resources.requests.cpu }}"
    memory: "{{ .customExporter.k8s.resources.requests.memory }}"
  limits:
    memory: "{{ .customExporter.k8s.resources.limits.memory }}"
clusterTypes: "{{ .customExporter.clusterTypes }}"
region: "{{ .region }}"
listenAddress: ":8080"
cacheTTL: "60m"
collectionInterval: "2m"
enabledCollectors: "{{ .customExporter.enabledCollectors }}"
kustoRegion: "__kustoRegion__"
kustoCluster: "{{ .kusto.kustoName }}"
