image:
  registry: ""
  repository: ""
  digest: ""
tracing:
  address: ""
  exporter: ""
deployment:
  zoneCount: ""
miseAppId: ""
audit:
  adInstance: ""
  tenantId: ""
  connectSocket: false
armPolicy:
  label: ""
  authority: ""
  audience: ""
  applicationId: ""
genevaActionsPolicy:
  label: ""
  authority: ""
  audience: ""
  applicationId: ""
sessiongatePolicy:
  label: ""
  authority: ""
  audience: ""
