cluster('{{ .ClusterURI }}').database('{{ .ServiceDatabase }}').table('kubernetesEvents')
| where timestamp between ({{ kqlDatetime .StartTime }} .. {{ kqlDatetime .EndTime }})
| where eventNamespace == '{{ .HostedControlPlaneNamespace }}'
    and objectName !contains 'control-plane-pki-operator'
    and objectName !contains 'control-plane-operator'
    and objectName !contains 'hosted-cluster-config-operator'
| project timestamp, objectKind, objectName, reason, message
| order by timestamp asc
