{
 "title": "AKS API Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apiserver_request_total{cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "label_values(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\"}, resource)"
   },
   {
    "name": "code",
    "label": "code",
    "query": "label_values(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\"},code)"
   },
   {
    "name": "verb",
    "label": "verb",
    "query": "label_values(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\"},verb)"
   },
   { "name": "interval", "label": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Kube APIserver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{cluster=\"$cluster\",job=\"kube-apiserver\"}[2m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Kube APIserver memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cluster=\"$cluster\",job=\"kube-apiserver\"}) by (instance)",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "request duration - 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$interval])) by(verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "request rate - by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$interval])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "request duration - 99th quantile - by resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",subresource!=\"log\",verb!~\"WATCH|WATCHLIST|PROXY\"}[$interval])) by(resource,le))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "request duration - 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",code=~\"$code\",verb=~\"$verb\"}[$interval])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "request duration - read vs write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"LIST|GET\"}[$interval])) by(le))",
     "legendFormat": "read"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[$interval])) by(le))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "request rate - read vs write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"LIST|GET\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[$interval]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "requests terminated rate",
   "type": "timeseries",
   "description": "Number of requests which apiserver terminated in self-defense",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{cluster=\"$cluster\",instance=~\"$instance\",code=~\"$code\"}[$interval])) by(component)"
    }
   ]
  },
  {
   "title": "requests status rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\",code=~\"$code\"}[$interval])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "long running requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_request{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "request in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{cluster=\"$cluster\",instance=~\"$instance\"}) by (instance,request_kind)",
     "legendFormat": "{{request_kind}}-{{instance}}"
    }
   ]
  },
  {
   "title": "response size - 99th quantile",
   "type": "timeseries",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_response_sizes_bucket{cluster=\"$cluster\",instance=~\"$instance\",resource=~\"$resource\",verb=~\"$verb\"}[$interval])) by(instance,le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "p&f - request queue length",
   "type": "timeseries",
   "description": "Length of queue in the API Priority and Fairness system, as seen by each request after it is enqueued",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_queue_length_after_enqueue_bucket{cluster=\"$cluster\",instance=~\"$instance\"}[$interval])) by(flow_schema, priority_level, le))",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "p&f - request wait duration - 99th quantile",
   "type": "timeseries",
   "description": "Length of time a request spent waiting in its queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_wait_duration_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\"}[5m])) by(flow_schema, priority_level, le))"
    }
   ]
  },
  {
   "title": "p&f - request dispatch rate",
   "type": "timeseries",
   "description": "Number of requests released by API Priority and Fairness system for service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_dispatched_requests_total{cluster=\"$cluster\",instance=~\"$instance\"}[$interval])) by(flow_schema,priority_level)",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "p&f - request execution duration",
   "type": "timeseries",
   "description": "Duration of request execution in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_execution_seconds_bucket{cluster=\"$cluster\",instance=~\"$instance\"}[$interval])) by(flow_schema, priority_level, le))",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "p&f - pending in queue",
   "type": "timeseries",
   "description": "Number of requests currently pending in queues of the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_inqueue_requests{cluster=\"$cluster\",instance=~\"$instance\"}) by (flow_schema,priority_level)",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "p&f - concurrency limit by kube-apiserver",
   "type": "timeseries",
   "description": "Shared concurrency limit in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_request_concurrency_limit{cluster=\"$cluster\",instance=~\".*:443\"}) by (instance,priority_level)"
    }
   ]
  }
 ]
}