{
 "title": "AKS ETCD Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Resource Usage",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 0
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk WAL Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster=\"$cluster\"}[2m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    }
   ]
  },
  {
   "title": "Disk Backend Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_backend_commit_duration_seconds_bucket{cluster=\"$cluster\"}[2m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} DB physical size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} DB logical size"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 17
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "p99 peer to peer latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_peer_received_bytes_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "rx {{instance}} Peer Traffic"
    },
    {
     "expr": "rate(etcd_network_peer_sent_bytes_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "tx {{instance}} Peer Traffic"
    }
   ]
  },
  {
   "title": "gRPC network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "rx {{instance}}"
    },
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "tx {{instance}}"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{cluster=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{cluster=\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{cluster=\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{cluster=\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "the total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "DB Info per Member",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 42
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "% DB Space Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{cluster=\"$cluster\"} / etcd_server_quota_backend_bytes{cluster=\"$cluster\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Left capacity (with fragmented space)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{cluster=\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Size Limit (Backend-bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} Quota Bytes"
    }
   ]
  },
  {
   "title": "General Info",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 51
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{cluster=\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{cluster=\"$cluster\"}[2m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Number of leader changes seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_leader_changes_seen_total{cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total number of failed proposals seen",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_proposals_committed_total{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} Num keys"
    }
   ]
  },
  {
   "title": "Leader Elections Per Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster=\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "delta(etcd_server_slow_apply_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{ instance }} slow applies"
    },
    {
     "expr": "delta(etcd_server_slow_read_indexes_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{ instance }} slow read indexes"
    }
   ]
  },
  {
   "title": "Key Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(etcd_mvcc_put_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{ instance }} puts/s"
    },
    {
     "expr": "rate(etcd_mvcc_delete_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{ instance }} deletes/s"
    }
   ]
  },
  {
   "title": "Heartbeat Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_heartbeat_send_failures_total{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} heartbeat failures"
    },
    {
     "expr": "etcd_server_health_failures{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} health failures"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance  }} keys compacted"
    }
   ]
  }
 ]
}