name: 'Azure CLI, Go, and Make'
description: 'Install Azure CLI, Go, and Make, and run a script'
runs:
  using: 'composite'
  steps:
    - name: 'Prepare workspace'
      run: mkdir -p /workspace/bin

    - name: 'Copy Azure CLI'
      uses: docker://mcr.microsoft.com/azure-cli:2.64.0
      with:
        args: |
          /bin/bash -c "
          cp -r /usr/local/bin/az /workspace/bin/ &&
          cp -r /usr/local/az /workspace/bin/
          "
      volumes:
        - name: workspace
          path: /workspace

    - name: 'Build templatize'
      uses: docker://golang:1.23
      with:
        args: |
          /bin/bash -c "
          go build -o /workspace/templatize ./tooling/templatize
          "
      env:
        GO111MODULE: 'on'
      volumes:
        - name: workspace
          path: /workspace

    - name: 'Install Make'
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: 'Run script'
      run: ${{ inputs.script }}
      shell: bash

inputs:
  script:
    description: 'The script to run'
    required: true
