# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "arohcp hcp-open-shift-cluster update",
)
class Update(AAZCommand):
    """Update a HcpOpenShiftCluster

    :example: HcpOpenShiftClusters_CreateOrUpdate
        az arohcp hcp-open-shift-cluster update --resource-group rgopenapi --hcp-open-shift-cluster-name hcpCluster-name
    """

    _aaz_info = {
        "version": "2025-12-23-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.redhatopenshift/hcpopenshiftclusters/{}", "2025-12-23-preview"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    AZ_SUPPORT_GENERIC_UPDATE = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.hcp_open_shift_cluster_name = AAZStrArg(
            options=["-n", "--name", "--hcp-open-shift-cluster-name"],
            help="The name of the HcpOpenShiftCluster",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z][-a-zA-Z0-9]{1,52}[a-zA-Z0-9]$",
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "Identity"

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.autoscaling = AAZObjectArg(
            options=["--autoscaling"],
            arg_group="Properties",
            help="Configure ClusterAutoscaling .",
            nullable=True,
        )
        _args_schema.image_digest_mirrors = AAZListArg(
            options=["--image-digest-mirrors"],
            arg_group="Properties",
            help="imageDigestMirrors is a set of rules to allow pulling images from a mirrored registry by using digest specifications.",
            nullable=True,
            fmt=AAZListArgFormat(
                max_length=240,
            ),
        )
        _args_schema.node_drain_timeout_minutes = AAZIntArg(
            options=["--node-drain-timeout-minutes"],
            arg_group="Properties",
            help="nodeDrainTimeoutMinutes is the grace period for how long Pod Disruption Budget-protected workloads will be respected during any node draining operation. After this grace period, any workloads protected by Pod Disruption Budgets that have not been successfully drained from a node will be forcibly evicted. This is especially relevant to cluster upgrades.  Valid values are in minutes and from 0 to 10080 minutes (1 week). 0 means that the MachinePool can be drained without any time limitation.  This is the value is used a default for all NodePools. It can be overridden by specifying nodeDrainTimeoutMinutes for a given NodePool",
            nullable=True,
            fmt=AAZIntArgFormat(
                maximum=10080,
                minimum=0,
            ),
        )
        _args_schema.platform = AAZObjectArg(
            options=["--platform"],
            arg_group="Properties",
            help="Azure platform configuration",
        )
        _args_schema.version = AAZObjectArg(
            options=["--version"],
            arg_group="Properties",
            help="Version of the control plane components",
        )

        autoscaling = cls._args_schema.autoscaling
        autoscaling.max_node_provision_time_seconds = AAZIntArg(
            options=["max-node-provision-time-seconds"],
            help="maxNodeProvisionTimeSeconds is the maximum time to wait for node provisioning before considering the provisioning to be unsuccessful. The default is 900 seconds, or 15 minutes.  Note: The default value is not declared in the API specification because of a TypeSpec bug with updatable fields. The default value will be declared in a future API version once the TypeSpec bug is fixed. https://github.com/Azure/typespec-azure/issues/1586",
            nullable=True,
            fmt=AAZIntArgFormat(
                minimum=0,
            ),
        )
        autoscaling.max_nodes_total = AAZIntArg(
            options=["max-nodes-total"],
            help="maxNodesTotal is the maximum allowable number of nodes for the Autoscaler scale out to be operational. The autoscaler will not grow the cluster beyond this number. If omitted, the autoscaler will not have a maximum limit.",
            nullable=True,
            fmt=AAZIntArgFormat(
                minimum=0,
            ),
        )
        autoscaling.max_pod_grace_period_seconds = AAZIntArg(
            options=["max-pod-grace-period-seconds"],
            help="maxPodGracePeriod is the maximum seconds to wait for graceful pod termination before scaling down a NodePool. The default is 600 seconds.  Note: The default value is not declared in the API specification because of a TypeSpec bug with updatable fields. The default value will be declared in a future API version once the TypeSpec bug is fixed. https://github.com/Azure/typespec-azure/issues/1586",
            nullable=True,
            fmt=AAZIntArgFormat(
                minimum=0,
            ),
        )
        autoscaling.pod_priority_threshold = AAZIntArg(
            options=["pod-priority-threshold"],
            help="podPriorityThreshold enables users to schedule \"best-effort\" pods, which shouldn't trigger autoscaler actions, but only run when there are spare resources available. The default is -10. See the following for more details: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-work-with-pod-priority-and-preemption  Note: The default value is not declared in the API specification because of a TypeSpec bug with updatable fields. The default value will be declared in a future API version once the TypeSpec bug is fixed. https://github.com/Azure/typespec-azure/issues/1586",
            nullable=True,
        )

        image_digest_mirrors = cls._args_schema.image_digest_mirrors
        image_digest_mirrors.Element = AAZObjectArg(
            nullable=True,
        )

        _element = cls._args_schema.image_digest_mirrors.Element
        _element.mirrors = AAZListArg(
            options=["mirrors"],
            help="Mirrors are one or more image repositories that may also contain the same images.",
            fmt=AAZListArgFormat(
                max_length=255,
                min_length=1,
            ),
        )
        _element.source = AAZStrArg(
            options=["source"],
            help="Source is the image repository that users refer to, e.g. in image pull specifications.",
            fmt=AAZStrArgFormat(
                max_length=255,
            ),
        )

        mirrors = cls._args_schema.image_digest_mirrors.Element.mirrors
        mirrors.Element = AAZStrArg(
            nullable=True,
            fmt=AAZStrArgFormat(
                max_length=255,
            ),
        )

        platform = cls._args_schema.platform
        platform.operators_authentication = AAZObjectArg(
            options=["operators-authentication"],
            help="The configuration that the operators of the cluster have to authenticate to Azure",
        )

        operators_authentication = cls._args_schema.platform.operators_authentication
        operators_authentication.user_assigned_identities = AAZObjectArg(
            options=["user-assigned-identities"],
            help="Represents the information related to Azure User-Assigned managed identities needed to perform Operators authentication based on Azure User-Assigned Managed Identities",
        )

        user_assigned_identities = cls._args_schema.platform.operators_authentication.user_assigned_identities
        user_assigned_identities.control_plane_operators = AAZDictArg(
            options=["control-plane-operators"],
            help="The set of Azure User-Assigned Managed Identities leveraged for the Control Plane operators of the cluster. The set of required managed identities is dependent on the Cluster's OpenShift version.",
        )
        user_assigned_identities.data_plane_operators = AAZDictArg(
            options=["data-plane-operators"],
            help="The set of Azure User-Assigned Managed Identities leveraged for the Data Plane operators of the cluster. The set of required managed identities is dependent on the Cluster's OpenShift version.",
        )
        user_assigned_identities.service_managed_identity = AAZResourceIdArg(
            options=["service-managed-identity"],
            help="Represents the information associated to an Azure User-Assigned Managed Identity whose purpose is to perform service level actions.",
        )

        control_plane_operators = cls._args_schema.platform.operators_authentication.user_assigned_identities.control_plane_operators
        control_plane_operators.Element = AAZResourceIdArg(
            nullable=True,
        )

        data_plane_operators = cls._args_schema.platform.operators_authentication.user_assigned_identities.data_plane_operators
        data_plane_operators.Element = AAZResourceIdArg(
            nullable=True,
        )

        version = cls._args_schema.version
        version.channel_group = AAZStrArg(
            options=["channel-group"],
            help="ChannelGroup is the name of the set to which this version belongs. Each version belongs to only a single set.  If not specified, the default value is 'stable'.  Note: The default value is not declared in the API specification because of a TypeSpec bug with updatable fields. The default value will be declared in a future API version once the TypeSpec bug is fixed. https://github.com/Azure/typespec-azure/issues/1586",
            nullable=True,
        )
        version.id = AAZStrArg(
            options=["id"],
            help="ID is the desired X.Y version of the cluster control plane.",
        )

        # define Arg Group "Resource"

        _args_schema = cls._args_schema
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="Resource",
            help="Resource tags.",
            nullable=True,
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg(
            nullable=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.HcpOpenShiftClustersGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.vars.instance)
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.InstanceUpdateByGeneric(ctx=self.ctx)()
        self.post_instance_update(self.ctx.vars.instance)
        yield self.HcpOpenShiftClustersCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class HcpOpenShiftClustersGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RedHatOpenShift/hcpOpenShiftClusters/{hcpOpenShiftClusterName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "hcpOpenShiftClusterName", self.ctx.args.hcp_open_shift_cluster_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-12-23-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_hcp_open_shift_cluster_read(cls._schema_on_200)

            return cls._schema_on_200

    class HcpOpenShiftClustersCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RedHatOpenShift/hcpOpenShiftClusters/{hcpOpenShiftClusterName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "hcpOpenShiftClusterName", self.ctx.args.hcp_open_shift_cluster_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-12-23-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_hcp_open_shift_cluster_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.vars.instance)

        def _update_instance(self, instance):
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZObjectType
            )
            _builder.set_prop("identity", AAZIdentityObjectType)
            _builder.set_prop("properties", AAZObjectType)
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("autoscaling", AAZObjectType, ".autoscaling")
                properties.set_prop("imageDigestMirrors", AAZListType, ".image_digest_mirrors")
                properties.set_prop("nodeDrainTimeoutMinutes", AAZIntType, ".node_drain_timeout_minutes")
                properties.set_prop("platform", AAZObjectType, ".platform", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("version", AAZObjectType, ".version", typ_kwargs={"flags": {"required": True}})

            autoscaling = _builder.get(".properties.autoscaling")
            if autoscaling is not None:
                autoscaling.set_prop("maxNodeProvisionTimeSeconds", AAZIntType, ".max_node_provision_time_seconds")
                autoscaling.set_prop("maxNodesTotal", AAZIntType, ".max_nodes_total")
                autoscaling.set_prop("maxPodGracePeriodSeconds", AAZIntType, ".max_pod_grace_period_seconds")
                autoscaling.set_prop("podPriorityThreshold", AAZIntType, ".pod_priority_threshold")

            image_digest_mirrors = _builder.get(".properties.imageDigestMirrors")
            if image_digest_mirrors is not None:
                image_digest_mirrors.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.imageDigestMirrors[]")
            if _elements is not None:
                _elements.set_prop("mirrors", AAZListType, ".mirrors", typ_kwargs={"flags": {"required": True}})
                _elements.set_prop("source", AAZStrType, ".source", typ_kwargs={"flags": {"required": True}})

            mirrors = _builder.get(".properties.imageDigestMirrors[].mirrors")
            if mirrors is not None:
                mirrors.set_elements(AAZStrType, ".")

            platform = _builder.get(".properties.platform")
            if platform is not None:
                platform.set_prop("operatorsAuthentication", AAZObjectType, ".operators_authentication", typ_kwargs={"flags": {"required": True}})

            operators_authentication = _builder.get(".properties.platform.operatorsAuthentication")
            if operators_authentication is not None:
                operators_authentication.set_prop("userAssignedIdentities", AAZObjectType, ".user_assigned_identities", typ_kwargs={"flags": {"required": True}})

            user_assigned_identities = _builder.get(".properties.platform.operatorsAuthentication.userAssignedIdentities")
            if user_assigned_identities is not None:
                user_assigned_identities.set_prop("controlPlaneOperators", AAZDictType, ".control_plane_operators", typ_kwargs={"flags": {"required": True}})
                user_assigned_identities.set_prop("dataPlaneOperators", AAZDictType, ".data_plane_operators", typ_kwargs={"flags": {"required": True}})
                user_assigned_identities.set_prop("serviceManagedIdentity", AAZStrType, ".service_managed_identity", typ_kwargs={"flags": {"required": True}})

            control_plane_operators = _builder.get(".properties.platform.operatorsAuthentication.userAssignedIdentities.controlPlaneOperators")
            if control_plane_operators is not None:
                control_plane_operators.set_elements(AAZStrType, ".")

            data_plane_operators = _builder.get(".properties.platform.operatorsAuthentication.userAssignedIdentities.dataPlaneOperators")
            if data_plane_operators is not None:
                data_plane_operators.set_elements(AAZStrType, ".")

            version = _builder.get(".properties.version")
            if version is not None:
                version.set_prop("channelGroup", AAZStrType, ".channel_group")
                version.set_prop("id", AAZStrType, ".id", typ_kwargs={"flags": {"required": True}})

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return _instance_value

    class InstanceUpdateByGeneric(AAZGenericInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance_by_generic(
                self.ctx.vars.instance,
                self.ctx.generic_update_args
            )


class _UpdateHelper:
    """Helper class for Update"""

    _schema_hcp_open_shift_cluster_read = None

    @classmethod
    def _build_schema_hcp_open_shift_cluster_read(cls, _schema):
        if cls._schema_hcp_open_shift_cluster_read is not None:
            _schema.id = cls._schema_hcp_open_shift_cluster_read.id
            _schema.identity = cls._schema_hcp_open_shift_cluster_read.identity
            _schema.location = cls._schema_hcp_open_shift_cluster_read.location
            _schema.name = cls._schema_hcp_open_shift_cluster_read.name
            _schema.properties = cls._schema_hcp_open_shift_cluster_read.properties
            _schema.system_data = cls._schema_hcp_open_shift_cluster_read.system_data
            _schema.tags = cls._schema_hcp_open_shift_cluster_read.tags
            _schema.type = cls._schema_hcp_open_shift_cluster_read.type
            return

        cls._schema_hcp_open_shift_cluster_read = _schema_hcp_open_shift_cluster_read = AAZObjectType()

        hcp_open_shift_cluster_read = _schema_hcp_open_shift_cluster_read
        hcp_open_shift_cluster_read.id = AAZStrType(
            flags={"read_only": True},
        )
        hcp_open_shift_cluster_read.identity = AAZIdentityObjectType()
        hcp_open_shift_cluster_read.location = AAZStrType(
            flags={"required": True},
        )
        hcp_open_shift_cluster_read.name = AAZStrType(
            flags={"read_only": True},
        )
        hcp_open_shift_cluster_read.properties = AAZObjectType()
        hcp_open_shift_cluster_read.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        hcp_open_shift_cluster_read.tags = AAZDictType()
        hcp_open_shift_cluster_read.type = AAZStrType(
            flags={"read_only": True},
        )

        identity = _schema_hcp_open_shift_cluster_read.identity
        identity.principal_id = AAZStrType(
            serialized_name="principalId",
            flags={"read_only": True},
        )
        identity.tenant_id = AAZStrType(
            serialized_name="tenantId",
            flags={"read_only": True},
        )
        identity.type = AAZStrType(
            flags={"required": True},
        )
        identity.user_assigned_identities = AAZDictType(
            serialized_name="userAssignedIdentities",
        )

        user_assigned_identities = _schema_hcp_open_shift_cluster_read.identity.user_assigned_identities
        user_assigned_identities.Element = AAZObjectType(
            nullable=True,
        )

        _element = _schema_hcp_open_shift_cluster_read.identity.user_assigned_identities.Element
        _element.client_id = AAZStrType(
            serialized_name="clientId",
            flags={"read_only": True},
        )
        _element.principal_id = AAZStrType(
            serialized_name="principalId",
            flags={"read_only": True},
        )

        properties = _schema_hcp_open_shift_cluster_read.properties
        properties.api = AAZObjectType()
        properties.autoscaling = AAZObjectType()
        properties.cluster_image_registry = AAZObjectType(
            serialized_name="clusterImageRegistry",
        )
        properties.console = AAZObjectType(
            flags={"read_only": True},
        )
        properties.dns = AAZObjectType()
        properties.etcd = AAZObjectType()
        properties.image_digest_mirrors = AAZListType(
            serialized_name="imageDigestMirrors",
        )
        properties.network = AAZObjectType()
        properties.node_drain_timeout_minutes = AAZIntType(
            serialized_name="nodeDrainTimeoutMinutes",
        )
        properties.platform = AAZObjectType(
            flags={"required": True},
        )
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
            flags={"read_only": True},
        )
        properties.version = AAZObjectType(
            flags={"required": True},
        )

        api = _schema_hcp_open_shift_cluster_read.properties.api
        api.authorized_cidrs = AAZListType(
            serialized_name="authorizedCidrs",
        )
        api.url = AAZStrType(
            flags={"read_only": True},
        )
        api.visibility = AAZStrType()

        authorized_cidrs = _schema_hcp_open_shift_cluster_read.properties.api.authorized_cidrs
        authorized_cidrs.Element = AAZStrType()

        autoscaling = _schema_hcp_open_shift_cluster_read.properties.autoscaling
        autoscaling.max_node_provision_time_seconds = AAZIntType(
            serialized_name="maxNodeProvisionTimeSeconds",
        )
        autoscaling.max_nodes_total = AAZIntType(
            serialized_name="maxNodesTotal",
        )
        autoscaling.max_pod_grace_period_seconds = AAZIntType(
            serialized_name="maxPodGracePeriodSeconds",
        )
        autoscaling.pod_priority_threshold = AAZIntType(
            serialized_name="podPriorityThreshold",
        )

        cluster_image_registry = _schema_hcp_open_shift_cluster_read.properties.cluster_image_registry
        cluster_image_registry.state = AAZStrType()

        console = _schema_hcp_open_shift_cluster_read.properties.console
        console.url = AAZStrType(
            flags={"read_only": True},
        )

        dns = _schema_hcp_open_shift_cluster_read.properties.dns
        dns.base_domain = AAZStrType(
            serialized_name="baseDomain",
            flags={"read_only": True},
        )
        dns.base_domain_prefix = AAZStrType(
            serialized_name="baseDomainPrefix",
        )

        etcd = _schema_hcp_open_shift_cluster_read.properties.etcd
        etcd.data_encryption = AAZObjectType(
            serialized_name="dataEncryption",
        )

        data_encryption = _schema_hcp_open_shift_cluster_read.properties.etcd.data_encryption
        data_encryption.customer_managed = AAZObjectType(
            serialized_name="customerManaged",
        )
        data_encryption.key_management_mode = AAZStrType(
            serialized_name="keyManagementMode",
        )

        customer_managed = _schema_hcp_open_shift_cluster_read.properties.etcd.data_encryption.customer_managed
        customer_managed.encryption_type = AAZStrType(
            serialized_name="encryptionType",
        )
        customer_managed.kms = AAZObjectType()

        kms = _schema_hcp_open_shift_cluster_read.properties.etcd.data_encryption.customer_managed.kms
        kms.active_key = AAZObjectType(
            serialized_name="activeKey",
            flags={"required": True},
        )
        kms.vault_name = AAZStrType(
            serialized_name="vaultName",
            flags={"required": True},
        )
        kms.visibility = AAZStrType(
            flags={"required": True},
        )

        active_key = _schema_hcp_open_shift_cluster_read.properties.etcd.data_encryption.customer_managed.kms.active_key
        active_key.name = AAZStrType(
            flags={"required": True},
        )
        active_key.version = AAZStrType(
            flags={"required": True},
        )

        image_digest_mirrors = _schema_hcp_open_shift_cluster_read.properties.image_digest_mirrors
        image_digest_mirrors.Element = AAZObjectType()

        _element = _schema_hcp_open_shift_cluster_read.properties.image_digest_mirrors.Element
        _element.mirrors = AAZListType(
            flags={"required": True},
        )
        _element.source = AAZStrType(
            flags={"required": True},
        )

        mirrors = _schema_hcp_open_shift_cluster_read.properties.image_digest_mirrors.Element.mirrors
        mirrors.Element = AAZStrType()

        network = _schema_hcp_open_shift_cluster_read.properties.network
        network.host_prefix = AAZIntType(
            serialized_name="hostPrefix",
        )
        network.machine_cidr = AAZStrType(
            serialized_name="machineCidr",
        )
        network.network_type = AAZStrType(
            serialized_name="networkType",
        )
        network.pod_cidr = AAZStrType(
            serialized_name="podCidr",
        )
        network.service_cidr = AAZStrType(
            serialized_name="serviceCidr",
        )

        platform = _schema_hcp_open_shift_cluster_read.properties.platform
        platform.issuer_url = AAZStrType(
            serialized_name="issuerUrl",
            flags={"read_only": True},
        )
        platform.managed_resource_group = AAZStrType(
            serialized_name="managedResourceGroup",
        )
        platform.network_security_group_id = AAZStrType(
            serialized_name="networkSecurityGroupId",
            flags={"required": True},
        )
        platform.operators_authentication = AAZObjectType(
            serialized_name="operatorsAuthentication",
            flags={"required": True},
        )
        platform.outbound_type = AAZStrType(
            serialized_name="outboundType",
        )
        platform.subnet_id = AAZStrType(
            serialized_name="subnetId",
            flags={"required": True},
        )
        platform.vnet_integration_subnet_id = AAZStrType(
            serialized_name="vnetIntegrationSubnetId",
            flags={"required": True},
        )

        operators_authentication = _schema_hcp_open_shift_cluster_read.properties.platform.operators_authentication
        operators_authentication.user_assigned_identities = AAZObjectType(
            serialized_name="userAssignedIdentities",
            flags={"required": True},
        )

        user_assigned_identities = _schema_hcp_open_shift_cluster_read.properties.platform.operators_authentication.user_assigned_identities
        user_assigned_identities.control_plane_operators = AAZDictType(
            serialized_name="controlPlaneOperators",
            flags={"required": True},
        )
        user_assigned_identities.data_plane_operators = AAZDictType(
            serialized_name="dataPlaneOperators",
            flags={"required": True},
        )
        user_assigned_identities.service_managed_identity = AAZStrType(
            serialized_name="serviceManagedIdentity",
            flags={"required": True},
        )

        control_plane_operators = _schema_hcp_open_shift_cluster_read.properties.platform.operators_authentication.user_assigned_identities.control_plane_operators
        control_plane_operators.Element = AAZStrType()

        data_plane_operators = _schema_hcp_open_shift_cluster_read.properties.platform.operators_authentication.user_assigned_identities.data_plane_operators
        data_plane_operators.Element = AAZStrType()

        version = _schema_hcp_open_shift_cluster_read.properties.version
        version.channel_group = AAZStrType(
            serialized_name="channelGroup",
        )
        version.id = AAZStrType(
            flags={"required": True},
        )

        system_data = _schema_hcp_open_shift_cluster_read.system_data
        system_data.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        tags = _schema_hcp_open_shift_cluster_read.tags
        tags.Element = AAZStrType()

        _schema.id = cls._schema_hcp_open_shift_cluster_read.id
        _schema.identity = cls._schema_hcp_open_shift_cluster_read.identity
        _schema.location = cls._schema_hcp_open_shift_cluster_read.location
        _schema.name = cls._schema_hcp_open_shift_cluster_read.name
        _schema.properties = cls._schema_hcp_open_shift_cluster_read.properties
        _schema.system_data = cls._schema_hcp_open_shift_cluster_read.system_data
        _schema.tags = cls._schema_hcp_open_shift_cluster_read.tags
        _schema.type = cls._schema_hcp_open_shift_cluster_read.type


__all__ = ["Update"]
