FROM scratch
# this is a placeholder dockerfile that needs to exist so we can
# update the prow jobs to build and test hcp-recovery images
# this allows us to runt E2E tests on the PR that will introduce the real
# hcp-recovery component