apiVersion: v1
kind: ConfigMap
metadata:
  name: hypershift-oadp-plugin-config
  namespace: velero
data:
  etcdBackupMethod: "etcdSnapshot" # or "volumeSnapshot" (default)
  hoNamespace: "hypershift" # HyperShift Operator namespace (default)
  migration: "true"
