//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package fleetapi

import (
	v4 "github.com/blang/semver/v4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	"github.com/Azure/ARO-HCP/internal/api/coreapi"
	metadataapi "github.com/Azure/ARO-HCP/internal/api/metadataapi"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVersionRollout) DeepCopyInto(out *ControlPlaneVersionRollout) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVersionRollout.
func (in *ControlPlaneVersionRollout) DeepCopy() *ControlPlaneVersionRollout {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVersionRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneVersionRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVersionRolloutList) DeepCopyInto(out *ControlPlaneVersionRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlaneVersionRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVersionRolloutList.
func (in *ControlPlaneVersionRolloutList) DeepCopy() *ControlPlaneVersionRolloutList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVersionRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneVersionRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVersionRolloutSpec) DeepCopyInto(out *ControlPlaneVersionRolloutSpec) {
	*out = *in
	if in.BestExactVersion != nil {
		in, out := &in.BestExactVersion, &out.BestExactVersion
		*out = new(v4.Version)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVersionRolloutSpec.
func (in *ControlPlaneVersionRolloutSpec) DeepCopy() *ControlPlaneVersionRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVersionRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVersionRolloutStatus) DeepCopyInto(out *ControlPlaneVersionRolloutStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterCountByDesiredExactVersion != nil {
		in, out := &in.ClusterCountByDesiredExactVersion, &out.ClusterCountByDesiredExactVersion
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MismatchedClusterCountByDesiredExactVersion != nil {
		in, out := &in.MismatchedClusterCountByDesiredExactVersion, &out.MismatchedClusterCountByDesiredExactVersion
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FailedClusterCountByDesiredExactVersion != nil {
		in, out := &in.FailedClusterCountByDesiredExactVersion, &out.FailedClusterCountByDesiredExactVersion
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClusterCountByAchievedExactVersion != nil {
		in, out := &in.ClusterCountByAchievedExactVersion, &out.ClusterCountByAchievedExactVersion
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SuccessfulClusterCountByAchievedExactVersion != nil {
		in, out := &in.SuccessfulClusterCountByAchievedExactVersion, &out.SuccessfulClusterCountByAchievedExactVersion
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVersionRolloutStatus.
func (in *ControlPlaneVersionRolloutStatus) DeepCopy() *ControlPlaneVersionRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVersionRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCluster) DeepCopyInto(out *ManagementCluster) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCluster.
func (in *ManagementCluster) DeepCopy() *ManagementCluster {
	if in == nil {
		return nil
	}
	out := new(ManagementCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterList) DeepCopyInto(out *ManagementClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterList.
func (in *ManagementClusterList) DeepCopy() *ManagementClusterList {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterSpec) DeepCopyInto(out *ManagementClusterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterSpec.
func (in *ManagementClusterSpec) DeepCopy() *ManagementClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterStatus) DeepCopyInto(out *ManagementClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AKSResourceID != nil {
		in, out := &in.AKSResourceID, &out.AKSResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	if in.PublicDNSZoneResourceID != nil {
		in, out := &in.PublicDNSZoneResourceID, &out.PublicDNSZoneResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	if in.ClusterServiceProvisionShardID != nil {
		in, out := &in.ClusterServiceProvisionShardID, &out.ClusterServiceProvisionShardID
		*out = new(metadataapi.InternalID)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterStatus.
func (in *ManagementClusterStatus) DeepCopy() *ManagementClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stamp) DeepCopyInto(out *Stamp) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stamp.
func (in *Stamp) DeepCopy() *Stamp {
	if in == nil {
		return nil
	}
	out := new(Stamp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Stamp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampList) DeepCopyInto(out *StampList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Stamp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampList.
func (in *StampList) DeepCopy() *StampList {
	if in == nil {
		return nil
	}
	out := new(StampList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StampList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampSpec) DeepCopyInto(out *StampSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampSpec.
func (in *StampSpec) DeepCopy() *StampSpec {
	if in == nil {
		return nil
	}
	out := new(StampSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampStatus) DeepCopyInto(out *StampStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampStatus.
func (in *StampStatus) DeepCopy() *StampStatus {
	if in == nil {
		return nil
	}
	out := new(StampStatus)
	in.DeepCopyInto(out)
	return out
}
