//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package fleetapi

import (
	azcorearm "github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	"github.com/Azure/ARO-HCP/internal/api/coreapi"
	metadataapi "github.com/Azure/ARO-HCP/internal/api/metadataapi"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPResourceRequirements) DeepCopyInto(out *HCPResourceRequirements) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPResourceRequirements.
func (in *HCPResourceRequirements) DeepCopy() *HCPResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(HCPResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCPResourceRequirements) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPResourceRequirementsList) DeepCopyInto(out *HCPResourceRequirementsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HCPResourceRequirements, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPResourceRequirementsList.
func (in *HCPResourceRequirementsList) DeepCopy() *HCPResourceRequirementsList {
	if in == nil {
		return nil
	}
	out := new(HCPResourceRequirementsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HCPResourceRequirementsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCPResourceRequirementsStatus) DeepCopyInto(out *HCPResourceRequirementsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReportedAt != nil {
		in, out := &in.LastReportedAt, &out.LastReportedAt
		*out = (*in).DeepCopy()
	}
	if in.AverageUsage != nil {
		in, out := &in.AverageUsage, &out.AverageUsage
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AverageRequests != nil {
		in, out := &in.AverageRequests, &out.AverageRequests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCPResourceRequirementsStatus.
func (in *HCPResourceRequirementsStatus) DeepCopy() *HCPResourceRequirementsStatus {
	if in == nil {
		return nil
	}
	out := new(HCPResourceRequirementsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementCluster) DeepCopyInto(out *ManagementCluster) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementCluster.
func (in *ManagementCluster) DeepCopy() *ManagementCluster {
	if in == nil {
		return nil
	}
	out := new(ManagementCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterList) DeepCopyInto(out *ManagementClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterList.
func (in *ManagementClusterList) DeepCopy() *ManagementClusterList {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterScheduling) DeepCopyInto(out *ManagementClusterScheduling) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterScheduling.
func (in *ManagementClusterScheduling) DeepCopy() *ManagementClusterScheduling {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterScheduling) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterSchedulingList) DeepCopyInto(out *ManagementClusterSchedulingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementClusterScheduling, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterSchedulingList.
func (in *ManagementClusterSchedulingList) DeepCopy() *ManagementClusterSchedulingList {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterSchedulingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementClusterSchedulingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterSchedulingStatus) DeepCopyInto(out *ManagementClusterSchedulingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ObservedResources.DeepCopyInto(&out.ObservedResources)
	if in.ReadyResourceIDs != nil {
		in, out := &in.ReadyResourceIDs, &out.ReadyResourceIDs
		*out = make([]*azcorearm.ResourceID, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = coreapi.DeepCopyResourceID(*in)
			}
		}
	}
	if in.NotReadyResourceIDs != nil {
		in, out := &in.NotReadyResourceIDs, &out.NotReadyResourceIDs
		*out = make([]*azcorearm.ResourceID, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = coreapi.DeepCopyResourceID(*in)
			}
		}
	}
	in.ScaleCeiling.DeepCopyInto(&out.ScaleCeiling)
	if in.PendingAssignedClusters != nil {
		in, out := &in.PendingAssignedClusters, &out.PendingAssignedClusters
		*out = make([]*azcorearm.ResourceID, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = coreapi.DeepCopyResourceID(*in)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterSchedulingStatus.
func (in *ManagementClusterSchedulingStatus) DeepCopy() *ManagementClusterSchedulingStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterSchedulingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterSpec) DeepCopyInto(out *ManagementClusterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterSpec.
func (in *ManagementClusterSpec) DeepCopy() *ManagementClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementClusterStatus) DeepCopyInto(out *ManagementClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AKSResourceID != nil {
		in, out := &in.AKSResourceID, &out.AKSResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	if in.PublicDNSZoneResourceID != nil {
		in, out := &in.PublicDNSZoneResourceID, &out.PublicDNSZoneResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	if in.ClusterServiceProvisionShardID != nil {
		in, out := &in.ClusterServiceProvisionShardID, &out.ClusterServiceProvisionShardID
		*out = new(metadataapi.InternalID)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementClusterStatus.
func (in *ManagementClusterStatus) DeepCopy() *ManagementClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedResources) DeepCopyInto(out *ObservedResources) {
	*out = *in
	if in.LastReportedAt != nil {
		in, out := &in.LastReportedAt, &out.LastReportedAt
		*out = (*in).DeepCopy()
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedResources.
func (in *ObservedResources) DeepCopy() *ObservedResources {
	if in == nil {
		return nil
	}
	out := new(ObservedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleCeiling) DeepCopyInto(out *ScaleCeiling) {
	*out = *in
	if in.LastReportedAt != nil {
		in, out := &in.LastReportedAt, &out.LastReportedAt
		*out = (*in).DeepCopy()
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleCeiling.
func (in *ScaleCeiling) DeepCopy() *ScaleCeiling {
	if in == nil {
		return nil
	}
	out := new(ScaleCeiling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stamp) DeepCopyInto(out *Stamp) {
	*out = *in
	in.CosmosMetadata.DeepCopyInto(&out.CosmosMetadata)
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = coreapi.DeepCopyResourceID(*in)
	}
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stamp.
func (in *Stamp) DeepCopy() *Stamp {
	if in == nil {
		return nil
	}
	out := new(Stamp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Stamp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampList) DeepCopyInto(out *StampList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Stamp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampList.
func (in *StampList) DeepCopy() *StampList {
	if in == nil {
		return nil
	}
	out := new(StampList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StampList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampSpec) DeepCopyInto(out *StampSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampSpec.
func (in *StampSpec) DeepCopy() *StampSpec {
	if in == nil {
		return nil
	}
	out := new(StampSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StampStatus) DeepCopyInto(out *StampStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StampStatus.
func (in *StampStatus) DeepCopy() *StampStatus {
	if in == nil {
		return nil
	}
	out := new(StampStatus)
	in.DeepCopyInto(out)
	return out
}
