.create-merge table backendContainerLogs (
    log: dynamic,
    tag: string,
    timestamp: datetime,
  	namespace: string,
    container_image: string,
  	host: string,
    labels: string,
    podName: string,
    region: string,
    cluster: string,
    environment: string,
    unmatched: dynamic,
	  level: string,
    operation: string,
    operationId: string,
    resourceId: string,
    internalId: string,
    clusterId: string,
    clientRequestId: string,
    correlationRequestId: string,
    cloudErrorCode: string,
    cloudErrorMessage: string,
    subscriptionId: string
)

.create-or-alter table backendContainerLogs ingestion json mapping 'ingestionMapping'
 ```
 [
   {"column":"log","Properties":{"path":"$.log.log"}},
   {"column":"timestamp","Properties":{"path":"$.timestamp"}},
   {"column":"tag","Properties":{"path":"$.tag"}},
   {"column":"region","Properties":{"path":"$.region"}},
   {"column":"cluster","Properties":{"path":"$.cluster"}},
   {"column":"namespace","Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"container_image","Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"host","Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"labels","Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName","Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"environment","Properties":{"path":"$.environment"}},
   {"column":"level","Properties":{"path":"$.level"}},
   {"column":"operation","Properties":{"path":"$.log.operation"}},
   {"column":"operationId","Properties":{"path":"$.log.operation_id"}},
   {"column":"resourceId","Properties":{"path":"$.log.resource_id"}},
   {"column":"internalId","Properties":{"path":"$.log.internal_id"}},
   {"column":"clusterId","Properties":{"path":"$.log.cluster_id"}},
   {"column":"clientRequestId","Properties":{"path":"$.log.client_request_id"}},
   {"column":"correlationRequestId","Properties":{"path":"$.log.correlation_request_id"}},
   {"column":"cloudErrorCode","Properties":{"path":"$.log.cloud_error_code"}},
   {"column":"cloudErrorMessage","Properties":{"path":"$.log.cloud_error_message"}},
   {"column":"subscriptionId","Properties":{"path":"$.log.subscription_id"}},
   {"column":"unmatched","Properties":{"path":"$", "Transform":"DropMappedFields" }}
 ]
 ```
