.create-merge table backendContainerLogs (
    log: dynamic,
    tag: string,
    timestamp: datetime,
  	namespace: string,
    container_image: string,
  	host: string,
    labels: string,
    podName: string,
    region: string,
    cluster: string,
    environment: string,
    unmatched: dynamic,
	  level: string,
    operation: string,
    operationId: string,
    resourceId: string,
    internalId: string,
    clusterId: string,
    clientRequestId: string,
    correlationRequestId: string,
    cloudErrorCode: string,
    cloudErrorMessage: string,
    subscriptionId: string
)

.create-or-alter table backendContainerLogs ingestion json mapping 'ingestionMapping'
 ```
 [
   {"column":"log","Properties":{"path":"$.log"}},
   {"column":"timestamp","Properties":{"path":"$.date"}},
   {"column":"region","Properties":{"path":"$.region"}},
   {"column":"cluster","Properties":{"path":"$.cluster"}},
   {"column":"namespace","Properties":{"path":"$.kubernetes.namespace_name"}},
   {"column":"container_image","Properties":{"path":"$.kubernetes.container_image"}},
   {"column":"host","Properties":{"path":"$.kubernetes.host"}},
   {"column":"labels","Properties":{"path":"$.kubernetes.labels"}},
   {"column":"podName","Properties":{"path":"$.kubernetes.pod_name"}},
   {"column":"environment","Properties":{"path":"$.environment"}},
   {"column":"level","Properties":{"path":"$.level"}},
   {"column":"operation","Properties":{"path":"$.operation"}},
   {"column":"operationId","Properties":{"path":"$.operationId"}},
   {"column":"resourceId","Properties":{"path":"$.resourceId"}},
   {"column":"internalId","Properties":{"path":"$.internalId"}},
   {"column":"clusterId","Properties":{"path":"$.clusterId"}},
   {"column":"clientRequestId","Properties":{"path":"$.clientRequestId"}},
   {"column":"correlationRequestId","Properties":{"path":"$.correlationRequestId"}},
   {"column":"cloudErrorCode","Properties":{"path":"$.cloudErrorCode"}},
   {"column":"cloudErrorMessage","Properties":{"path":"$.cloudErrorMessage"}},
   {"column":"subscriptionId","Properties":{"path":"$.subscriptionId"}},
   {"column":"unmatched","Properties":{"path":"$", "Transform":"DropMappedFields" }}
 ]
 ```
