.execute database script with (ThrowOnErrors=true)
<|
.create-or-alter table containerLogs ingestion json mapping 'ingestionMapping'
 ```
 [
   {"column":"timestamp", "DataType":"datetime", "Properties":{"path":"$.timestamp"}},
   {"column":"log", "DataType":"dynamic", "Properties":{"path":"$.log.log"}},
   {"column":"environment", "DataType":"string", "Properties":{"path":"$.log.environment"}},
   {"column":"region", "DataType":"string", "Properties":{"path":"$.log.region"}},
   {"column":"cluster", "DataType":"string", "Properties":{"path":"$.log.cluster"}},
   {"column":"host", "DataType":"string", "Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"containerName", "Properties": {"path": "$log.kubernetes.container_name"}},
   {"column":"containerImage", "DataType":"string", "Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"namespace", "DataType":"string", "Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"labels", "DataType":"string", "Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName", "DataType":"string", "Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"tag", "DataType":"string", "Properties":{"path":"$.tag"}},
   {"column":"unmatched", "DataType":"dynamic", "Properties":{"path":"$", "Transform":"DropMappedFields" }}
 ]
 ```
 .create-or-alter table kubernetesEvents ingestion json mapping 'ingestionMapping'
 ```
 [
   {"column":"log", "DataType":"dynamic", "Properties":{"path":"$.log.log"}},
   {"column":"timestamp","DataType":"datetime", "Properties":{"path":"$.timestamp"}},
   {"column":"tag","DataType":"string", "Properties":{"path":"$.tag"}},
   {"column":"region","DataType":"string", "Properties":{"path":"$.log.region"}},
   {"column":"cluster","DataType":"string", "Properties":{"path":"$.log.cluster"}},
   {"column":"namespace","DataType":"string", "Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"containerName", "DataType":"string", "Properties": {"path": "$log.kubernetes.container_name"}},
   {"column":"containerImage","DataType":"string", "Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"host","DataType":"string", "Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"labels","DataType":"string", "Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName","DataType":"string", "Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"environment","DataType":"string", "Properties":{"path":"$.log.environment"}},
   {"column":"count","DataType":"int", "Properties":{"path":"$.log.count"}},
   {"column":"kubeEventType","DataType":"string", "Properties":{"path":"$.log.kubeEventType"}},
   {"column":"firstSeen","DataType":"datetime", "Properties":{"path":"$.log.first_timestamp"}},
   {"column":"lastSeen","DataType":"datetime", "Properties":{"path":"$.log.last_timestamp"}},
   {"column":"message","DataType":"string", "Properties":{"path":"$.log.message"}},
   {"column":"eventNamespace", "DataType":"string", "Properties":{"path":"$.log.involved_object.namespace"}},
   {"column":"objectKind","DataType":"string", "Properties":{"path":"$.log.involved_object.kind"}},
   {"column":"objectName","DataType":"string", "Properties":{"path":"$.log.involved_object.name"}},
   {"column":"objectApiVersion","DataType":"string", "Properties":{"path":"$.log.involved_object.api_version"}},
   {"column":"objectUID","DataType":"string", "Properties":{"path":"$.log.involved_object.uid"}},
   {"column":"reason","DataType":"string", "Properties":{"path":"$.log.reason"}},
   {"column":"sourceComponent","DataType":"string", "Properties":{"path":"$.log.source.component"}},
   {"column":"unmatched","DataType":"dynamic", "Properties":{"path":"$", "Transform":"DropMappedFields" }}
 ]
 ```
 .create-or-alter table frontendContainerLogs ingestion json mapping 'ingestionMapping'
 ```
 [
   {"column":"log", "DataType":"dynamic", "Properties":{"path":"$.log.log"}},
   {"column":"timestamp", "DataType":"datetime", "Properties":{"path":"$.timestamp"}},
   {"column":"tag", "DataType":"string", "Properties":{"path":"$.tag"}},
   {"column":"region", "DataType":"string", "Properties":{"path":"$.log.region"}},
   {"column":"cluster", "DataType":"string", "Properties":{"path":"$.log.cluster"}},
   {"column":"namespace", "DataType":"string", "Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"containerName", "Properties": {"path": "$log.kubernetes.container_name"}},
   {"column":"containerImage", "DataType":"string", "Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"host", "DataType":"string", "Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"labels", "DataType":"string", "Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName", "DataType":"string", "Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"environment", "DataType":"string", "Properties":{"path":"$.log.environment"}},
   {"column":"level", "DataType":"string", "Properties":{"path":"$.log.level"}},
   {"column":"msg", "DataType":"string", "Properties":{"path":"$.log.msg"}},
   {"column":"requestId", "DataType":"string", "Properties":{"path":"$.log.request_id"}},
   {"column":"clientRequestId", "DataType":"string", "Properties":{"path":"$.log.client_request_id"}},
   {"column":"correlationRequestId", "DataType":"string", "Properties":{"path":"$.log.correlation_request_id"}},
   {"column":"subscriptionId", "Properties": {"path":"$log.subscription_id"}},
   {"column":"resourceGroup", "Properties": {"path":"$log.resource_group"}},
   {"column":"requestMethod", "DataType":"string", "Properties":{"path":"$.log.request_method"}},
   {"column":"requestPath", "DataType":"string", "Properties":{"path":"$.log.request_path"}},
   {"column":"requestProto", "DataType":"string", "Properties":{"path":"$.log.request_proto"}},
   {"column":"requestQuery", "DataType":"string", "Properties":{"path":"$.log.request_query"}},
   {"column":"requestReferer", "DataType":"string", "Properties":{"path":"$.log.request_referer"}},
   {"column":"requestRemoteAddr", "DataType":"string", "Properties":{"path":"$.log.request_remote_addr"}},
   {"column":"requestUserAgent", "DataType":"string", "Properties":{"path":"$.log.request_user_agent"}},
   {"column":"bodyReadBytes", "DataType":"int", "Properties":{"path":"$.log.body_read_bytes"}},
   {"column":"bodyWrittenBytes", "DataType":"int", "Properties":{"path":"$.log.body_written_bytes"}},
   {"column":"responseStatusCode", "DataType":"string", "Properties":{"path":"$.log.response_status_code"}},
   {"column":"duration", "DataType":"int", "Properties":{"path":"$.log.duration"}},
   {"column":"unmatched", "DataType":"dynamic", "Properties":{"path":"$", "Transform":"DropMappedFields" }}
 ]
 ```
.create-or-alter table backendContainerLogs ingestion json mapping 'ingestionMapping'
 ```
 [
   {"column":"log", "DataType":"dynamic", "Properties":{"path":"$.log.log"}},
   {"column":"timestamp", "DataType":"datetime", "Properties":{"path":"$.timestamp"}},
   {"column":"tag", "DataType":"string", "Properties":{"path":"$.tag"}},
   {"column":"region", "DataType":"string", "Properties":{"path":"$.log.region"}},
   {"column":"cluster", "DataType":"string", "Properties":{"path":"$.log.cluster"}},
   {"column":"namespace", "DataType":"string", "Properties":{"path":"$.log.kubernetes.namespace_name"}},
   {"column":"containerName", "Properties": {"path": "$log.kubernetes.container_name"}},
   {"column":"containerImage", "DataType":"string", "Properties":{"path":"$.log.kubernetes.container_image"}},
   {"column":"host", "DataType":"string", "Properties":{"path":"$.log.kubernetes.host"}},
   {"column":"labels", "DataType":"string", "Properties":{"path":"$.log.kubernetes.labels"}},
   {"column":"podName", "DataType":"string", "Properties":{"path":"$.log.kubernetes.pod_name"}},
   {"column":"environment", "DataType":"string", "Properties":{"path":"$.log.environment"}},
   {"column":"level", "DataType":"string", "Properties":{"path":"$.level"}},
   {"column":"operation", "DataType":"string", "Properties":{"path":"$.log.operation"}},
   {"column":"operationId", "DataType":"string", "Properties":{"path":"$.log.operation_id"}},
   {"column":"resourceId", "DataType":"string", "Properties":{"path":"$.log.resource_id"}},
   {"column":"internalId", "DataType":"string", "Properties":{"path":"$.log.internal_id"}},
   {"column":"clusterId", "DataType":"string", "Properties":{"path":"$.log.cluster_id"}},
   {"column":"clientRequestId", "DataType":"string", "Properties":{"path":"$.log.client_request_id"}},
   {"column":"correlationRequestId", "DataType":"string", "Properties":{"path":"$.log.correlation_request_id"}},
   {"column":"cloudErrorCode", "DataType":"string", "Properties":{"path":"$.log.cloud_error_code"}},
   {"column":"cloudErrorMessage", "DataType":"string", "Properties":{"path":"$.log.cloud_error_message"}},
   {"column":"subscriptionId", "DataType":"string", "Properties":{"path":"$.log.subscription_id"}},
   {"column":"unmatched", "DataType":"dynamic", "Properties":{"path":"$", "Transform":"DropMappedFields" }}
 ]
 ```
