defaults:
  region: {{ .ctx.region}}
  # Resourcegroups
  globalRG: global
  regionRG: hcp-underlay-{{ .ctx.region }}-{{ .ctx.regionStamp}}
  serviceClusterRG: hcp-underlay-{{ .ctx.region }}-svc-{{ .ctx.regionStamp }}
  managementClusterRG: hcp-underlay-{{ .ctx.region }}-mgmt-{{ .ctx.regionStamp }}-{{ .ctx.cxStamp }}
  imageSyncRG: hcp-underlay-{{ .ctx.region }}-imagesync-{{ .ctx.regionStamp }}

  # General AKS config
  kubernetesVersion: 1.30.5
  istioVersion: "['asm-1-22']"
  vnetAddressPrefix: "10.128.0.0/14"
  persist: true
  subnetPrefix: "10.128.8.0/21"
  podSubnetPrefix: "10.128.64.0/18"
  aksName: aro-hcp-aks

  # SVC cluster
  svcEtcdKVName: {{ azureKeyVaultName "aro-hcp-etcd" 5 .ctx.region .ctx.regionStamp }}
  svcEtcdKVSoftDelete: true
  svcPullResourceGroups: global

  # MGMT cluster specifics
  mgmtEtcdKVName: {{ azureKeyVaultName "aro-hcp-etcd" 5 .ctx.region .ctx.regionStamp .ctx.cxStamp }}
  mgmtEtcdKVSoftDelete: true

  # Frontend
  frontendCosmosDBDeploy: true
  frontendCosmosDBDisableLocalAuth: true

  # Maestro
  maestroKeyVaultName: {{ azureKeyVaultName "maestro" 5 .ctx.region .ctx.regionStamp }}
  maestroEventgridName: {{ azureEventGridName "maestro" 5 .ctx.region .ctx.regionStamp }}
  maestroEventGridMaxClientSessionsPerAuthName: '4'
  maestroCertDomain: 'selfsigned.maestro.keyvault.azure.com'
  maestroPostgresName: {{ azurePostgresName "maestro" 6 .ctx.region .ctx.regionStamp }}
  maestroPostgresServerVersion: '15'
  maestroPostgresServerStorageSizeGB: '32'
  maestroPostgresDeploy: true
  maestroPostgresPrivate: true
  maestroRestrictIstioIngress: true
  maestroConsumerName: hcp-underlay-{{ .ctx.region }}-mgmt-{{ .ctx.regionStamp }}-{{ .ctx.cxStamp }}

  # Cluster Service
  clusterServicePostgresName: {{ azurePostgresName "cs" 6 .ctx.region .ctx.regionStamp }}
  clusterServicePostgresDeploy: true
  clusterServicePostgresPrivate: true
  clusterServiceAcrRG: global

  # Image Sync
  imageSyncAcrRG: global
  imageSyncRepositories: '{registry.k8s.io/external-dns/external-dns,quay.io/acm-d/rhtap-hypershift-operator,quay.io/pstefans/controlplaneoperator,quay.io/app-sre/uhc-clusters-service}'

  # Service KeyVault
  serviceKeyVaultName: {{ azureKeyVaultName "svc-kv" 6 .ctx.region .ctx.regionStamp }}
  serviceKeyVaultRG: hcp-underlay-{{ .ctx.region }}-svc-{{ .ctx.regionStamp }}
  serviceKeyVaultRegion: {{ .ctx.region }}
  serviceKeyVaultSoftDelete: true
  serviceKeyVaultPrivate: true

  # DNS
  baseDnsZoneRG: 'global'
clouds:
  fairfax:
    defaults:
  public:
    defaults:
    environments:
      rh-dev:
        # this configuration serves as a template for for all RH DEV environment based deployments
        # the following vars need approprivate overrides:
        # - regionalDNSSubdomain
        default: &rh-dev
          # DNS
          baseDnsZoneName: 'hcp.osadev.cloud'
          # MGMTM AKS nodepools - big enough for 2 HCPs
          mgmtSystemAgentPoolMinCount: 1
          mgmtSystemAgentPoolMaxCount: 4
          mgmtSystemAgentPoolVmSize: 'Standard_D2s_v3'
          mgmtSystemAgentPoolOsDiskSizeGB: 32
          mgmtUserAgentPoolMinCount: 1
          mgmtUserAgentPoolMaxCount: 6
          mgmtUserAgentPoolVmSize: 'Standard_D4s_v3'
          mgmtUserAgentPoolOsDiskSizeGB: 100
          mgmtUserAgentPoolAzCount: 3
          # Maestro
          maestroPostgresDeploy: false
          maestroImageBase: quay.io/redhat-user-workloads/maestro-rhtap-tenant/maestro/maestro
          maestroImageTag: ea066c250a002f0cc458711945165591bc9f6d3f
          # Cluster Service
          clusterServicePostgresDeploy: false
          # Shared SVC KV
          serviceKeyVaultName: 'aro-hcp-dev-svc-kv'
          serviceKeyVaultRG: 'global'
          serviceKeyVaultRegion: 'westus3'
          serviceKeyVaultPrivate: false
          # disable soft delete on etcd KVs in DEV
          svcEtcdKVSoftDelete: false
          mgmtEtcdKVSoftDelete: false
          # ACR
          acrName: arohcpdev
          # OIDC
          oidcStorageAccountName: {{ azureStorageAccountName "arohcpoidc" 6 .ctx.region .ctx.regionStamp }}
          # DEVOPS MSI
          aroDevopsMsiId: '/subscriptions/1d3378d3-5a3f-4712-85a1-2485495dfc4b/resourceGroups/global/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aro-hcp-devops'
      integraded-dev-env:
        defaults:
          <<: *rh-dev
          # MGMTM AKS nodepools - big enough for multiple HCPs
          mgmtUserAgentPoolMinCount: 2
          mgmtUserAgentPoolMaxCount: 12
          # DNS
          regionalDNSSubdomain: '{{ .ctx.region }}'
      cs-pr-check:
        defaults:
          <<: *rh-dev
          # MGMTM AKS nodepools - big enough for multiple HCPs
          mgmtUserAgentPoolMinCount: 2
          mgmtUserAgentPoolMaxCount: 12
          # DNS
          regionalDNSSubdomain: '{{ .ctx.region }}-cs'
          # Maestro
          maestroRestrictIstioIngress: false
      personal-dev:
        defaults:
          <<: *rh-dev
          # saving money!
          persist: false
          # DNS
          regionalDNSSubdomain: '{{ .ctx.region }}-{{ uniqueString 6 .ctx.region .ctx.regionStamp }}'
