---
# Source: AcmPolicies/templates/managedclustersetbinding.yaml
# Makes the hypershift-management-clusters clusterset available in the open-cluster-management-policies namespace
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: hypershift-management-clusters
  namespace: 'open-cluster-management-policies'
spec:
  clusterSet: hypershift-management-clusters
---
# Source: AcmPolicies/templates/managedclustersetbinding.yaml
# Makes the default clusterset available for arobit namespace-resourceid-mapping policy
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: 'open-cluster-management-policies'
spec:
  clusterSet: default
---
# Source: AcmPolicies/templates/all-hosted-clusters.placement.yaml
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-hosted-clusters
  namespace: 'open-cluster-management-policies'
spec:
  clusterSets:
  - hypershift-management-clusters
---
# Source: AcmPolicies/templates/namespace-resourceid-mapping.placement.yaml
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: namespace-resourceid-mapping
  namespace: 'open-cluster-management-policies'
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/clusterset: default
          name: local-cluster
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
---
# Source: AcmPolicies/templates/default-ingress-cert.policy.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: default-ingress-cert
  namespace: 'open-cluster-management-policies'
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: all-hosted-clusters
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: default-ingress-config
---
# Source: AcmPolicies/templates/namespace-resourceid-mapping.placementbinding.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: namespace-resourceid-mapping
  namespace: 'open-cluster-management-policies'
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: namespace-resourceid-mapping
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: namespace-resourceid-mapping
---
# Source: AcmPolicies/templates/default-ingress-cert.policy.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: default-ingress-config
  namespace: 'open-cluster-management-policies'
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: default-ingress-cert
      spec:
        evaluationInterval:
          compliant: "10m"
          noncompliant: "45s"
        object-templates-raw: |
          {{hub- $cfgName := print "default-ingress-config-" .ManagedClusterName hub}}
          {{hub- $certName := print "default-ingress-tls-cert-" .ManagedClusterName hub}}
          {{hub- $ns := .PolicyMetadata.namespace hub}}
          {{hub- $disableCertificates := fromConfigMap $ns $cfgName "disable-certificates" hub}}
          {{hub- if ne $disableCertificates "true" hub}}
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: cluster-ingress-cert
                namespace: openshift-ingress
              type: kubernetes.io/tls
              data:
                tls.crt: {{hub fromSecret $ns $certName "tls.crt" hub}}
                tls.key: {{hub fromSecret $ns $certName "tls.key" hub}}
          {{hub- end hub}}
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: low
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: default-ingress-config
      spec:
        evaluationInterval:
          compliant: "10m"
          noncompliant: "45s"
        object-templates-raw: |
          {{hub $cfgName := print "default-ingress-config-" .ManagedClusterName hub}}
          {{hub- $ns := .PolicyMetadata.namespace hub}}
          {{hub- $disableCertificates := fromConfigMap $ns $cfgName "disable-certificates" hub}}
          {{hub- $eps := fromConfigMap $ns $cfgName "endpoint-publishing-strategy" hub}}
          - complianceType: musthave
            objectDefinition:
              apiVersion: operator.openshift.io/v1
              kind: IngressController
              metadata:
                name: default
                namespace: openshift-ingress-operator
              spec:
                {{hub- if ne $disableCertificates "true" hub}}
                defaultCertificate:
                  name: cluster-ingress-cert
                {{hub- end hub}}
                endpointPublishingStrategy:
                  type: LoadBalancerService
                  loadBalancer:
                    dnsManagementPolicy: 'Managed'
                    scope: {{hub if eq $eps "internal" hub}}Internal{{hub else hub}}External{{hub end hub}}
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: low
---
# Source: AcmPolicies/templates/namespace-resourceid-mapping.policy.yaml
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: namespace-resourceid-mapping
  namespace: 'open-cluster-management-policies'
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: namespace-resourceid-mapping
      spec:
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
        severity: low
        evaluationInterval:
          compliant: 2m
          noncompliant: 30s
        object-templates-raw: |
          - complianceType: mustonlyhave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: namespace-resourceid-mapping
                namespace: arobit
              data:
                {{- range (lookup "hypershift.openshift.io/v1beta1" "HostedCluster" "" "").items }}
                {{- if index .metadata.annotations "azure.microsoft.com/hcp-cluster-azure-resource-id" }}
                '{{ .metadata.namespace }}-{{ .metadata.name }}': '{{ index .metadata.annotations "azure.microsoft.com/hcp-cluster-azure-resource-id" }}'
                {{- end }}
                {{- end }}

