**
!image-environment
!internal/
!admin/
!sessiongate/
!test-integration/

# https://github.com/containers/podman/discussions/22910
# !image-environment
# !internal/go.*
# !internal/**/*.go
# !admin/Makefile
# !admin/server/go.*
# !admin/server/**/*.go
# !sessiongate/go.*
# !sessiongate/**/*.go
