FROM scratch
# this is a placeholder dockerfile that needs to exist so we can
# update the prow jobs to build and test sessiongate images
# this allows us to runt E2E tests on the PR that will introduce the real
# sessiongate component