apiVersion: v2
appVersion: 2.11.4-551
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:bc847ae30b4c850af92a1dedb6b7018eb324d9262825cb27e77220f7ad0a3aa6
type: application
version: 2.11.4-551
