{
 "title": "Backend",
 "description": "ARO HCP Backend Component",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "SLO Availability: Backend Health",
   "type": "timeseries",
   "description": "backend_health where 1 is good and 0 is bad",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (backend_health{cluster=\"$cluster\"})) / \ncount(max without(prometheus_replica) (backend_health{cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Volume: Total Backend Operations by Type",
     "type": "timeseries",
     "description": "Total Backend Operations by Type",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(type) (max without(prometheus_replica) (rate(backend_operations_total{cluster=\"$cluster\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Volume: Backend Failed Operations by Type",
     "type": "timeseries",
     "description": "Backend Failed Operations by Type",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(type) (max without(prometheus_replica) (rate(backend_failed_operations_total{cluster=\"$cluster\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency: Backend Request Latency longer than 1 second",
     "type": "timeseries",
     "description": "Ratio of Backend requests taking longer than 1 second",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by(type) (max without(prometheus_replica) (rate(backend_operations_duration_seconds_bucket{cluster=\"$cluster\",le=~\"^1(\\\\.0)?$\"}[5m])))\n/\nsum by(type) (max without(prometheus_replica) (rate(backend_operations_duration_seconds_bucket{cluster=\"$cluster\",le=\"+Inf\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency: Backend Request Latency (Histrogram 90 percentile)",
     "type": "timeseries",
     "description": "Approximated percentile value of backend latency",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le,type) (max without(prometheus_replica) (rate(backend_operations_duration_seconds_bucket{cluster=\"$cluster\"}[5m]))))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Subscriptions by State",
     "type": "timeseries",
     "description": "Backend Subscriptions by State",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "count by (state) (max without(prometheus_replica) (backend_subscriptions{cluster=\"$cluster\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Workers by Count",
     "type": "timeseries",
     "description": "Total number of active Backend workers",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "count(max without(prometheus_replica) (backend_workers{cluster=\"$cluster\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backend Leader Election State",
     "type": "timeseries",
     "description": "Backend Leader election by Cluster, Namespace, Pod",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum by (cluster,namespace,pod) (max without(prometheus_replica) (backend_leader_election_state{cluster=\"$cluster\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}