apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: backend-nodepool-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: backend-nodepool
    rules: []
