// Copyright 2025 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package customize

import (
	"fmt"
	"os"
	"path/filepath"

	"sigs.k8s.io/yaml"
)

// LoadExistingValues attempts to load an existing values.yaml file from the output directory
// Returns nil if the file doesn't exist (not an error - chart may not exist yet)
func LoadExistingValues(outputDir, chartName, valuesFileName string) (map[string]interface{}, error) {
	valuesPath := filepath.Join(outputDir, chartName, valuesFileName)

	if _, err := os.Stat(valuesPath); os.IsNotExist(err) {
		return nil, nil
	}

	data, err := os.ReadFile(valuesPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read existing values file: %w", err)
	}

	var values map[string]interface{}
	if err := yaml.Unmarshal(data, &values); err != nil {
		return nil, fmt.Errorf("failed to parse existing values file: %w", err)
	}

	return values, nil
}

// LoadScaffoldValues attempts to load a values.yaml file from the scaffold directory
// Returns nil if the file doesn't exist (not an error - scaffold may not have values)
func LoadScaffoldValues(scaffoldDir, valuesFileName string) (map[string]interface{}, error) {
	if scaffoldDir == "" {
		return nil, nil
	}

	valuesPath := filepath.Join(scaffoldDir, valuesFileName)

	if _, err := os.Stat(valuesPath); os.IsNotExist(err) {
		return nil, nil
	}

	data, err := os.ReadFile(valuesPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read scaffold values file: %w", err)
	}

	var values map[string]interface{}
	if err := yaml.Unmarshal(data, &values); err != nil {
		return nil, fmt.Errorf("failed to parse scaffold values file: %w", err)
	}

	return values, nil
}

// MergeValues merges auto-generated values with existing user values
// User values take precedence over auto-generated values
func MergeValues(autoGenerated, existing map[string]interface{}) map[string]interface{} {
	if existing == nil {
		return autoGenerated
	}
	if autoGenerated == nil {
		return existing
	}

	return MergeMaps(autoGenerated, existing)
}
