rule_files:
- certificate-rotation-prometheusRule.yaml
- certificate-rotation-slo-recordingRule.yaml
evaluation_interval: 1h
tests:
- interval: 1h
  input_series:
  - series: 'keyvault_certificate_not_before_timestamp_seconds{certificate_name="frontend", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr", prometheus_replica="agent-0"}'
    values: "-40000000+0x4"
  - series: 'keyvault_certificate_not_before_timestamp_seconds{certificate_name="frontend", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr", prometheus_replica="agent-1"}'
    values: "-40000000+0x4"
  - series: 'keyvault_certificate_not_after_timestamp_seconds{certificate_name="frontend", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr", prometheus_replica="agent-0"}'
    values: "20000000+0x4"
  - series: 'keyvault_certificate_not_after_timestamp_seconds{certificate_name="frontend", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr", prometheus_replica="agent-1"}'
    values: "20000000+0x4"
  alert_rule_test:
  - eval_time: 1h
    alertname: CertificateRotationFailure
    exp_alerts:
    - exp_labels:
        certificate_name: frontend
        cluster: cspr-westus3-svc-1
        component: certificate-rotation
        environment: cspr
        key_vault: service-kv
        region: westus3
        severity: "3"
      exp_annotations:
        summary: "westus3/service-kv: Certificate frontend rotation is overdue"
        description: "Certificate 'frontend' in Key Vault 'service-kv' (westus3) exceeded the rotation safety threshold. Current lifetime: 66.67%. Safety threshold: 65%. Expected rotation: 50%."
        runbook_url: TBD
- interval: 1h
  input_series:
  - series: 'keyvault_certificate_not_before_timestamp_seconds{certificate_name="sessiongate", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr"}'
    values: "0+0x3"
  - series: 'keyvault_certificate_not_after_timestamp_seconds{certificate_name="sessiongate", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr"}'
    values: "21600+0x3"
  alert_rule_test:
  - eval_time: 2h
    alertname: CertificateRotationFailure
- interval: 1h
  input_series:
  - series: 'keyvault_certificate_not_before_timestamp_seconds{certificate_name="admin-api", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr"}'
    values: "7200+0x3"
  - series: 'keyvault_certificate_not_after_timestamp_seconds{certificate_name="admin-api", key_vault="service-kv", region="westus3", cluster="cspr-westus3-svc-1", environment="cspr"}'
    values: "7200+0x3"
  alert_rule_test:
  - eval_time: 2h
    alertname: CertificateRotationFailure