apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hcp-test-clusters-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: hcp-test-clusters-rules
    rules:
    - alert: HCPClusterOlderThan3Hours
      expr: |
        max by (cluster, resource_id, environment) (
          time() - backend_cluster_created_time_seconds{environment=~"int|stg"}
        ) > 3 * 3600
      for: 5m
      labels:
        severity: "3"
      annotations:
        correlationId: 'IntStgClusterOlderThan3Hours{{ $labels.resource_id }}'
        description: |
          HCP cluster {{ $labels.resource_id }} in {{ $labels.environment }} on service cluster {{ $labels.cluster }} has existed for more than 3 hours.
        runbook_url: TBD
        summary: HCP in {{ $labels.environment }} is older than 3h
    - alert: ProdE2EHCPClusterOlderThan3Hours
      expr: |
        max by (cluster, resource_id, environment, subscription_id) (
          time() - backend_cluster_created_time_seconds{
            environment="prod",
            subscription_id=~"403d9de9-132b-4974-94a5-5b78bdfa191e|8d696692-794f-4cdb-ba25-9250c9e9ec4c|ec435068-e722-475f-8504-c91b72a5dc51"
          }
        ) > 3 * 3600
      for: 5m
      labels:
        severity: "3"
      annotations:
        correlationId: 'ProdE2EClusterOlderThan3Hours{{ $labels.resource_id }}'
        description: |
          Prod e2e HCP cluster {{ $labels.resource_id }} in subscription {{ $labels.subscription_id }} on service cluster {{ $labels.cluster }} has existed for more than 3 hours.
        runbook_url: TBD
        summary: Prod e2e HCP is older than 3h
