apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hcp-stuck-deletion
  namespace: monitoring
spec:
  groups:
  - name: hcp-deletion-rules
    rules:
    - alert: HCPClusterStuckDeleting
      expr: label_replace(max by (cluster_id, cluster_external_id, region, management_cluster) (cluster_deprovision_duration_seconds), "cluster", "$1", "management_cluster", "(.*)") > 7200
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Cluster stuck deleting"
        description: "Cluster {{ $labels.cluster_external_id }} has been in a deleting state for more than 2 hours. \nThis may indicate that finalizers are stuck or resources are failing to cleanup.\n"
        runbook_url: TBD
