apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kusto-logs-age-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: kusto-logs-age-rules
    rules:
    - alert: KustoLogsDataStale
      expr: kusto_logs_age_in_seconds{table!="systemdlogs"} > 3600 or kusto_logs_age_in_seconds{table="systemdlogs",cluster!~".*-svc-.*"} > 3600 or kusto_logs_age_in_seconds{table="systemdlogs",cluster=~".*-svc-.*"} > 7200
      for: 15m
      labels:
        severity: warning
      annotations:
        description: |
          Kusto log data for table {{ $labels.table }} on cluster {{ $labels.cluster }} (Kusto cluster {{ $labels.kusto_cluster }}) is stale. Check the ingestion pipeline.
        runbook_url: TBD
        summary: Kusto log data is stale for {{ $labels.table }} on {{ $labels.cluster }}.
