apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: msi-credential-refresher-prometheus-rule
  namespace: monitoring
spec:
  groups:
  - name: msi-credential-refresher
    interval: 1m
    rules:
    - alert: ClusterCredentialExpiringSoon
      expr: sum by (cluster) (increase(credential_refresher_days_until_msi_credential_expiration_bucket{le="30"}[30m])) - sum by (cluster) (increase(credential_refresher_days_until_msi_credential_expiration_bucket{le="0"}[30m])) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        description: 'Credential(s) for customer cluster monitored by {{ $labels.cluster }} are expiring in less than 30 days.'
        summary: 'Customer cluster credential expiring in less than 30 days'
        runbook_url: 'https://eng.ms/docs/cloud-ai-platform/azure-core/azure-cloud-native-and-management-platform/control-plane-bburns/azure-red-hat-openshift/azure-redhat-openshift-team-doc/troubleshooting/tsgs/credential-refresher-expiring-cert'
        correlationId: 'ClusterCredentialExpiringSoon/{{ $labels.cluster }}'
    - alert: ClusterCredentialExpired
      expr: increase(credential_refresher_days_until_msi_credential_expiration_bucket{le="0"}[30m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        description: 'Credential(s) for customer cluster monitored by {{ $labels.cluster }} have expired.'
        summary: 'Customer cluster credential has expired'
        runbook_url: 'https://eng.ms/docs/cloud-ai-platform/azure-core/azure-cloud-native-and-management-platform/control-plane-bburns/azure-red-hat-openshift/azure-redhat-openshift-team-doc/troubleshooting/tsgs/credential-refresher-expiring-cert'
        correlationId: 'ClusterCredentialExpired/{{ $labels.cluster }}'
