apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: uj-kubeapiserver-availability-alerts
  namespace: prometheus
spec:
  groups:
  - name: rp-uj-kas-availability-monitor-rules
    rules:
    - alert: UJKubeApiserverAvailability1h5m
      expr: |
        (
          1 - (hostedClusterAPI_kubeapiserver_available:sli_sum_5m / hostedClusterAPI_kubeapiserver_available:sli_count_5m)
          > (14.4 * (1 - 0.9995))
        )
        and on (name, namespace, _id, cluster)
        (
          1 - (hostedClusterAPI_kubeapiserver_available:sli_sum_1h / hostedClusterAPI_kubeapiserver_available:sli_count_1h)
          > (14.4 * (1 - 0.9995))
        )
      for: 10m
      labels:
        long_window: 1h
        short_window: 5m
        severity: critical
        slo: kas-availability
      annotations:
        summary: "[HCP] [{{ $labels.name }}] KubeAPIServer Fast Error Budget Burn (1h/5m)"
        description: |
          CID: {{ $labels._id }}
          Management Cluster: {{ $labels.cluster }}/{{ $labels.namespace }}
        runbook_url: https://aka.ms/arohcp-runbook-ujkasavailable
        correlationId: "UJKubeApiserverAvailability1h5m/{{ $labels.cluster }}/{{ $labels._id }}"
    - alert: UJKubeApiserverAvailability6h30m
      # sli_sum_6h and sli_count_6h are recording rules defined in HCPkasRecord-prometheusRule-KSM.yaml
      expr: |
        (
          1 - (hostedClusterAPI_kubeapiserver_available:sli_sum_30m / hostedClusterAPI_kubeapiserver_available:sli_count_30m)
          > (6 * (1 - 0.9995))
        )
        and on (name, namespace, _id, cluster)
        (
          1 - (hostedClusterAPI_kubeapiserver_available:sli_sum_6h / hostedClusterAPI_kubeapiserver_available:sli_count_6h)
          > (6 * (1 - 0.9995))
        )
      for: 30m
      labels:
        long_window: 6h
        short_window: 30m
        severity: warning
        slo: kas-availability
      annotations:
        summary: "[HCP] [{{ $labels.name }}] KubeAPIServer Medium Error Budget Burn (6h/30m)"
        description: |
          CID: {{ $labels._id }}
          Management Cluster: {{ $labels.cluster }}/{{ $labels.namespace }}
        runbook_url: https://aka.ms/arohcp-runbook-ujkasavailable
        correlationId: "UJKubeApiserverAvailability6h30m/{{ $labels.cluster }}/{{ $labels._id }}"
