{
 "title": "HCP KSM API SLO",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HCP API Server Availability SLO (KSM)",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "### API Server Availability SLO Distribution (KSM)\n\nHistogram representing the SLO distribution across the fleet for API Server Availability (based on KSM metrics) and percentage of total clusters meeting the SLO\n\nSLO target used for API Server Availability is 99.95%"
   }
  },
  {
   "title": "HCP API Server Availability Distribution 30 Days (KSM)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 > 99.99) or vector(0)",
     "legendFormat": "> 99.99%"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 > 99.95) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 <= 99.99)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 > 99.9) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 <= 99.95)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 > 99.5) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 <= 99.9)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 > 99) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 <= 99.5)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_30d{cluster!=\"\"}) * 100 <= 99) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HCP API Server Availability Distribution 7 Days (KSM)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 > 99.99) or vector(0)",
     "legendFormat": "> 99.99%"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 > 99.95) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 <= 99.99)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 > 99.9) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 <= 99.95)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 > 99.5) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 <= 99.9)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 > 99) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 <= 99.5)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_7d{cluster!=\"\"}) * 100 <= 99) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HCP API Server Availability Distribution 1 Day (KSM)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 > 99.99) or vector(0)",
     "legendFormat": "> 99.99%"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 > 99.95) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 <= 99.99)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 > 99.9) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 <= 99.95)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 > 99.5) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 <= 99.9)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count((avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 > 99) and (avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 <= 99.5)) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg by (namespace) (hostedClusterAPI_kubeapiserver_available:ratio_avg_1d{cluster!=\"\"}) * 100 <= 99) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}