apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ama-metrics-serviceaccount-role
  namespace: maestro
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["maestro-agent-metrics-sa-token"]
    verbs: ["get"]