apiVersion: v1
kind: Secret
metadata:
  name: maestro-agent-metrics-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: ama-metrics-serviceaccount
type: kubernetes.io/service-account-token