apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maestro-agent
  name: maestro-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: maestro-agent
  template:
    metadata:
      labels:
        app: maestro-agent
      annotations:
        checksum/credsstore: {{ include (print $.Template.BasePath "/maestro.secretproviderclass.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/maestro.secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx-proxy
        image: quay.io/rh_ee_tschneid/nginx:latest
        ports:
        - containerPort: 8444
          name: metrics-proxy
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: ssl-certificates
          mountPath: /etc/nginx/certs
        - name: logs
          mountPath: /var/log/nginx
        command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
      - command:
        - /usr/local/bin/maestro
        - agent
        - --consumer-name={{ .Values.consumerName }}
        - --workload-source-driver=mqtt
        - --workload-source-config=/secrets/maestro/config.yaml
        - --cloudevents-client-id={{ .Values.consumerName }}-work-agent
        image: "{{ .Values.image.base }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443 
          name: metrics 
          protocol: TCP
        name: maestro-agent
        volumeMounts:
        - mountPath: /secrets/maestro
          name: maestro
        - mountPath: /secrets/mqtt-creds
          name: mqtt-creds
          readOnly: true
      serviceAccountName: maestro
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: ssl-certificates
        secret:
          secretName: nginx-ssl
      - name: logs
        emptyDir: {}
      - name: maestro
        secret:
          secretName: maestro
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: maestro
        name: mqtt-creds
