---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maestro-agent-metrics-access-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maestro-agent-metrics-access
subjects:
  - kind: ServiceAccount
    name: maestro-agent-metrics-sa
    namespace: maestro