{
 "title": "AKS Performance",
 "description": "Performance dashboard for AKS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "_worker_node",
    "label": "Worker",
    "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\",namespace!=\"(cluster-density.*|node-density-.*)\"}, namespace)"
   },
   {
    "name": "block_device",
    "label": "Block device",
    "query": "label_values(node_disk_written_bytes_total{cluster=\"$cluster\"},device)"
   },
   { "name": "interval", "label": "interval", "query": "2m,3m,4m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Kubelet",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 0
   },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sum of all worker CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{cluster=\"$cluster\",job=~\".*\",instance=~\".*user.*\"}[$interval]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Top 10 Kubelet CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,irate(process_cpu_seconds_total{cluster=\"$cluster\",job=\"kubelet\"}[$interval])*100)",
       "legendFormat": "kubelet - {{instance}}"
      }
     ]
    },
    {
     "title": "Top 10 Kubelet memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10,process_resident_memory_bytes{cluster=\"$cluster\",job=\"kubelet\"})",
       "legendFormat": "kubelet - {{instance}}"
      }
     ]
    },
    {
     "title": "Containerd CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",id=\"/system.slice/containerd.service\"}[2m])*100) by (container, pod, instance)) > 0",
       "legendFormat": "Containerd - {{instance}}"
      }
     ]
    },
    {
     "title": "Containerd memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\",id=\"/system.slice/containerd.service\"}) by (container, pod, instance)",
       "legendFormat": "Containerd - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 1
   },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Node Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=\"$cluster\",})",
       "legendFormat": "Number of nodes"
      },
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",status=\"true\"}) by (condition) > 0",
       "legendFormat": "Node: {{ condition }}"
      }
     ]
    },
    {
     "title": "Current namespace Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_namespace_status_phase{cluster=\"$cluster\"}) by (phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Current Pod Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\"}) by (phase) > 0",
       "legendFormat": "{{ phase}} Pods"
      }
     ]
    },
    {
     "title": "Number of nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=\"$cluster\"})",
       "legendFormat": "Number of nodes"
      },
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$cluster\",status=\"true\"}) by (condition) > 0",
       "legendFormat": "Node: {{ condition }}"
      }
     ]
    },
    {
     "title": "Namespace count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_namespace_status_phase{cluster=\"$cluster\"}) by (phase) > 0",
       "legendFormat": "{{ phase }} namespaces"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\"}) by (phase)",
       "legendFormat": "{{phase}} pods"
      }
     ]
    },
    {
     "title": "Secret & configmap count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_secret_info{cluster=\"$cluster\"})",
       "legendFormat": "secrets"
      },
      {
       "expr": "count(kube_configmap_info{cluster=\"$cluster\"})",
       "legendFormat": "Configmaps"
      }
     ]
    },
    {
     "title": "Deployment count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_deployment_labels{cluster=\"$cluster\"})",
       "legendFormat": "Deployments"
      }
     ]
    },
    {
     "title": "Services count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_service_info{cluster=\"$cluster\"})",
       "legendFormat": "Services"
      }
     ]
    },
    {
     "title": "Pod Distribution",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kubelet_running_pods{cluster=\"$cluster\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Pod Distribution Heat Map",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(kubelet_running_pods{cluster=\"$cluster\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Hypershift Shared Ingress usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"hypershift-sharedingress\", container!=\"\"}[$interval])*100)",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    },
    {
     "title": "Hypershift Shared Ingress RSS usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(30, container_memory_rss{cluster=\"$cluster\",namespace=\"hypershift-sharedingress\", container!=\"\"})",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 container RSS (Excluding AMA)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(30, container_memory_rss{cluster=\"$cluster\",namespace!=\"\",container!=\"POD\",pod!~\".*ama*\",name!=\"\"})",
       "legendFormat": "{{ namespace }} - {{ pod }}"
      }
     ]
    },
    {
     "title": "Top 10 container CPU(Excluding AMA)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace!=\"\",container!=\"POD\",pod!~\".*ama*\",name!=\"\"}[$interval])*100)",
       "legendFormat": "{{ namespace }} - {{ pod }}"
      }
     ]
    },
    {
     "title": "Top 10 Prometheus Collector container RSS ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{cluster=\"$cluster\",namespace!=\"\",container!=\"POD\",pod=~\".*ama*\",name!=\"\"})",
       "legendFormat": "{{ namespace }} - {{ pod }}"
      }
     ]
    },
    {
     "title": "Top 10 Prometheus Collector container CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace!=\"\",container!=\"POD\",pod=~\".*ama*\",name!=\"\"}[$interval])*100)",
       "legendFormat": "{{ namespace }} - {{ pod }}"
      }
     ]
    },
    {
     "title": "container RSS system.slice",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(container_memory_rss{cluster=\"$cluster\",id=~\"/system.slice.*\"})",
       "legendFormat": "system.slice - {{ instance }}"
      }
     ]
    },
    {
     "title": "Goroutines count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10, sum(go_goroutines{cluster=\"$cluster\"}) by (job,instance))",
       "legendFormat": "{{ job }} - {{ instance }}"
      }
     ]
    },
    {
     "title": "Sum of HCP app CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container!=\"POD\",name!=\"\",namespace=~\"ocm.*\",instance=~\".*user.*\"}[$interval])) by (instance) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Sum of non HCP CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container!=\"POD\",name!=\"\",namespace!~\"ocm.*\",instance=~\".*user.*\"}[$interval])) by (instance) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Sum of HCP app memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\",container!=\"POD\",name!=\"\",instance=~\".*user.*\",namespace=~\"ocm.*\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Sum of non HCP  memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\",container!=\"POD\",name!=\"\",instance=~\".*user.*\",namespace!~\"ocm.*\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "PV Usage in Byters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{ namespace }}-{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PV Usage in %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=\"$cluster\"}/kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{ namespace }}-{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $_worker_node",
   "type": "row",
   "gridPos": {
    "gridPos": { "h": 8, "w": 0, "x": 0, "y": 1 },
    "h": 1,
    "w": 24,
    "x": 0,
    "y": 2
   },
   "repeat": "_worker_node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Basic: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance, mode)(irate(node_cpu_seconds_total{cluster=\"$cluster\",instance=~\"$_worker_node\",job=~\".*\"}[$interval])) * 100",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "System Memory: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Active_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Cached_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"} + node_memory_Buffers_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"} + node_memory_Buffers_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"} +  node_memory_Cached_bytes{cluster=\"$cluster\",instance=~\"$_worker_node\"}))",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Disk throughput: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{cluster=\"$cluster\",device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{cluster=\"$cluster\",device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{cluster=\"$cluster\",device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{cluster=\"$cluster\",device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Network Utilization: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\",instance=~\"$_worker_node\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\",instance=~\"$_worker_node\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network Packets: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{cluster=\"$cluster\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{cluster=\"$cluster\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets drop: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, rate(node_network_receive_drop_total{cluster=\"$cluster\",instance=~\"$_worker_node\"}[$interval]))",
       "legendFormat": "rx-drop-{{ device }}"
      },
      {
       "expr": "topk(10,rate(node_network_transmit_drop_total{cluster=\"$cluster\",instance=~\"$_worker_node\"}[$interval]))",
       "legendFormat": "tx-drop-{{ device }}"
      }
     ]
    },
    {
     "title": "Conntrack stats: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{cluster=\"$cluster\",instance=~\"$_worker_node\"}",
       "legendFormat": "conntrack_entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{cluster=\"$cluster\",instance=~\"$_worker_node\"}",
       "legendFormat": "conntrack_limit"
      }
     ]
    },
    {
     "title": "Top 10 HCP container CPU: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container!=\"POD\",name!=\"\",instance=~\"$_worker_node\",namespace=~\"ocm.*\"}[$interval])) by (pod,container,namespace,name,service) * 100",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 non HCP container CPU: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container!=\"POD\",name!=\"\",instance=~\"$_worker_node\",namespace!~\"ocm.*\",namespace=~\"$namespace\"}[$interval])) by (pod,container,namespace,name,service) * 100",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 HCP container RSS: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{cluster=\"$cluster\",container!=\"POD\",name!=\"\",instance=~\"$_worker_node\",namespace=~\"ocm.*\",namespace=~\"$namespace\"})",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 non HCP container RSS: $_worker_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{cluster=\"$cluster\",container!=\"POD\",name!=\"\",instance=~\"$_worker_node\",namespace!~\"ocm.*\",namespace=~\"$namespace\"})",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    }
   ]
  }
 ]
}