{
 "title": "ARO HCP Cluster Service SLOs",
 "description": "ARO HCP Cluster Service Component",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } }
  ]
 },
 "panels": [
  { "title": "Availability SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO Definition: Availability",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "Over a 28-day rolling window, 99% of API requests will return with a successful status, where successful is defined as a non-5xx HTTP response code (which includes timeout errors that return 504)."
   }
  },
  {
   "title": "Availability",
   "type": "stat",
   "description": "Percentage of CS API is available (not returning 5xx Internal Service Errors).",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code!~\"5..\", service=\"clusters-service-metrics\"}[28d]))) / sum((max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[28d]))))) or vector(1))",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Availability - Error Budget Burn Rate (28d)",
   "type": "timeseries",
   "description": "**Purpose:** This graph displays the Error Budget Burn Rate over the past 28 days to monitor the long-term reliability of Clusters Service Availability.\n\n---\n\n### **Understanding Long-Term Burn Rate Recovery**\n\nThe 28-day Burn Rate is a rolling cumulative metric. After an incident, even if short-term performance looks good, the long-term Burn Rate may remain consistently high and recover slowly. This typically happens because:\n\n1.  **Old Good Data Ages Out:** As time passes, older, well-performing data rolls out of the 28-day window, and new data might not fully compensate for its positive contribution.\n2.  **Traffic Impact:** If traffic (RPS) is high at the time of the incident, problematic requests will constitute a larger proportion of the rolling window.  In such scenarios, error dilution becomes difficult, extending the Burn Rate's recovery period, and this impact is further amplified for services with low sample volume and potentially high incident density.\n3.  **Limited Dilution Capacity:** The weight and volume of newly added healthy requests may be insufficient to quickly dilute historical errors, slowing down the Burn Rate's decrease.",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code!~\"5..\", service=\"clusters-service-metrics\"}[28d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[28d]))))) / (1 - 0.99)) or vector(0)",
     "legendFormat": "Error budget burn rate"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion (99%)",
   "type": "gauge",
   "description": "An error budget is the maximum amount of allowable errors a service can incur within its SLO window before it is considered out of compliance with its reliability target. \n\nThe Error budget exhaustion shows how much allowable errors the service has used. \n\nFor example, we have API Availability 99% target value, that means the error budget is 1%. Suppose that actual value is 99.7%, that means the error budget exhaustion is 30%",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code!~\"5..\", service=\"clusters-service-metrics\"}[28d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[28d]))))) / (1 - 0.99)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Burn Rate Alert (5m & 1h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 5 minutes and last 1 hour remains at 13.44 or greater.\n\nThis threshold means consuming:\n-  2% of the error budget in 1h \n-  100% in approximately 2 days",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code=~\"5..\", service=\"clusters-service-metrics\"}[5m]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[5m]))))) / (1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 5m"
    },
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code=~\"5..\", service=\"clusters-service-metrics\"}[1h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[1h]))))) / (1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 1h"
    }
   ]
  },
  {
   "title": "Critical Burn Rate Alert (30m & 6h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 30 minutes and last 6 hours remains at 5.6 or greater.\n\nThis threshold means consuming:\n-  5% of the error budget in 6h \n-  100% in 5 days",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code=~\"5..\", service=\"clusters-service-metrics\"}[30m]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[30m]))))) / (1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 30m"
    },
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code=~\"5..\", service=\"clusters-service-metrics\"}[6h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[6h]))))) / (1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 6h"
    }
   ]
  },
  {
   "title": "Warning Burn Rate Alert (2h & 1d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 2 hours and last 1 days remains at 2.8 or greater. \n\nThis threshold means consuming:\n-  10% of the error budget in 1 day \n-  100% in approximately 10 days",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", code=~\"5..\", service=\"clusters-service-metrics\"}[2h])))\n/\nsum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[2h])))))/(1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 2h"
    },
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", code=~\"5..\", service=\"clusters-service-metrics\"}[1d])))\n/\nsum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[1d])))))/(1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 1d"
    }
   ]
  },
  {
   "title": "Warning Burn Rate Alert (6h & 3d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 6 hours and last 3 days remains at 0.934 or greater.\n\nThis threshold means consuming:\n-  10% of the error budget in 3 days \n-  100% in approximately 26 days",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code=~\"5..\", service=\"clusters-service-metrics\"}[6h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[6h]))))) / (1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 6h"
    },
    {
     "expr": "clamp_min((((sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\",code=~\"5..\", service=\"clusters-service-metrics\"}[3d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\"}[3d]))))) / (1 - 0.99)) or vector(0), 0)",
     "legendFormat": "Burn Rate - 3d"
    }
   ]
  },
  {
   "title": "SLO Definition: P90 Latency",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 26 },
   "options": {
    "content": "Over a 28-day rolling window, 90% of successful API calls (determined as a non-5xx HTTP response) will complete within 100ms."
   }
  },
  {
   "title": "P90 Latency (< 100ms)",
   "type": "stat",
   "description": "Percentage of requests to operate cluster are successful with a latency of <100ms",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[28d])))\n/\nsum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[28d]))))",
     "legendFormat": "P90 Latency"
    }
   ]
  },
  {
   "title": "P90 Latency - Error Budget Burn Rate (28d)",
   "type": "timeseries",
   "description": "**Purpose:** This graph displays the Error Budget Burn Rate over the past 28 days to monitor the long-term reliability of Clusters Service P90 Latency.\n\n---\n\n### **Understanding Long-Term Burn Rate Recovery**\n\nThe 28-day Burn Rate is a rolling cumulative metric. After an incident, even if short-term performance looks good, the long-term Burn Rate may remain consistently high and recover slowly. This typically happens because:\n\n1.  **Old Good Data Ages Out:** As time passes, older, well-performing data rolls out of the 28-day window, and new data might not fully compensate for its positive contribution.\n2.  **Traffic Impact:** If traffic (RPS) is high at the time of the incident, problematic requests will constitute a larger proportion of the rolling window.  In such scenarios, error dilution becomes difficult, extending the Burn Rate's recovery period, and this impact is further amplified for services with low sample volume and potentially high incident density.\n3.  **Limited Dilution Capacity:** The weight and volume of newly added healthy requests may be insufficient to quickly dilute historical errors, slowing down the Burn Rate's decrease.",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[28d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[28d])))))/(1 - 0.90)",
     "legendFormat": "P90 Error budget burn rate"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion (90%)",
   "type": "gauge",
   "description": "An error budget is the maximum amount of allowable errors a service can incur within its SLO window before it is considered out of compliance with its reliability target. \n\nThe Error budget exhaustion shows how much allowable errors the service has used. \n\nFor example, we have P90 API Latency 90% target value, that means the error budget is 10%. Suppose that actual value is 95%, that means the error budget exhaustion is 50%",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[28d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[28d])))))/(1 - 0.90)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Critical Burn Rate Alert (5m & 1h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 5 minutes and last 1 hour remains at 13.44 or greater.\n\nThis threshold means consuming:\n-  2% of the error budget in 1h \n-  100% in approximately 2 days",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[5m]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[5m]))))) / (1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 5m"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[1h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[1h])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 1h"
    }
   ]
  },
  {
   "title": "P90 Critical Burn Rate Alert (30m & 6h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 30 minutes and last 6 hours remains at 5.6 or greater.\n\nThis threshold means consuming:\n-  5% of the error budget in 6h \n-  100% in 5 days",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[30m]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[30m])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 30m"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[6h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[6h])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 6h"
    }
   ]
  },
  {
   "title": "P90 Warning Burn Rate Alert (2h & 1d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 2 hours and last 1 days remains at 2.8 or greater. \n\n\nThis threshold means consuming:\n-  10% of the error budget in 1 day \n-  100% in approximately 10 days",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[2h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[2h])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 2h"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[1d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[1d])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 1d"
    }
   ]
  },
  {
   "title": "P90 Warning Burn Rate Alert (6h & 3d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 6 hours and last 3 days remains at 0.934 or greater.\n\nThis threshold means consuming:\n-  10% of the error budget in 3 days \n-  100% in approximately 26 days",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[6h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[6h])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 6h"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"0.1\", code!~\"5..\"}[3d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[3d])))))/(1 - 0.90), 0)",
     "legendFormat": "P90 Burn Rate - 3d"
    }
   ]
  },
  { "title": "Latency SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "SLO Definition: P99 Latency",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 14 },
   "options": {
    "content": "Over a 28-day rolling window, 99% of successful API calls (determined as a non-5xx HTTP response) will complete within 1s."
   }
  },
  {
   "title": "P99 Latency (< 1s)",
   "type": "stat",
   "description": "Percentage of requests to operate cluster are successful with a latency of <1s",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[28d])))\n/\nsum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[28d]))))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency - Error Budget Burn Rate (28d)",
   "type": "timeseries",
   "description": "**Purpose:** This graph displays the Error Budget Burn Rate over the past 28 days to monitor the long-term reliability of Clusters Service P99 Latency.\n\n---\n\n### **Understanding Long-Term Burn Rate Recovery**\n\nThe 28-day Burn Rate is a rolling cumulative metric. After an incident, even if short-term performance looks good, the long-term Burn Rate may remain consistently high and recover slowly. This typically happens because:\n\n1.  **Old Good Data Ages Out:** As time passes, older, well-performing data rolls out of the 28-day window, and new data might not fully compensate for its positive contribution.\n2.  **Traffic Impact:** If traffic (RPS) is high at the time of the incident, problematic requests will constitute a larger proportion of the rolling window.  In such scenarios, error dilution becomes difficult, extending the Burn Rate's recovery period, and this impact is further amplified for services with low sample volume and potentially high incident density.\n3.  **Limited Dilution Capacity:** The weight and volume of newly added healthy requests may be insufficient to quickly dilute historical errors, slowing down the Burn Rate's decrease.",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[28d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[28d])))))/(1 - 0.99)",
     "legendFormat": "P99 Error budget burn rate"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion (99%)",
   "type": "gauge",
   "description": "An error budget is the maximum amount of allowable errors a service can incur within its SLO window before it is considered out of compliance with its reliability target. \n\nThe Error budget exhaustion shows how much allowable errors the service has used. \n\nFor example, we have API Availability 99% target value, that means the error budget is 1%. Suppose that actual value is 99.7%, that means the error budget exhaustion is 30%",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[28d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[28d])))))/(1 - 0.99)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Critical Burn Rate Alert (5m & 1h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 5 minutes and last 1 hour remains at 13.44 or greater.\n\nThis threshold means consuming:\n-  2% of the error budget in 1h \n-  100% in approximately 2 days",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[5m]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[5m]))))) / (1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 5m"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[1h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[1h])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 1h"
    }
   ]
  },
  {
   "title": "P99 Critical Burn Rate Alert (30m & 6h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 30 minutes and last 6 hours remains at 5.6 or greater.\n\nThis threshold means consuming:\n-  5% of the error budget in 6h \n-  100% in 5 days",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[30m]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[30m])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 30m"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[6h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[6h])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 6h"
    }
   ]
  },
  {
   "title": "P99 Warning Burn Rate Alert (2h & 1d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 2 hours and last 1 days remains at 2.8 or greater. \n\n\nThis threshold means consuming:\n-  10% of the error budget in 1 day \n-  100% in approximately 10 days",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[2h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[2h])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 2h"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[1d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[1d])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 1d"
    }
   ]
  },
  {
   "title": "P99 Warning Burn Rate Alert (6h & 3d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 6 hours and last 3 days remains at 0.934 or greater.\n\nThis threshold means consuming:\n-  10% of the error budget in 3 days \n-  100% in approximately 26 days",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[6h]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[6h])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 6h"
    },
    {
     "expr": "clamp_min((1 - (sum(max without(prometheus_replica) (rate(api_inbound_request_duration_bucket{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", le=\"1.0\", code!~\"5..\"}[3d]))) / sum(max without(prometheus_replica) (rate(api_inbound_request_count{cluster=\"$cluster\", namespace=\"clusters-service\", service=\"clusters-service-metrics\", code!~\"5..\"}[3d])))))/(1 - 0.99), 0)",
     "legendFormat": "Burn Rate - 3d"
    }
   ]
  }
 ]
}