apiVersion: v1
kind: Service
metadata:
  name: {{ include "cihealth.postgresName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cihealth.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "cihealth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
