apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cihealth.postgresPvcName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cihealth.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    {{- toYaml .Values.postgres.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
