apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "cihealth.secretProviderClassName" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  provider: azure
  parameters:
    clientID: '{{ if .Values.secretProvider.msiClientId }}{{ .Values.secretProvider.msiClientId }}{{ else }}{{ .Values.msiClientId }}{{ end }}'
    tenantId: "{{ .Values.secretProvider.tenantId }}"
    keyvaultName: "{{ .Values.secretProvider.keyVault }}"
    objects: |
      array:
        - |
          objectName: "{{ .Values.postgres.keyVaultSecretNames.username }}"
          objectAlias: "postgres-username"
          objectType: secret
        - |
          objectName: "{{ .Values.postgres.keyVaultSecretNames.password }}"
          objectAlias: "postgres-password"
          objectType: secret
        - |
          objectName: "{{ .Values.postgres.keyVaultSecretNames.database }}"
          objectAlias: "postgres-database"
          objectType: secret
    usePodIdentity: "false"
