# Global Docker image parameters
##
# imagePullSecrets:
#   - linuxgeneva-microsoft
forwarder:
  geoShortId: "{{ .azureGeoShortId }}"
  azureCloudEnvironmentName: "{{ .cloudEnvironmentName }}"
  clusterType: "svc"
  environment: "{{ .arobit.kusto.environmentName }}"
  clusterName: "{{ .svc.aks.name }}"
  region: "{{ .region }}"
  ## Enable forwarder daemonset
  ##
  dynamicConfig: false
  ## K8s Security Context for forwarder pods
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    enabled: true
    runAsUser: 65532
    runAsGroup: 65532
  ## Pods Service Account
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  serviceAccountName: arobit-forwarder
  fluentbit:
    ## Fluent Bit image version
    ##
    image:
      registry: "{{ .arobit.forwarder.image.registry }}"
      repository: "{{ .arobit.forwarder.image.repository }}"
      digest: "{{ .arobit.forwarder.image.digest }}"
      pullPolicy: IfNotPresent
  kusto:
    serviceLogsDatabase: {{ .kusto.serviceLogsDatabase }}
    hostedControlPlaneLogsDatabase: {{ .kusto.hostedControlPlaneLogsDatabase }}
    enabled: {{ .arobit.kusto.enabled }}
    ingestionEndpoint: "__kustoDataIngestionUri__"
  msiClientId: "__msiClientId__"
  tenantId: "__tenantId__"
  secretProvider:
    keyVault: "{{ .serviceKeyVault.name }}"
