{
 "title": "Frontend",
 "description": "ARO HCP Frontend Component",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "SLO Availability: Frontend Health",
   "type": "timeseries",
   "description": "frontend_health where 1 is good and 0 is bad",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (frontend_health{cluster=\"$cluster\"})) / \ncount(max without(prometheus_replica) (frontend_healt{cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend HTTP Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Request Volume: Total Frontend Requests",
     "type": "timeseries",
     "description": "Good for capacity planning and detecting usage anomalies.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (rate(frontend_http_requests_total{cluster=\"$cluster\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Availability: Frontend Request Success Rate",
     "type": "timeseries",
     "description": "Measure the percentage of successful API requests (non-5xx)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (rate(frontend_http_requests_total{code!~\"5..\",cluster=\"$cluster\"}[5m])))\n/\nsum(max without(prometheus_replica) (rate(frontend_http_requests_total{cluster=\"$cluster\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Error Rate: Frontend Errors (5xx)",
     "type": "timeseries",
     "description": "Direct measure of 5xx responses over time.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(max without (prometheus_replica) (rate(frontend_http_requests_total{code=~\"5..\", cluster=\"$cluster\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Latency: Frontend Request Latency",
     "type": "timeseries",
     "description": "Ratio of Frontend's requests taking less than 1 second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by(code,method) (max without(prometheus_replica) (rate(frontend_http_requests_duration_seconds_bucket{le=~\"^1(\\\\.0)?$\"}[5m])))\n/\nsum by(code,method) (max without(prometheus_replica) (rate(frontend_http_requests_duration_seconds_bucket{le=\"+Inf\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Cluster Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Request Volume: Total Frontend Cluster Service Client Requests by code,method,path",
     "type": "timeseries",
     "description": "Good for capacity planning and detecting usage anomalies.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (rate(frontend_clusters_service_client_request_count{cluster=\"$cluster\"}[5m]))) by (code, method, path)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " SLO Availability: Frontend Cluster Service Client Request Success Rate by code,method,path",
     "type": "timeseries",
     "description": "Measure the percentage of successful API requests (non-5xx)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (rate(frontend_clusters_service_client_request_count{code!~\"5..\", cluster=\"$cluster\"}[5m]))) by (code, method, path)\n/\nsum(max without(prometheus_replica) (rate(frontend_clusters_service_client_request_count{cluster=\"$cluster\"}[5m]))) by (code, method, path)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Error Rate: Frontend Cluster Service Client Request Errors (5xx) by code,method,path",
     "type": "timeseries",
     "description": "Direct measure of 5xx responses over time.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (rate(frontend_clusters_service_client_request_count{code=~\"5..\", cluster=\"$cluster\"}[5m]))) by (code, method, path)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Latency: Frontend Cluster Service Client Request Latency by code,method,path",
     "type": "timeseries",
     "description": "Ratio of Frontend's Cluster Service requests taking less than 1 second",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by(code,method,path) (max without(prometheus_replica) (rate(frontend_clusters_service_client_request_duration_bucket{le=~\"^1(\\\\.0)?$\"}[5m])))\n/\nsum by(code,method,path) (max without(prometheus_replica) (rate(frontend_clusters_service_client_request_duration_bucket{le=\"+Inf\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLI frontend_clusters_service_client_request_duration_count by code,method,path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by (code,method,path) (rate(frontend_clusters_service_client_request_duration_count{cluster=\"$cluster\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Subscription Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLI frontend_subscription_collector_last_success_timestamp_seconds",
     "type": "timeseries",
     "description": "frontend_subscription_collector_last_success_timestamp_seconds is intended to be used in conjunction with the time() function to detect a drift in metric collection",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "time() - max by(namespace,pod,cluster) (frontend_subscription_collector_last_success_timestamp_seconds{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Error: Frontend Failed Syncs",
     "type": "timeseries",
     "description": "Failed syncs can be compared against the total number of operations",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by(pod,namespace,cluster) (max without(prometheus_replica) (rate(frontend_subscription_collector_failed_syncs_total{cluster=\"$cluster\"}[5m])))\n/\nsum by(pod,namespace,cluster) (max without(prometheus_replica) (rate(frontend_subscription_collector_syncs_total{cluster=\"$cluster\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Lifecycle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLI frontend_lifecycle_state",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "max by(cluster,location,namespace,state,subscription_id) (frontend_lifecycle_state{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLI frontend_lifecycle_last_update_timestamp_seconds",
     "type": "timeseries",
     "description": "frontend_lifecycle_last_update_timestamp_seconds is intended to be used in conjunction with the time() function to detect a drift in metric collection.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "time() - max by(namespace,pod,cluster) (frontend_lifecycle_last_update_timestamp_seconds{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}