apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sessiongate
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: sessiongate
