apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-exporter-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cert-exporter
data:
  config.yaml: |
    server:
      listen: :9793
    metrics:
      exposeNotBefore: true
    sources:
      - kind: secret
        secrets:
          - type: kubernetes.io/tls
            key: tls.crt
