apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cert-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-exporter
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cert-exporter
        image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}'
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
        args:
        - --config=/etc/x509-certificate-exporter/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/x509-certificate-exporter
          readOnly: true
        ports:
        - name: metrics
          containerPort: 9793
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: cert-exporter-config
