apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbacController.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cert-exporter-rbac-controller
automountServiceAccountToken: true