apiVersion: v1
kind: Service
metadata:
  name: cert-exporter-rbac-controller-metrics
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: cert-exporter-rbac-controller
    port: metrics
spec:
  ports:
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: healthz
  selector:
    app.kubernetes.io/name: cert-exporter-rbac-controller
