// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035 "github.com/Azure/ARO-HCP/internal/graph/graphsdk/models"
)

type GroupBasedSubjectSet struct {
    i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.SubjectSet
}
// NewGroupBasedSubjectSet instantiates a new GroupBasedSubjectSet and sets the default values.
func NewGroupBasedSubjectSet()(*GroupBasedSubjectSet) {
    m := &GroupBasedSubjectSet{
        SubjectSet: *i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.NewSubjectSet(),
    }
    odataTypeValue := "#microsoft.graph.identityGovernance.groupBasedSubjectSet"
    m.SetOdataType(&odataTypeValue)
    return m
}
// CreateGroupBasedSubjectSetFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGroupBasedSubjectSetFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGroupBasedSubjectSet(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GroupBasedSubjectSet) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.SubjectSet.GetFieldDeserializers()
    res["groups"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.CreateGroupFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable)
                }
            }
            m.SetGroups(res)
        }
        return nil
    }
    return res
}
// GetGroups gets the groups property value. The groups property
// returns a []Groupable when successful
func (m *GroupBasedSubjectSet) GetGroups()([]i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable) {
    val, err := m.GetBackingStore().Get("groups")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable)
    }
    return nil
}
// Serialize serializes information the current object
func (m *GroupBasedSubjectSet) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.SubjectSet.Serialize(writer)
    if err != nil {
        return err
    }
    if m.GetGroups() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetGroups()))
        for i, v := range m.GetGroups() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("groups", cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetGroups sets the groups property value. The groups property
func (m *GroupBasedSubjectSet) SetGroups(value []i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable)() {
    err := m.GetBackingStore().Set("groups", value)
    if err != nil {
        panic(err)
    }
}
type GroupBasedSubjectSetable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.SubjectSetable
    GetGroups()([]i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable)
    SetGroups(value []i1064077c0deed3e13037469d51458ffc82d2db75e239cd9605f39aaa91186035.Groupable)()
}
