{
 "title": "Velero",
 "description": "Velero Backup and Restore Monitoring",
 "tags": [
  "velero",
  "backup"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total{cluster=~\"$cluster\"},schedule)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backup Health Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backups",
   "type": "stat",
   "description": "Total number of backups - and number of backup attempts in the selected time range",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\"}) == 1)",
     "legendFormat": "Backup CRs total"
    },
    {
     "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))))",
     "legendFormat": "Attempts"
    }
   ]
  },
  {
   "title": "Attempts",
   "type": "stat",
   "description": "Total number backup deletion attempts",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_deletion_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))))",
     "legendFormat": "Backup Deletions"
    },
    {
     "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_success_total{cluster=~\"$cluster\"}[$__range]))) + sum(max without(prometheus_replica) (increase(podvolume_data_upload_failure_total{cluster=~\"$cluster\"}[$__range]))))",
     "legendFormat": "Data Uploads (all schedules)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 }, "options": { "content": "Schedules with Failed Backups" } },
  {
   "title": "Backup Schedule Last Status",
   "type": "table",
   "description": "Last backup status per schedule (1=Success, 0=Failure)",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max without(prometheus_replica) (velero_backup_last_status{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"})",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max without(prometheus_replica) (velero_backup_last_status{cluster=~\"$cluster\", schedule=~\"$schedule\"}) == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Rates",
   "type": "piechart",
   "description": "Combined backup success & failure rate as a fraction of attempts, broken into Success, Failure, Partial Failure and Validation Failure. Bar segments stack to the total failure rate.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_partial_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Partial Failure"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_validation_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Validation Failure"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "description": "Ratio of successful backups to total backup attempts",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)"
    }
   ]
  },
  {
   "title": "Success Rates",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_deletion_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_deletion_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Backup Deletion"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(podvolume_data_upload_success_total{cluster=~\"$cluster\"}[$__range]))) / ((sum(max without(prometheus_replica) (increase(podvolume_data_upload_success_total{cluster=~\"$cluster\"}[$__range]))) + sum(max without(prometheus_replica) (increase(podvolume_data_upload_failure_total{cluster=~\"$cluster\"}[$__range])))) > 0)",
     "legendFormat": "Data Upload (all schedules)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "options": {
    "content": "Schedules with >48 Hours Since Last Backup"
   }
  },
  {
   "title": "Hours Since Last Backup",
   "type": "table",
   "description": "Hours since the last successful backup per schedule. Green < 24h, Orange < 48h, Red >= 48h.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - max without(prometheus_replica) (velero_backup_last_successful_timestamp{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"})) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  count((time() - max without(prometheus_replica) (velero_backup_last_successful_timestamp{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"})) > 48*3600 ) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Failure Rates",
   "type": "gauge",
   "description": "Combined backupfailure rate as a fraction of attempts, broken into Failure, Partial Failure and Validation Failure.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_partial_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Partial Failure"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_validation_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Validation Failure"
    }
   ]
  },
  {
   "title": "Failure Rates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max without(prometheus_replica) (increase(velero_backup_deletion_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_backup_deletion_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
     "legendFormat": "Backup Deletion"
    },
    {
     "expr": "sum(max without(prometheus_replica) (increase(podvolume_data_upload_failure_total{cluster=~\"$cluster\"}[$__range]))) / ((sum(max without(prometheus_replica) (increase(podvolume_data_upload_success_total{cluster=~\"$cluster\"}[$__range]))) + sum(max without(prometheus_replica) (increase(podvolume_data_upload_failure_total{cluster=~\"$cluster\"}[$__range])))) > 0)",
     "legendFormat": "Data Upload (all schedules)"
    }
   ]
  },
  {
   "title": "Velero CR Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup CRs Total",
     "type": "stat",
     "description": "Total number of Velero Backup custom resources",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 476 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\"}) == 1)"
      }
     ]
    },
    {
     "title": "Backup CRs Enqueued",
     "type": "stat",
     "description": "Backup CRs in non-terminal phases (New, InProgress, WaitingForPluginOperations)",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 476 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=~\"New|InProgress|WaitingForPluginOperations|WaitingForPluginOperationsPartiallyFailed\"}) == 1) or vector(0)"
      }
     ]
    },
    {
     "title": "Backup CRs Enqueued - All Clusters",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 480 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (cluster) (max without(prometheus_replica) (velerobackup_phase{phase=~\"New|InProgress|WaitingForPluginOperations|WaitingForPluginOperationsPartiallyFailed\"}) == 1)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Backup CRs Enqueued - Cluster Level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 480 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (cluster) (max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=~\"New|InProgress|WaitingForPluginOperations|WaitingForPluginOperationsPartiallyFailed\"}) == 1)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Backup CRs by Phase",
     "type": "barchart",
     "description": "Backup CR count by phase",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 487 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"Completed\"}) == 1) or vector(0)",
       "legendFormat": "Comp"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"Failed\"}) == 1) or vector(0)",
       "legendFormat": "Fail"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"PartiallyFailed\"}) == 1) or vector(0)",
       "legendFormat": "PartFail"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"FailedValidation\"}) == 1) or vector(0)",
       "legendFormat": "FailVal"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"New\"}) == 1) or vector(0)",
       "legendFormat": "New"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"InProgress\"}) == 1) or vector(0)",
       "legendFormat": "InProg"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"Finalizing\"}) == 1) or vector(0)",
       "legendFormat": "Fin"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"FinalizingPartiallyFailed\"}) == 1) or vector(0)",
       "legendFormat": "FinPartFail"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"WaitingForPluginOperations\"}) == 1) or vector(0)",
       "legendFormat": "WPO"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"WaitingForPluginOperationsPartiallyFailed\"}) == 1) or vector(0)",
       "legendFormat": "WPOPF"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\", phase=\"Deleting\"}) == 1) or vector(0)",
       "legendFormat": "Del"
      }
     ]
    },
    {
     "title": "Backup CRs by Phase Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 487 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (phase) (max without(prometheus_replica) (velerobackup_phase{cluster=~\"$cluster\"}) == 1)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters by Backup Failure Rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (cluster) (max without(prometheus_replica) (increase(velero_backup_failure_total{schedule!=\"\"}[$__range]))) + sum by (cluster) (max without(prometheus_replica) (increase(velero_backup_partial_failure_total{schedule!=\"\"}[$__range]))) + sum by (cluster) (max without(prometheus_replica) (increase(velero_backup_validation_failure_total{schedule!=\"\"}[$__range])))) / (sum by (cluster) (max without(prometheus_replica) (increase(velero_backup_attempt_total{schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Schedules by Backup Failure Rate (Selected Cluster)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) + sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_partial_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) + sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_validation_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) ) / (sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{schedule}}"
      }
     ]
    },
    {
     "title": "Schedules by Backup Success Rate",
     "type": "table",
     "description": "Per-schedule backup success rate sorted worst-first",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) / (sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{schedule}}"
      }
     ]
    },
    {
     "title": "Backup Operations per Hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup success"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_partial_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup partial failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_validation_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup validation failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_warning_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup warning"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_deletion_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup deletion success"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_backup_deletion_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Backup deletion failure"
      }
     ]
    },
    {
     "title": "Total Backup Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (velero_backup_total{cluster=~\"$cluster\"}))",
       "legendFormat": "Backup Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Items - All Clusters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (cluster) (max without(prometheus_replica) (velero_backup_items_total))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Backup Items Total vs Errors",
     "type": "timeseries",
     "description": "Total backup items and item errors over time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (velero_backup_items_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}))",
       "legendFormat": "Items Total"
      },
      {
       "expr": "sum(max without(prometheus_replica) (velero_backup_items_errors{cluster=~\"$cluster\", schedule=~\"$schedule\"}))",
       "legendFormat": "Item Errors"
      }
     ]
    },
    {
     "title": "Backup Size - All Clusters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (cluster) (max without(prometheus_replica) (velero_backup_tarball_size_bytes))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Backup Size per Schedule",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (schedule) (avg_over_time(max without(prometheus_replica) (velero_backup_tarball_size_bytes{cluster=~\"$cluster\", schedule=~\"$schedule\"})[15m:]))",
       "legendFormat": "{{schedule}}"
      },
      {
       "expr": "avg_over_time(max without(prometheus_replica) (velero_backup_tarball_size_bytes{cluster=~\"$cluster\", schedule!~\".+\"})[15m:])",
       "legendFormat": "Non Scheduled"
      }
     ]
    },
    {
     "title": "Backup Durations",
     "type": "timeseries",
     "description": "Durations are grouped (<60s, <300s etc). Displays the count of active backups per duration group.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (increase(velero_backup_duration_seconds_bucket{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Deletion Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters by Deletion Failure Rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1745 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cluster) (max without(prometheus_replica) (increase(velero_backup_deletion_failure_total{schedule!=\"\"}[$__range]))) / (sum by (cluster) (max without(prometheus_replica) (increase(velero_backup_deletion_attempt_total{schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Schedules by Deletion Failure Rate (Selected Cluster)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1745 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_deletion_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) / (sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_deletion_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{schedule}}"
      }
     ]
    },
    {
     "title": "Deletion Operations (Schedule Level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1761 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_deletion_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "{{schedule}}-success"
      },
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_deletion_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "{{schedule}}-failure"
      },
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_backup_deletion_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "{{schedule}}-attempt"
      }
     ]
    }
   ]
  },
  {
   "title": "Restore Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Restore Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1791 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (velero_restore_total{cluster=~\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "Restore Failure Rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1791 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (increase(velero_restore_failed_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_restore_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Restore Success Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1791 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (increase(velero_restore_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) / (sum(max without(prometheus_replica) (increase(velero_restore_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[$__range]))) > 0)"
      }
     ]
    },
    {
     "title": "Clusters by Restore Failure Rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1796 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cluster) (max without(prometheus_replica) (increase(velero_restore_failed_total{schedule!=\"\"}[$__range]))) / (sum by (cluster) (max without(prometheus_replica) (increase(velero_restore_attempt_total{schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Schedules by Restore Failure Rate (Selected Cluster)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1796 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_restore_failed_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) / (sum by (schedule) (max without(prometheus_replica) (increase(velero_restore_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{schedule}}"
      }
     ]
    },
    {
     "title": "Schedules by Restore Success Rate",
     "type": "table",
     "description": "Per-schedule restore success rate sorted worst-first",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1796 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (schedule) (max without(prometheus_replica) (increase(velero_restore_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) / (sum by (schedule) (max without(prometheus_replica) (increase(velero_restore_attempt_total{cluster=~\"$cluster\", schedule=~\"$schedule\", schedule!=\"\"}[$__range]))) > 0)",
       "legendFormat": "{{schedule}}"
      }
     ]
    },
    {
     "title": "Restore Operations per Hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1804 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_restore_success_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Restore success"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_restore_failed_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Restore failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_restore_validation_failed_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Restore validation failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(velero_restore_partial_failure_total{cluster=~\"$cluster\", schedule=~\"$schedule\"}[1h])))) > 0",
       "legendFormat": "Restore partial failure"
      }
     ]
    },
    {
     "title": "Total Restore Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1804 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max without(prometheus_replica) (velero_restore_total{cluster=~\"$cluster\"}))",
       "legendFormat": "Restore Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Data Movement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Upload Totals",
     "type": "stat",
     "description": "Total number of data upload operations (success, failure, cancelled)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_success_total{cluster=~\"$cluster\"}[$__range]))))",
       "legendFormat": "Success"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_failure_total{cluster=~\"$cluster\"}[$__range]))))",
       "legendFormat": "Failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_cancel_total{cluster=~\"$cluster\"}[$__range]))))",
       "legendFormat": "Cancelled"
      }
     ]
    },
    {
     "title": "Clusters by Data Upload Failure Rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cluster) (max without(prometheus_replica) (increase(podvolume_data_upload_failure_total[$__range]))) / ((sum by (cluster) (max without(prometheus_replica) (increase(podvolume_data_upload_success_total[$__range]))) + sum by (cluster) (max without(prometheus_replica) (increase(podvolume_data_upload_failure_total[$__range])))) > 0)"
      }
     ]
    },
    {
     "title": "Data Upload Operations per Hour",
     "type": "timeseries",
     "description": "Tracks OADP node-agent uploads of CSI volume snapshot data to the backup storage location (e.g. object store). Success, failure, and cancellation rates.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_success_total{cluster=~\"$cluster\"}[1h])))) > 0",
       "legendFormat": "Data upload success"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_failure_total{cluster=~\"$cluster\"}[1h])))) > 0",
       "legendFormat": "Data upload failure"
      },
      {
       "expr": "round(sum(max without(prometheus_replica) (increase(podvolume_data_upload_cancel_total{cluster=~\"$cluster\"}[1h])))) > 0",
       "legendFormat": "Data upload cancelled"
      }
     ]
    }
   ]
  }
 ]
}