apiVersion: v2
appVersion: 2.17.3
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-217@sha256:f6ecdb0f27800d9d4f5dfa06ba639ebe2b29067e93da6513922aa93a3502be0c
type: application
version: 2.17.3
