apiVersion: v2
appVersion: 2.17.3
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-217@sha256:a7027158c0b762347e55d5c4212b6745b21df83421b874f37d02b1b87e4be016
type: application
version: 2.17.3
