apiVersion: v1
kind: Secret
metadata:
  name: provision-shards
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/resource-policy: keep
stringData:
  config: |
    provision_shards: []
