ARO_HCP_IMAGE_ACR ?= __SVCACRNAME__
HO_IMAGE_TAG ?= __HYPERSHIFTOPERATORIMAGETAG__
ED_IMAGE_TAG ?= __EXTERNALDNSIMAGETAG__
RESOURCEGROUP ?= __MANAGEMENTCLUSTERRG__
REGIONAL_RESOURCEGROUP ?= __REGIONRG__
ZONE_NAME ?= __REGIONALDNSSUBDOMAIN__.__BASEDNSZONENAME__
