name: 'ci-go'
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      - 'internal/**'
      - '**/go.mod'
      - '**/go.sum'
      - 'go.work'


jobs:
  test:
    name: test
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        directory: [frontend, internal]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.work'
          check-latest: true
          cache: false

      - name: 'Test'
        uses: robherley/go-test-action@v0.2.0
        with:
          moduleDirectory: ${{ matrix.directory }}

  lint:
    name: lint
    permissions:
      contents: 'read'
      pull-requests: read
      # Allow to write comments to annotate code in the PR.
      checks: write
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.work'
          check-latest: true
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # NOTE: This needs to be kept in sync with the version in .devcontainer/postCreate.sh
          version: v1.55.2
          working-directory: ${{ matrix.directory }}
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true