name: Publish Service Images
on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  DEPLOY_ENV: dev
  PERSIST: true
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build_push:
    name: 'Publish service images'
    permissions:
      id-token: 'write'
      contents: 'read'
    secrets: inherit
    uses: ./.github/workflows/services-ci.yml
    with:
      push: true
